//! Rust-generated byte vectors for the two ceremonies the Go bridge signs by hand.
//!
//! # What this adds that the merge gate cannot see
//!
//! `go-signed-message-parity-check` (2026-08-17) already reads Rust's
//! `sig_domain::AUTH_VERIFY_V2` and the Go literal and fails when the two **tags**
//! differ. That closed the direction which took mail/IMAP/CalDAV down for ~16 h,
//! and it is cheap enough to run synchronously on every merge on every machine.
//! Nothing here replaces it.
//!
//! But a signed message is not only its tag. `challenge_verify_signed_message` is
//! `AUTH_VERIFY_V2 ‖ actor_id ‖ nonce ‖ nest_id`, assembled through
//! `sig_domain::domain_separated`; `enrollment_signed_message` is
//! `DOMAIN ‖ ed25519 ‖ x25519 ‖ role`. **A change to the LAYOUT leaves both tag
//! literals untouched**, so the gate stays green while the bridge signs bytes nest
//! refuses — the 2026-08-17 outage entered from a third side.
//!
//! That is not a hypothetical. `sig_domain` already exports a second constructor,
//! [`domain_separated_length_prefixed`], which prefixes every element (the tag
//! included) with a big-endian `u64` length. Re-targeting this context onto it is
//! exactly the sort of injectivity hardening a future session does — and it would
//! change every signed byte, keep `AUTH_VERIFY_V2` spelled identically, and take
//! every bridge role off the air.
//!
//! So: the gate pins **source text matched by a regex**, this pins **bytes
//! produced by Rust**. Complementary by construction — do not rebuild the gate,
//! and do not delete it in favour of this.
//!
//! # Shape
//!
//! The fixture carries the INPUTS as well as the expected bytes, so
//! `internal/wsrpc/signed_message_bytes_test.go` reads its own vectors from here
//! and types no bytes of its own. A hand-typed vector on the Go side would be a
//! second copy that agrees with itself.
//!
//! There is deliberately no regen environment variable: the failure below prints
//! the exact file contents. A test with a write mode is a test that can be made to
//! bless whatever it finds — and this one exists precisely because the thing it
//! checks is invisible by inspection.

use fauna_protocol::auth::challenge_verify_signed_message;
use fauna_protocol::sig_domain::{CERT_BINDING_V1, domain_separated};
use fauna_protocol::wrapped_blob::enrollment_signed_message;
use std::path::PathBuf;

const FIXTURE: &str = "bins/fauna-bridges/internal/wsrpc/testdata/signed-message-bytes.json";

/// Distinguishable per-field fill bytes: every 32-byte field gets its own
/// pattern, so a swap of two adjacent fields changes the message. A shared
/// filler (all-zero, or the same byte everywhere) would let an
/// `ed25519 ‖ x25519` transposition pass.
const ACTOR_ID: [u8; 32] = [0x11; 32];
const NONCE: [u8; 32] = [0x22; 32];
/// The receiving nest's identity the verify binds (`login.md` § Binding the
/// nest) — its own fill so a nonce/nest transposition changes the message.
const NEST_ID: [u8; 32] = [0x55; 32];
/// The nest's channel-binding proof the bridge VERIFIES before it signs a
/// login (`login.md` § Binding the nest): `CERT_BINDING_V1 ‖ served_spki ‖
/// client_nonce`, the tagged half `auth_handlers::sign_channel_binding` emits.
const SERVED_SPKI: [u8; 32] = [0x66; 32];
const CLIENT_NONCE: [u8; 32] = [0x77; 32];

/// The bytes the nest signs — assembled here from the registry tag exactly as
/// `sign_channel_binding` does, so the Go verifier is pinned to the producer.
fn cert_binding_signed_message(spki: &[u8], client_nonce: &[u8]) -> Vec<u8> {
    let mut body = Vec::with_capacity(spki.len() + client_nonce.len());
    body.extend_from_slice(spki);
    body.extend_from_slice(client_nonce);
    domain_separated(CERT_BINDING_V1, &body)
}
const ED25519: [u8; 32] = [0x33; 32];
const X25519: [u8; 32] = [0x44; 32];

fn render() -> String {
    // Two enrollment roles of DIFFERENT lengths. The role is the one
    // variable-length element in either ceremony, so a length-prefixed
    // reformulation, or a role written at the wrong offset, shows up as a
    // difference in one vector and not the other.
    let enroll_roles = ["mta", "caldav"];

    let mut out = String::from("[\n");
    out.push_str(&format!(
        "  {{\n    \"ceremony\": \"challenge_verify\",\n    \"actor_id\": \"{}\",\n    \
         \"nonce\": \"{}\",\n    \"nest_id\": \"{}\",\n    \"signed_message\": \"{}\"\n  }}",
        hex::encode(ACTOR_ID),
        hex::encode(NONCE),
        hex::encode(NEST_ID),
        hex::encode(challenge_verify_signed_message(&ACTOR_ID, &NONCE, &NEST_ID)),
    ));
    // Two SPKI shapes: the TLS nest's 32-byte served SPKI and the plaintext
    // nest's EMPTY one (the message is then the nonce alone) — the shape the
    // bridge meets on a loopback dev nest, and the one a wrong offset hides.
    for spki in [&SERVED_SPKI[..], &[][..]] {
        out.push_str(&format!(
            ",\n  {{\n    \"ceremony\": \"cert_binding\",\n    \"spki_sha256\": \"{}\",\n    \
             \"client_nonce\": \"{}\",\n    \"signed_message\": \"{}\"\n  }}",
            hex::encode(spki),
            hex::encode(CLIENT_NONCE),
            hex::encode(cert_binding_signed_message(spki, &CLIENT_NONCE)),
        ));
    }
    for role in enroll_roles {
        out.push_str(&format!(
            ",\n  {{\n    \"ceremony\": \"enroll\",\n    \"role\": \"{role}\",\n    \
             \"ed25519_pubkey\": \"{}\",\n    \"x25519_pubkey\": \"{}\",\n    \
             \"signed_message\": \"{}\"\n  }}",
            hex::encode(ED25519),
            hex::encode(X25519),
            hex::encode(enrollment_signed_message(role, &ED25519, &X25519)),
        ));
    }
    out.push_str("\n]\n");
    out
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("libs/fauna-protocol sits two levels under the workspace root")
        .to_path_buf()
}

#[test]
fn the_go_signed_message_fixture_matches_the_live_rust_bytes() {
    let rendered = render();
    let committed = std::fs::read_to_string(workspace_root().join(FIXTURE)).unwrap_or_default();

    assert_eq!(
        committed.trim_end(),
        rendered.trim_end(),
        "\n\nthe committed Go signed-message fixture is STALE (or missing).\n\n\
         The BYTES a bridge must sign changed, even if the domain tag did not — which \
         is exactly the case `go-signed-message-parity-check` cannot see. Until the \
         Go builders in internal/wsrpc/{{auth,enroll}}.go are changed to match, every \
         bridge role (MTA, MDA, CalDAV) will enrol and then fail its first bearer \
         acquisition with fauna.auth.signature_failed: mail, IMAP and CalDAV down.\n\n\
         If that change was deliberate, update BOTH sides in the same commit and write \
         EXACTLY this into {FIXTURE}:\n\n{rendered}"
    );
}

#[test]
fn the_vectors_bind_every_field() {
    // A fixture whose vectors cannot distinguish the fields would pass while the
    // Go builder concatenated them in the wrong order. Assert the fill bytes do
    // their job before trusting any comparison against them.
    let base = challenge_verify_signed_message(&ACTOR_ID, &NONCE, &NEST_ID);
    assert_ne!(
        base,
        challenge_verify_signed_message(&NONCE, &ACTOR_ID, &NEST_ID),
        "actor_id and nonce are not distinguishable in this vector — a transposed \
         Go builder would match the fixture"
    );
    assert_ne!(
        base,
        challenge_verify_signed_message(&ACTOR_ID, &NEST_ID, &NONCE),
        "nonce and nest_id are not distinguishable in this vector — a transposed \
         Go builder would match the fixture"
    );

    assert_ne!(
        cert_binding_signed_message(&SERVED_SPKI, &CLIENT_NONCE),
        cert_binding_signed_message(&CLIENT_NONCE, &SERVED_SPKI),
        "spki and client_nonce are not distinguishable in this vector"
    );

    let enroll = enrollment_signed_message("mta", &ED25519, &X25519);
    assert_ne!(
        enroll,
        enrollment_signed_message("mta", &X25519, &ED25519),
        "the two enrollment pubkeys are not distinguishable in this vector"
    );
    assert_ne!(
        enroll,
        enrollment_signed_message("mda", &ED25519, &X25519),
        "the role is not bound into the enrollment message"
    );
}
