

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureDroppedCallback(
				UniffiForeignFutureDroppedCallback cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static uint64_t call_UniffiCallbackInterfaceClone(
				UniffiCallbackInterfaceClone cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureResultU8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureResultU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureResultI8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureResultI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureResultU16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureResultU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureResultI16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureResultI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureResultU32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureResultU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureResultI32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureResultI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureResultU64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureResultU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureResultI64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureResultI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureResultF32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureResultF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureResultF64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureResultF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureResultRustBuffer result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureResultRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureResultVoid result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureResultVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_APPVIEW_SERVICE_DID
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_APPVIEW_SERVICE_DID
RustBuffer uniffi_fauna_bridge_atproto_fn_func_appview_service_did(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_AUTHORIZE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_AUTHORIZE
RustBuffer uniffi_fauna_bridge_atproto_fn_func_authorize(RustBuffer input, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_DESCRIBE_SCOPE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_DESCRIBE_SCOPE
RustBuffer uniffi_fauna_bridge_atproto_fn_func_describe_scope(RustBuffer scope, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_VALIDATE_CLIENT_ASSERTION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_VALIDATE_CLIENT_ASSERTION
RustBuffer uniffi_fauna_bridge_atproto_fn_func_validate_client_assertion(RustBuffer assertion_type, RustBuffer assertion, RustBuffer client, RustBuffer expect, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_VALIDATE_DPOP_PROOF
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_VALIDATE_DPOP_PROOF
RustBuffer uniffi_fauna_bridge_atproto_fn_func_validate_dpop_proof(RustBuffer compact, RustBuffer expect, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_CHECK_FETCH_TARGET
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_CHECK_FETCH_TARGET
RustBuffer uniffi_fauna_bridge_atproto_fn_func_check_fetch_target(RustBuffer target, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_ATTACH_CLIENT_JWKS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_ATTACH_CLIENT_JWKS
RustBuffer uniffi_fauna_bridge_atproto_fn_func_attach_client_jwks(RustBuffer client, RustBuffer body, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_PARSE_CLIENT_METADATA
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_PARSE_CLIENT_METADATA
RustBuffer uniffi_fauna_bridge_atproto_fn_func_parse_client_metadata(RustBuffer client_id, RustBuffer body, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_PLAN_CLIENT_ID
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_PLAN_CLIENT_ID
RustBuffer uniffi_fauna_bridge_atproto_fn_func_plan_client_id(RustBuffer client_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_ATPROTO_PDS_HOST
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_ATPROTO_PDS_HOST
RustBuffer uniffi_fauna_bridge_atproto_fn_func_atproto_pds_host(RustBuffer apex_domain, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_ATPROTO_PDS_SERVICE_DID
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_ATPROTO_PDS_SERVICE_DID
RustBuffer uniffi_fauna_bridge_atproto_fn_func_atproto_pds_service_did(RustBuffer apex_domain, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_OAUTH_ISSUER
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_OAUTH_ISSUER
RustBuffer uniffi_fauna_bridge_atproto_fn_func_oauth_issuer(RustBuffer host, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_OAUTH_PROTECTED_RESOURCE_DOCUMENT
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_OAUTH_PROTECTED_RESOURCE_DOCUMENT
RustBuffer uniffi_fauna_bridge_atproto_fn_func_oauth_protected_resource_document(RustBuffer apex_domain, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_FINISH_PAR_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_FINISH_PAR_REQUEST
RustBuffer uniffi_fauna_bridge_atproto_fn_func_finish_par_request(RustBuffer pending, RustBuffer records, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_PLAN_PAR_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_PLAN_PAR_REQUEST
RustBuffer uniffi_fauna_bridge_atproto_fn_func_plan_par_request(RustBuffer request, RustBuffer client, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_CHECK_GRANT_EXPANSION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_CHECK_GRANT_EXPANSION
RustBuffer uniffi_fauna_bridge_atproto_fn_func_check_grant_expansion(uint32_t include_count, RustBuffer expanded, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_EXPAND_PERMISSION_SET
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_EXPAND_PERMISSION_SET
RustBuffer uniffi_fauna_bridge_atproto_fn_func_expand_permission_set(RustBuffer include, RustBuffer record_dag_cbor, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_PARSE_INCLUDE_SCOPE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_FN_FUNC_PARSE_INCLUDE_SCOPE
RustBuffer uniffi_fauna_bridge_atproto_fn_func_parse_include_scope(RustBuffer scope, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUSTBUFFER_ALLOC
RustBuffer ffi_fauna_bridge_atproto_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_fauna_bridge_atproto_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUSTBUFFER_FREE
void ffi_fauna_bridge_atproto_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUSTBUFFER_RESERVE
RustBuffer ffi_fauna_bridge_atproto_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_U8
void ffi_fauna_bridge_atproto_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_U8
void ffi_fauna_bridge_atproto_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_U8
void ffi_fauna_bridge_atproto_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_fauna_bridge_atproto_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_I8
void ffi_fauna_bridge_atproto_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_I8
void ffi_fauna_bridge_atproto_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_I8
void ffi_fauna_bridge_atproto_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_I8
int8_t ffi_fauna_bridge_atproto_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_U16
void ffi_fauna_bridge_atproto_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_U16
void ffi_fauna_bridge_atproto_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_U16
void ffi_fauna_bridge_atproto_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_fauna_bridge_atproto_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_I16
void ffi_fauna_bridge_atproto_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_I16
void ffi_fauna_bridge_atproto_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_I16
void ffi_fauna_bridge_atproto_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_I16
int16_t ffi_fauna_bridge_atproto_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_U32
void ffi_fauna_bridge_atproto_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_U32
void ffi_fauna_bridge_atproto_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_U32
void ffi_fauna_bridge_atproto_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_fauna_bridge_atproto_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_I32
void ffi_fauna_bridge_atproto_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_I32
void ffi_fauna_bridge_atproto_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_I32
void ffi_fauna_bridge_atproto_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_I32
int32_t ffi_fauna_bridge_atproto_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_U64
void ffi_fauna_bridge_atproto_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_U64
void ffi_fauna_bridge_atproto_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_U64
void ffi_fauna_bridge_atproto_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_fauna_bridge_atproto_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_I64
void ffi_fauna_bridge_atproto_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_I64
void ffi_fauna_bridge_atproto_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_I64
void ffi_fauna_bridge_atproto_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_I64
int64_t ffi_fauna_bridge_atproto_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_F32
void ffi_fauna_bridge_atproto_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_F32
void ffi_fauna_bridge_atproto_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_F32
void ffi_fauna_bridge_atproto_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_F32
float ffi_fauna_bridge_atproto_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_F64
void ffi_fauna_bridge_atproto_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_F64
void ffi_fauna_bridge_atproto_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_F64
void ffi_fauna_bridge_atproto_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_F64
double ffi_fauna_bridge_atproto_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_fauna_bridge_atproto_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_fauna_bridge_atproto_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_fauna_bridge_atproto_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_fauna_bridge_atproto_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_POLL_VOID
void ffi_fauna_bridge_atproto_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_CANCEL_VOID
void ffi_fauna_bridge_atproto_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_FREE_VOID
void ffi_fauna_bridge_atproto_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_RUST_FUTURE_COMPLETE_VOID
void ffi_fauna_bridge_atproto_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_APPVIEW_SERVICE_DID
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_APPVIEW_SERVICE_DID
uint16_t uniffi_fauna_bridge_atproto_checksum_func_appview_service_did(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_AUTHORIZE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_AUTHORIZE
uint16_t uniffi_fauna_bridge_atproto_checksum_func_authorize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_DESCRIBE_SCOPE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_DESCRIBE_SCOPE
uint16_t uniffi_fauna_bridge_atproto_checksum_func_describe_scope(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_VALIDATE_CLIENT_ASSERTION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_VALIDATE_CLIENT_ASSERTION
uint16_t uniffi_fauna_bridge_atproto_checksum_func_validate_client_assertion(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_VALIDATE_DPOP_PROOF
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_VALIDATE_DPOP_PROOF
uint16_t uniffi_fauna_bridge_atproto_checksum_func_validate_dpop_proof(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_CHECK_FETCH_TARGET
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_CHECK_FETCH_TARGET
uint16_t uniffi_fauna_bridge_atproto_checksum_func_check_fetch_target(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_ATTACH_CLIENT_JWKS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_ATTACH_CLIENT_JWKS
uint16_t uniffi_fauna_bridge_atproto_checksum_func_attach_client_jwks(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_PARSE_CLIENT_METADATA
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_PARSE_CLIENT_METADATA
uint16_t uniffi_fauna_bridge_atproto_checksum_func_parse_client_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_PLAN_CLIENT_ID
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_PLAN_CLIENT_ID
uint16_t uniffi_fauna_bridge_atproto_checksum_func_plan_client_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_ATPROTO_PDS_HOST
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_ATPROTO_PDS_HOST
uint16_t uniffi_fauna_bridge_atproto_checksum_func_atproto_pds_host(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_ATPROTO_PDS_SERVICE_DID
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_ATPROTO_PDS_SERVICE_DID
uint16_t uniffi_fauna_bridge_atproto_checksum_func_atproto_pds_service_did(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_OAUTH_ISSUER
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_OAUTH_ISSUER
uint16_t uniffi_fauna_bridge_atproto_checksum_func_oauth_issuer(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_OAUTH_PROTECTED_RESOURCE_DOCUMENT
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_OAUTH_PROTECTED_RESOURCE_DOCUMENT
uint16_t uniffi_fauna_bridge_atproto_checksum_func_oauth_protected_resource_document(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_FINISH_PAR_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_FINISH_PAR_REQUEST
uint16_t uniffi_fauna_bridge_atproto_checksum_func_finish_par_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_PLAN_PAR_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_PLAN_PAR_REQUEST
uint16_t uniffi_fauna_bridge_atproto_checksum_func_plan_par_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_CHECK_GRANT_EXPANSION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_CHECK_GRANT_EXPANSION
uint16_t uniffi_fauna_bridge_atproto_checksum_func_check_grant_expansion(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_EXPAND_PERMISSION_SET
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_EXPAND_PERMISSION_SET
uint16_t uniffi_fauna_bridge_atproto_checksum_func_expand_permission_set(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_PARSE_INCLUDE_SCOPE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_BRIDGE_ATPROTO_CHECKSUM_FUNC_PARSE_INCLUDE_SCOPE
uint16_t uniffi_fauna_bridge_atproto_checksum_func_parse_include_scope(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_FAUNA_BRIDGE_ATPROTO_UNIFFI_CONTRACT_VERSION
uint32_t ffi_fauna_bridge_atproto_uniffi_contract_version(void
    
);
#endif

