// Generated by scripts/ui-ids-generate.py from tests/e2e-unified/ui.yaml. DO NOT EDIT.
//
// The `payments` plane's element ids, in the isolated render directory rather
// than in the shared table: folding the build condition to false does not
// unlink a module, so a shared table would ship these ids in every flavor
// (dynamic-features.md § What "completely compiled away" means, criterion 1).
// Import this ONLY from behind `__FAUNA_PAYMENTS__`.

export const PAYMENTS_IDS = {
  COMPOSE_SELL_ASKING_PRICE: 'compose-sell-asking-price',
  POST_TIP_COUNT: 'post-tip-count',
  POST_TIP_ITEM: 'post-tip-item',
  POST_TIP_LIST: 'post-tip-list',
  POST_TIP_LIST_BUTTON: 'post-tip-list-button',
  POST_TIP_TOTAL: 'post-tip-total',
  SUBSCRIPTION_CLAIM_CODE: 'subscription-claim-code',
  SUBSCRIPTION_CLAIM_LIST: 'subscription-claim-list',
  SUBSCRIPTION_CLAIM_MINT_BUTTON: 'subscription-claim-mint-button',
  SUBSCRIPTION_CLAIM_REDEEM_BUTTON: 'subscription-claim-redeem-button',
  SUBSCRIPTION_CLAIM_REDEEM_INPUT: 'subscription-claim-redeem-input',
  SUBSCRIPTION_CLAIM_ROW: 'subscription-claim-row',
  SUBSCRIPTION_CLAIM_SECTION: 'subscription-claim-section',
  SUBSCRIPTION_CLAIM_STATUS: 'subscription-claim-status',
  SUBSCRIPTION_CLAIM_TIER: 'subscription-claim-tier',
  SUBSCRIPTION_CLAIM_TIER_SELECT: 'subscription-claim-tier-select',
  SUBSCRIPTION_PROVIDER_ADD_BUTTON: 'subscription-provider-add-button',
  SUBSCRIPTION_PROVIDER_FORM: 'subscription-provider-form',
  SUBSCRIPTION_PROVIDER_FORM_CANCEL: 'subscription-provider-form-cancel',
  SUBSCRIPTION_PROVIDER_FORM_KIND: 'subscription-provider-form-kind',
  SUBSCRIPTION_PROVIDER_FORM_SAVE: 'subscription-provider-form-save',
  SUBSCRIPTION_PROVIDER_FORM_SECRET: 'subscription-provider-form-secret',
  SUBSCRIPTION_PROVIDER_FORM_TIER_MAP: 'subscription-provider-form-tier-map',
  SUBSCRIPTION_PROVIDER_FORM_WEBHOOK_URL: 'subscription-provider-form-webhook-url',
  SUBSCRIPTION_PROVIDER_FORM_WEBHOOK_URL_COPY_BUTTON: 'subscription-provider-form-webhook-url-copy-button',
  SUBSCRIPTION_PROVIDER_KIND: 'subscription-provider-kind',
  SUBSCRIPTION_PROVIDER_LIST: 'subscription-provider-list',
  SUBSCRIPTION_PROVIDER_REMOVE_BUTTON: 'subscription-provider-remove-button',
  SUBSCRIPTION_PROVIDER_ROW: 'subscription-provider-row',
  SUBSCRIPTION_PROVIDER_SECTION: 'subscription-provider-section',
  SUBSCRIPTION_PROVIDER_STATUS: 'subscription-provider-status',
  SUBSCRIPTION_TIER_FORM_ASKING_PRICE: 'subscription-tier-form-asking-price',
} as const;

export type PaymentsElementId = (typeof PAYMENTS_IDS)[keyof typeof PAYMENTS_IDS];
