"""tier_1: scripts/generate-windows-fake-bases.py emits a compile-safe abstract
FakeBase for every generated UniFFI C# interface.

Pure in-process parsing tests against synthetic fixture `.cs` files — no cargo, no
dotnet, no nest, no driver. The real generated bindings
(apps/fauna-windows/FaunaApp/FaunaApp.Core/Generated/uniffi/) are gitignored and not
guaranteed present in a clean checkout, so this suite never depends on them.

See docs/goal/architecture/merge-gate-check.md § Merge-gate check (win). Guards the
class of break fixed 2026-07-23: a UniFFI interface grows a member and a hand-written
C# test fake (FakeAccountRegistry et al.) stops compiling (CS0535) — four real
instances. Generated fake bases make the growth compile clean by
construction (new member throws NotSupportedException at runtime, never a compile
break) — the growth-simulation test below is the property those four incidents
lacked.
"""

import importlib.util
import os
import re

import pytest

pytestmark = pytest.mark.tier_1

_HERE = os.path.dirname(__file__)
_REPO = os.path.normpath(os.path.join(_HERE, "..", "..", ".."))
_SCRIPT = os.path.join(_REPO, "scripts", "generate-windows-fake-bases.py")


def _load():
    spec = importlib.util.spec_from_file_location("generate_windows_fake_bases", _SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_gen = _load()


def _write(tmp_path, filename, text):
    d = tmp_path / "uniffi"
    d.mkdir(exist_ok=True)
    (d / filename).write_text(text, encoding="utf-8")
    return d


_ACCOUNT_REGISTRY_CS = """// <auto-generated>
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
namespace uniffi.fauna_ffi;

internal interface IFfiAccountRegistry {
    /// <summary>Active actor id.</summary>
    string? Active();
    FfiAccountEntry[] List();
    void Remove(string @actorId);
}
internal class FfiAccountRegistry : IFfiAccountRegistry, IDisposable {
    public void Dispose() { }
}
"""


# ── Basic shape ────────────────────────────────────────────────────────────


def test_emits_one_fake_base_per_interface(tmp_path):
    d = _write(tmp_path, "fauna_ffi.cs", _ACCOUNT_REGISTRY_CS)
    content, count = _gen._generate(d)
    assert count == 1
    assert "internal abstract class FfiAccountRegistryFakeBase : IFfiAccountRegistry" in content


def test_fake_base_class_is_internal_not_public(tmp_path):
    """Real regression (2026-07-23, first run against actual generated bindings):
    a `public abstract class` referencing an `internal`-declared parameter/return
    type (many are, e.g. ThreadId/TypedAddress/ContentLabelEntry in the
    conversations interface) is CS0050/CS0051 'inconsistent accessibility'. The
    interfaces themselves are always `internal`, so the base class must match —
    members stay `public` (implicit interface implementation requires it)."""
    d = _write(tmp_path, "fauna_ffi.cs", _ACCOUNT_REGISTRY_CS)
    content, _ = _gen._generate(d)
    assert "public abstract class" not in content
    assert "internal abstract class" in content


def test_namespace_and_usings_preserved(tmp_path):
    d = _write(tmp_path, "fauna_ffi.cs", _ACCOUNT_REGISTRY_CS)
    content, _ = _gen._generate(d)
    assert "namespace uniffi.fauna_ffi" in content
    assert "using System;" in content
    assert "using System.Collections.Generic;" in content


def test_every_member_is_virtual_and_throws(tmp_path):
    d = _write(tmp_path, "fauna_ffi.cs", _ACCOUNT_REGISTRY_CS)
    content, _ = _gen._generate(d)
    assert "public virtual string? Active() =>" in content
    assert "public virtual FfiAccountEntry[] List() =>" in content
    assert "public virtual void Remove(string @actorId) =>" in content
    assert content.count("throw new NotSupportedException(") == 3


def test_throw_message_names_interface_and_member(tmp_path):
    d = _write(tmp_path, "fauna_ffi.cs", _ACCOUNT_REGISTRY_CS)
    content, _ = _gen._generate(d)
    assert "IFfiAccountRegistry.Active: outside this fake's implemented surface" in content


def test_hand_written_class_declaration_is_not_mistaken_for_an_interface(tmp_path):
    """`internal class FfiAccountRegistry : IFfiAccountRegistry, IDisposable` must never
    itself be parsed as a fakeable interface — only the `interface` keyword qualifies."""
    d = _write(tmp_path, "fauna_ffi.cs", _ACCOUNT_REGISTRY_CS)
    _content, count = _gen._generate(d)
    assert count == 1  # the class declaration did not also register as an interface


# ── Async methods (Task-returning) ──────────────────────────────────────────


_ASYNC_CS = """#nullable enable
using System;
using System.Threading.Tasks;
namespace uniffi.fauna_ffi;

internal interface IFfiAccountClient {
    Task<bool> AmIAdmin();
    Task<FfiUpgradeReply> Upgrade(string @tier, string @inviteCode);
}
"""


def test_async_task_returning_methods_throw_synchronously(tmp_path):
    """Spec: 'Async members (Task-returning) throw synchronously — fine for a fake.'
    An expression-bodied throw is valid on a Task<T>-returning member (never awaited,
    never a faulted Task) — this is the shape, not a wrapped/faulted-task alternative."""
    d = _write(tmp_path, "fauna_ffi.cs", _ASYNC_CS)
    content, _ = _gen._generate(d)
    assert "public virtual Task<bool> AmIAdmin() =>" in content
    assert "public virtual Task<FfiUpgradeReply> Upgrade(string @tier, string @inviteCode) =>" in content


# ── Dispose handling ─────────────────────────────────────────────────────────


_DISPOSE_IN_BODY_CS = """#nullable enable
using System;
namespace uniffi.fauna_ffi;

internal interface IFfiSomethingWithDispose {
    void Dispose();
    string? Foo();
}
"""


def test_dispose_declared_in_body_is_a_noop_never_a_throw(tmp_path):
    """Teardown must not explode a passing test — Dispose is the one member that is
    never a throw, even though it is otherwise treated like every other member."""
    d = _write(tmp_path, "fauna_ffi.cs", _DISPOSE_IN_BODY_CS)
    content, _ = _gen._generate(d)
    assert "public virtual void Dispose() { }" in content
    # Foo still throws normally — only Dispose is special-cased.
    assert 'IFfiSomethingWithDispose.Foo: outside' in content


_DISPOSE_VIA_BASE_LIST_CS = """#nullable enable
using System;
namespace uniffi.fauna_ffi;

internal interface IFfiDisposableThing : IDisposable {
    string? Foo();
}
"""


def test_dispose_synthesized_when_interface_inherits_idisposable(tmp_path):
    """An interface that inherits IDisposable via its base list (rather than
    redeclaring Dispose() in its own body) still needs a no-op Dispose synthesized,
    or the emitted abstract class would not compile against IDisposable's contract."""
    d = _write(tmp_path, "fauna_ffi.cs", _DISPOSE_VIA_BASE_LIST_CS)
    content, _ = _gen._generate(d)
    assert "public virtual void Dispose() { }" in content


# ── Properties ───────────────────────────────────────────────────────────────


_PROPERTY_CS = """#nullable enable
using System;
namespace uniffi.fauna_ffi;

internal interface IFfiWithProperty {
    string Name { get; set; }
    int ReadOnlyCount { get; }
}
"""


def test_property_members_get_virtual_throwing_accessors(tmp_path):
    d = _write(tmp_path, "fauna_ffi.cs", _PROPERTY_CS)
    content, _ = _gen._generate(d)
    assert "public virtual string Name" in content
    assert "public virtual int ReadOnlyCount" in content
    assert content.count("get => throw new NotSupportedException(") == 2
    assert content.count("set => throw new NotSupportedException(") == 1


# ── Doc-comment prose must never corrupt member splitting ──────────────────


_PROSE_WITH_SEMICOLON_AND_BRACE_CS = """#nullable enable
using System;
namespace uniffi.fauna_client_mail_settings;

internal interface IMailSettingsMachine {
    /// <summary>
    /// The two policy flags are passed in (the [`NestClient`] seam carries no
    /// `setup.status` read); the caller reads them from `fauna.setup.status`
    /// (`SetupStatusReply.{email_enabled, auto_enable_mail_for_new_users}`).
    /// </summary>
    /// <exception cref="DispatchException"></exception>
    Task<SecretString?> AutoEnableMailForNewUser(bool @deploymentMailEnabled);
    Task Dispatch(MailSettingsAction @action);
}
"""


def test_prose_semicolon_and_brace_inside_doc_comment_does_not_corrupt_splitting(tmp_path):
    """Real regression (2026-07-23, first run against actual generated bindings):
    an English semicolon in a `///` doc-comment sentence ('...read); the caller...')
    and a markdown code-span brace pair ('`Foo.{a, b}`') were mistaken for member
    boundaries, corrupting the split across two real methods. Comments must be
    stripped BEFORE brace/semicolon-based splitting, never after."""
    d = _write(tmp_path, "fauna_client_mail_settings.cs", _PROSE_WITH_SEMICOLON_AND_BRACE_CS)
    content, count = _gen._generate(d)
    assert count == 1
    assert "public virtual Task<SecretString?> AutoEnableMailForNewUser(bool @deploymentMailEnabled) =>" in content
    assert "public virtual Task Dispatch(MailSettingsAction @action) =>" in content


# ── Using-alias directives (file-scoped in C#) ──────────────────────────────


_ALIAS_CS = """#nullable enable
using System;
using System.Threading.Tasks;
namespace uniffi.fauna_conversations;
using ThreadId = String;
using FfiConverterTypeThreadId = FfiConverterString;

internal interface IConversationsManager {
    ThreadId? AddParticipant(ThreadId @id, TypedAddress @addr);
}
"""


def test_alias_form_using_directives_are_captured(tmp_path):
    """Real regression (2026-07-23): `using ThreadId = String;` is a using-ALIAS
    directive, not an import — the plain `using [\\w.]+;` regex silently skipped it,
    leaving `ThreadId` undefined (CS0246) in the generated file. Must be captured
    like any other using line."""
    d = _write(tmp_path, "fauna_conversations.cs", _ALIAS_CS)
    content, _ = _gen._generate(d)
    assert "using ThreadId = String;" in content


_ALIAS_CONFLICT_A_CS = """#nullable enable
namespace uniffi.fauna_core;
using FfiConverterTypeSecretString = FfiConverterString;

internal interface IFooA {
    string? Get();
}
"""

_ALIAS_CONFLICT_B_CS = """#nullable enable
namespace uniffi.fauna_client_dns;
using FfiConverterTypeSecretString = uniffi.fauna_core.FfiConverterString;

internal interface IFooB {
    string? Get();
}
"""


def test_same_named_alias_with_different_rhs_across_files_does_not_collide(tmp_path):
    """Real pattern in the actual bindings: `FfiConverterTypeSecretString` aliases to
    the unqualified `FfiConverterString` inside fauna_core.cs itself, but to the
    fully-qualified `uniffi.fauna_core.FfiConverterString` from every OTHER crate's
    file. Using-alias directives are file-scoped in C#, so hoisting both into one
    shared top-of-file list would be a genuine CS7007 conflict (duplicate alias for
    one name) — each file's usings must stay scoped inside its OWN namespace block."""
    d = tmp_path / "uniffi"
    d.mkdir()
    (d / "fauna_core.cs").write_text(_ALIAS_CONFLICT_A_CS, encoding="utf-8")
    (d / "fauna_client_dns.cs").write_text(_ALIAS_CONFLICT_B_CS, encoding="utf-8")
    content, count = _gen._generate(d)
    assert count == 2
    assert "using FfiConverterTypeSecretString = FfiConverterString;" in content
    assert "using FfiConverterTypeSecretString = uniffi.fauna_core.FfiConverterString;" in content


# ── Multiple files / namespaces ──────────────────────────────────────────────


_OTHER_CRATE_CS = """#nullable enable
using System;
namespace uniffi.fauna_core;

internal interface IFooMachine {
    string? State();
}
"""


def test_multiple_source_files_each_get_their_own_namespace_block(tmp_path):
    d = tmp_path / "uniffi"
    d.mkdir()
    (d / "fauna_ffi.cs").write_text(_ACCOUNT_REGISTRY_CS, encoding="utf-8")
    (d / "fauna_core.cs").write_text(_OTHER_CRATE_CS, encoding="utf-8")
    content, count = _gen._generate(d)
    assert count == 2
    assert "namespace uniffi.fauna_ffi" in content
    assert "namespace uniffi.fauna_core" in content
    assert "internal abstract class FooMachineFakeBase : IFooMachine" in content


def test_file_with_no_interfaces_contributes_nothing(tmp_path):
    d = tmp_path / "uniffi"
    d.mkdir()
    (d / "empty.cs") .write_text(
        "#nullable enable\nnamespace uniffi.fauna_empty;\ninternal static class Helpers {}\n",
        encoding="utf-8",
    )
    content, count = _gen._generate(d)
    assert count == 0
    assert "uniffi.fauna_empty" not in content


# ── The growth-simulation property (the whole point of the track) ───────────


def test_growth_simulation_new_member_compiles_and_would_auto_throw(tmp_path):
    """The exact property the four historical CS0535 incidents lacked: appending a
    member to a faked interface must not require ANY change to a hand-written fake —
    the generated base picks it up automatically as a virtual throw."""
    d = _write(tmp_path, "fauna_ffi.cs", _ACCOUNT_REGISTRY_CS)
    before, _ = _gen._generate(d)
    assert "ClearNestBinding" not in before

    grown = _ACCOUNT_REGISTRY_CS.replace(
        "    void Remove(string @actorId);\n",
        "    void Remove(string @actorId);\n    void ClearNestBinding(string @actorId);\n",
    )
    (d / "fauna_ffi.cs").write_text(grown, encoding="utf-8")
    after, _ = _gen._generate(d)
    assert "public virtual void ClearNestBinding(string @actorId) =>" in after
    assert "IFfiAccountRegistry.ClearNestBinding: outside this fake's implemented surface" in after


def test_a_parser_miss_fails_loudly_rather_than_silently_dropping_a_member(tmp_path):
    """'A parser miss self-diagnoses as CS0535 in the generated base at the same
    gate' (spec) — but that only holds if unparseable input raises rather than being
    silently skipped. Malformed interface body -> ParseError, not a partial class."""
    malformed = _ACCOUNT_REGISTRY_CS.replace(
        "void Remove(string @actorId);", "void Remove(string @actorId"  # missing `)`+`;`
    )
    d = _write(tmp_path, "fauna_ffi.cs", malformed)
    with pytest.raises(_gen.ParseError):
        _gen._generate(d)


def test_missing_source_dir_raises_with_actionable_message(tmp_path):
    with pytest.raises(_gen.ParseError, match="windows-ffi"):
        _gen._generate(tmp_path / "does-not-exist")


# ── Migration invariant: no test class implements a generated UniFFI interface
#    directly — every fake inherits its generated `<X>FakeBase`. ──────────────────
#
# The rule is ratified in docs/goal/architecture/apps/windows.md § Workspace Layout
# ("Test fakes for generated UniFFI interfaces inherit the generated `<X>FakeBase`,
# never implement the interface directly"). A hand-listed set of fakes cannot hold it:
# the list this test used to carry named three, and eleven more fakes were written
# against the raw interface afterwards — each one growth away from the whole-project
# CS0535 the base classes exist to end (`FakeMailExportMachine`, 2026-09-21).
#
# The gitignored bindings are not guaranteed present here, so the scan cannot ask "is
# this interface UniFFI-generated?". It asks the tracked tree the inverse question: an
# interface a test class implements is legitimate only if it is DECLARED in tracked
# hand-written C# under FaunaApp/ (a project seam such as `IStringLocalizer`) or is a
# BCL interface. Anything else can only have come from the generated bindings, and a
# fake for it must inherit `<X>FakeBase`. Project seams need no list — the scan finds
# them; only a genuinely external interface is named in `_EXTERNAL_INTERFACES`.

_APP_DIR = os.path.join(_REPO, "apps", "fauna-windows", "FaunaApp")
_TESTS_DIR = os.path.join(_APP_DIR, "FaunaApp.Tests")

# Interfaces a fake may implement directly because they are declared neither by the
# generated bindings nor anywhere in this tree. Add a name only for a BCL / NuGet
# interface, with the reason.
_EXTERNAL_INTERFACES = frozenset(
    {
        "IDisposable",  # BCL — fixtures, and `Disposable*` doubles that also inherit a base
        "INotifyPropertyChanged",  # BCL — observer test doubles
    }
)

# `Generated/` is gitignored output (the bindings and FakeBases.g.cs itself, whose bases
# implement every interface directly by design); `bin`/`obj` are build output.
_SKIPPED_DIRS = frozenset({"Generated", "bin", "obj"})

_INTERFACE_DECL_RE = re.compile(r"\binterface\s+(I[A-Z]\w*)")
_TYPE_KEYWORD_RE = re.compile(r"\b(?:class|struct|record)\s+\w+")
_INTERFACE_NAME_RE = re.compile(r"^I[A-Z]\w*$")


def _strip_line_comments(text):
    # Line comments only: a `/*` inside a string literal (`"**/*.cs"`) would otherwise
    # open a block comment that swallows the rest of the file and hides violations.
    return re.sub(r"//[^\n]*", "", text)


def _skip_ws(text, i):
    while i < len(text) and text[i].isspace():
        i += 1
    return i


def _skip_group(text, i, open_ch, close_ch):
    """Index just past the balanced group opening at text[i]; `i` unchanged if none."""
    if i >= len(text) or text[i] != open_ch:
        return i
    depth = 0
    while i < len(text):
        if text[i] == open_ch:
            depth += 1
        elif text[i] == close_ch:
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return i


def _split_bases(base_list):
    """`A, B<C, D>, Ns.E` -> ['A', 'B', 'E'] (top-level commas; generics and namespace
    qualification dropped)."""
    bases, depth, current = [], 0, []
    for ch in base_list:
        if ch == "<":
            depth += 1
        elif ch == ">":
            depth -= 1
        if ch == "," and depth == 0:
            bases.append("".join(current))
            current = []
        else:
            current.append(ch)
    bases.append("".join(current))
    names = []
    for b in bases:
        b = re.sub(r"<.*", "", b.strip(), flags=re.DOTALL)  # drop generic arguments
        if b:
            names.append(b.rsplit(".", 1)[-1].strip())  # drop namespace qualification
    return names


def _declared_bases(text):
    """Yield (type_name, [base names]) for every class/struct/record header in `text`
    that has a base list. Walks the header (generics, primary constructor, base list up
    to `{`/`;`/`where`) instead of one regex, so multi-line base lists, primary
    constructors and constraint clauses all resolve."""
    for m in _TYPE_KEYWORD_RE.finditer(text):
        name = m.group(0).split()[-1]
        i = _skip_ws(text, m.end())
        i = _skip_ws(text, _skip_group(text, i, "<", ">"))
        i = _skip_ws(text, _skip_group(text, i, "(", ")"))
        if i >= len(text) or text[i] != ":":
            continue
        end = i + 1
        depth = 0
        while end < len(text):
            ch = text[end]
            if ch == "<":
                depth += 1
            elif ch == ">":
                depth -= 1
            elif depth == 0 and ch in "{;":
                break
            end += 1
        base_list = re.split(r"\bwhere\b", text[i + 1 : end])[0]
        yield name, _split_bases(base_list)


def _cs_files(root):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in _SKIPPED_DIRS]
        for fn in sorted(filenames):
            if fn.endswith(".cs"):
                yield os.path.join(dirpath, fn)


def _read_cs(path):
    with open(path, encoding="utf-8") as fh:
        return _strip_line_comments(fh.read())


def _scan_test_tree(app_dir, tests_dir):
    """-> (declared_interfaces, inherited_fake_bases, violations). A violation is
    (file relative to tests_dir, type name, interface) for an interface that is neither
    declared in `app_dir`'s hand-written C# nor in `_EXTERNAL_INTERFACES`."""
    declared = set()
    for path in _cs_files(app_dir):
        declared.update(_INTERFACE_DECL_RE.findall(_read_cs(path)))
    allowed = declared | _EXTERNAL_INTERFACES

    fake_bases, violations = set(), []
    for path in _cs_files(tests_dir):
        for type_name, bases in _declared_bases(_read_cs(path)):
            for base in bases:
                if base.endswith("FakeBase"):
                    fake_bases.add(base)
                elif _INTERFACE_NAME_RE.match(base) and base not in allowed:
                    violations.append((os.path.relpath(path, tests_dir), type_name, base))
    return declared, fake_bases, violations


def _synthetic_tree(tmp_path, files):
    app = tmp_path / "FaunaApp"
    for rel, text in files.items():
        p = app / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
    return str(app), str(app / "FaunaApp.Tests")


def _violating(tmp_path, files):
    _, _, violations = _scan_test_tree(*_synthetic_tree(tmp_path, files))
    return sorted((t, i) for _, t, i in violations)


_SEAM_CS = "namespace FaunaApp.Core;\npublic interface IStringLocalizer { string Get(string k); }\n"


def test_scan_flags_a_fake_that_implements_an_undeclared_interface_directly(tmp_path):
    """The exact shape of the eleven violations: `class FakeX : IXMachine` where IXMachine
    is declared nowhere in tracked C# (so it can only be a generated UniFFI interface)."""
    got = _violating(
        tmp_path,
        {
            "FaunaApp.Core/IStringLocalizer.cs": _SEAM_CS,
            "FaunaApp.Tests/A.cs": "internal sealed class FakeThing : IThingMachine\n{\n}\n",
        },
    )
    assert got == [("FakeThing", "IThingMachine")]


def test_scan_passes_fakebase_inheritors_project_seams_and_bcl_interfaces(tmp_path):
    files = {
        "FaunaApp.Core/IStringLocalizer.cs": _SEAM_CS,
        "FaunaApp.Tests/A.cs": (
            "internal sealed class FakeThing : ThingMachineFakeBase { }\n"  # the sanctioned form
            "internal sealed class FakeQualified : uniffi.fauna_ffi.FfiThingFakeBase { }\n"
            "class L : IStringLocalizer { }\n"  # project seam, declared in Core
            "class D : IDisposable { }\n"  # BCL
            "sealed class R(int x) : IDisposable { }\n"  # primary constructor
            "class Both : ThingMachineFakeBase, IDisposable { }\n"  # base + BCL
        ),
    }
    assert _violating(tmp_path, files) == []


def test_scan_resolves_multiline_generic_qualified_and_constrained_headers(tmp_path):
    got = _violating(
        tmp_path,
        {
            "FaunaApp.Tests/A.cs": (
                "class Multi\n"
                "    : IOtherMachine,\n"
                "      IDisposable\n"
                "{\n}\n"
                "class Gen<T> : IGenericMachine<T> where T : class\n{\n}\n"
                "class Qual : uniffi.fauna_ffi.IQualifiedMachine\n{\n}\n"
                "sealed class Prim(int x) : IPrimaryMachine\n{\n}\n"
            ),
        },
    )
    assert got == [
        ("Gen", "IGenericMachine"),
        ("Multi", "IOtherMachine"),
        ("Prim", "IPrimaryMachine"),
        ("Qual", "IQualifiedMachine"),
    ]


def test_scan_ignores_commented_out_code_and_the_generated_dir(tmp_path):
    files = {
        "FaunaApp.Tests/A.cs": "// class Ghost : IGhostMachine\n/// class Doc : IDocMachine\n",
        # FakeBases.g.cs's own bases implement the interface directly, by design.
        "FaunaApp.Tests/Generated/FakeBases.g.cs": "abstract class XFakeBase : IXMachine { }\n",
        "FaunaApp.Core/Generated/uniffi/x.cs": "public interface IXMachine { }\nclass Impl : IXMachine { }\n",
    }
    assert _violating(tmp_path, files) == []


def test_no_test_fake_implements_a_generated_interface_directly():
    declared, fake_bases, violations = _scan_test_tree(_APP_DIR, _TESTS_DIR)

    # Non-vacuity: a moved directory or a broken walk must not turn this into a pass.
    assert "IStringLocalizer" in declared, "scan did not read the hand-written C# under FaunaApp/"
    assert fake_bases, "scan found no `*FakeBase` inheritor — the test tree was not read"

    assert not violations, (
        "test fakes must inherit the generated `<X>FakeBase`, never implement a UniFFI "
        "interface directly — a new interface member must compile clean, not CS0535 "
        "(docs/goal/architecture/apps/windows.md § Workspace Layout). Change the base "
        "and `override` only the members the test exercises:\n"
        + "\n".join(
            f"  {path}: {type_name} : {iface}  ->  {iface[1:]}FakeBase"
            for path, type_name, iface in violations
        )
        + "\nIf the interface is genuinely not UniFFI-generated (a BCL / NuGet interface), "
        "name it in `_EXTERNAL_INTERFACES` in this file, with the reason."
    )
