"""tier_3: the AUTO-REPLY round-trip — the in-CI proxy for the external
send-and-reply human proof.

This is the closest in-CI mirror of the milestone's human-acceptance scenario
("send FROM the Fauna app to a real external mailbox; the external party
replies; the reply lands back in Fauna conversations"). It differs from
`test_mail_client_full_roundtrip.py` in ONE load-bearing way: the inbound reply
is NOT hand-crafted by the test — it is generated by the stub external MX as an
AUTO-REPLY to the message the bridge relayed out, addressed back to the exact
`From:` the Fauna app stamped on its outbound. That closes the loop the way a
real correspondent's "Reply" does, and PROVES the address the client sends from
is a real, routable mailbox (replyability) — a property the hand-crafted-reply
test cannot catch because it hardcodes `To: <handle>`.

Flow:
  1–5. Claim (whose derived mail enable auto-approves the box's bridge) →
       provision → bridge serving → add a credential → conversations, via the
       shared `helpers.mail_client_ui.claim_enable_and_ready` (handle
       `alice@fauna.test`, which once mail is enabled IS the routable address).
  6.   Arm the stub MX's `on_message` auto-reply: on receiving the relayed-out
       message it parses the `From:` and delivers a reply back inbound to that
       address over the MTA's port 25.
  7.   Compose + send to an external recipient through the conversations UI.
  8.   Assert the auto-reply was addressed to the sender's own handle
       (replyability) AND surfaces decrypted in the conversations list.

Single combo (oauthbearer — the production default); the full credential-kind
matrix is already covered by the full-roundtrip test, so this one adds only
the auto-reply / replyability dimension. (No-modes retirement, ratified
2026-07-12: there is no longer a storage-mode axis to combine with — every
nest is sealed at rest unconditionally.)

Test taxonomy: tier_3 (every binary real; real SMTP wire out to the stub MX, the
stub's real SMTP wire back in to the MTA, real seal → client fetch → open →
render). Promote to tier_4 only if a packaging/supervision seam is implicated —
the binary nest reproduces the whole reply loop here.
"""

import threading
import time

import pytest

from helpers.app_surface import skip_unbuilt
from helpers.mail_client_ui import claim_enable_and_ready, deliver_inbound
from helpers.mail_wire import build_reply_message

pytestmark = pytest.mark.tier_3

# The external recipient/correspondent domain — routed to the stub MX by the
# bridge's mta_mx_override; the stub's auto-reply comes back as genuine external
# inbound (no loopback/local-domain exemption on the sender domain).
EXTERNAL_DOMAIN = "external.test"


@pytest.mark.feature("email-in-conversations")
def test_client_send_then_stub_autoreply_renders_decrypted(app, unclaimed_mail_nest_ui):
    if not (app.driver.is_linux() or app.driver.is_macos() or app.driver.is_ios()):
        skip_unbuilt(
            app.driver,
            surface="the client-UI mail reply round-trip",
            detail="wired on linux first; web/windows/android/tui are "
            "the cross-app follow-on",
            tracked="mail-settings.md",
        )

    nest = unclaimed_mail_nest_ui

    # ── 1–5. Claim → provision → bridge serving → add credential → conversations.
    ctx = claim_enable_and_ready(app, nest, credential_kind="oauthbearer")
    domain = ctx["domain"]
    handle = ctx["handle"]                          # alice@fauna.test

    out_nonce = f"replyout{int(time.time() * 1000)}qx"
    reply_nonce = f"replyin{int(time.time() * 1000)}qx"
    recipient = f"bob@{EXTERNAL_DOMAIN}"
    subject = f"Auto-reply round-trip {out_nonce}"

    # ── 6. Arm the stub MX auto-reply. On receiving the relayed-out message the
    # stub parses its `From:` and delivers a reply BACK to that address over the
    # MTA's port-25 listener (loopback → exempt from the sender-domain check, like
    # any external peer reaching us). It fires exactly once (only our outbound
    # tagged `out_nonce` reaches the stub — the client-side Sent copy never does),
    # and records the parsed reply target / any fault for the assertions below.
    state = {"fired": False, "reply_to": None, "error": None}
    _once = threading.Lock()

    def _auto_reply(raw_outbound: bytes) -> None:
        if out_nonce.encode() not in raw_outbound:
            return  # not our message — ignore any unrelated traffic
        with _once:
            if state["fired"]:
                return
            state["fired"] = True
        try:
            reply_to, reply_raw = build_reply_message(
                raw_outbound, reply_nonce=reply_nonce, reply_from=f"bob@{EXTERNAL_DOMAIN}"
            )
            state["reply_to"] = reply_to
            deliver_inbound(
                nest.mx_port, domain, f"bob@{EXTERNAL_DOMAIN}", reply_to, reply_raw,
                time.monotonic() + 40.0,
            )
        except Exception as e:  # noqa: BLE001 - surfaced to the test via `state`
            state["error"] = repr(e)
            raise

    nest.stub_mx.on_message = _auto_reply

    # ── 7. Compose + send to the external recipient through the conversations UI.
    app.conversations.start_new_conversation(
        recipient, subject=subject, body=f"Outbound {out_nonce} from the Fauna app.\n"
    )

    # The outbound relayed to the stub (proves the send half) — gate on this so a
    # relay miss is reported distinctly from a reply miss.
    deadline = time.monotonic() + 90.0
    relayed = None
    while time.monotonic() < deadline and relayed is None:
        for raw in nest.stub_mx.messages():
            if out_nonce.encode() in raw:
                relayed = raw
                break
        if relayed is None:
            time.sleep(0.5)
    threads = [(t.label, t.snippet, t.rail) for t in app.conversations.list_threads()]
    assert relayed is not None, (
        f"the stub external MX never received the client-sent message {out_nonce!r}. "
        f"threads={threads}; conversations error: {app.error_text()!r}; "
        f"{nest.bridge_log_hint()}"
    )
    from helpers.mail_wire import header_value
    relayed_from = header_value(relayed, "From")

    # ── 8a. Replyability: the auto-reply targeted the sender's OWN handle — i.e.
    # the `From:` the client stamped is the routable mail address `alice@fauna.test`.
    deadline = time.monotonic() + 15.0
    while time.monotonic() < deadline and state["reply_to"] is None and state["error"] is None:
        time.sleep(0.25)
    assert state["error"] is None, (
        f"the stub auto-reply delivery failed: {state['error']}\n"
        f"  relayed-out From: {relayed_from!r}; parsed reply target: {state['reply_to']!r}; "
        f"expected sender handle: {handle!r}"
    )
    assert state["reply_to"] == handle, (
        f"the relayed-out message's From: must be the sender's routable mail "
        f"address {handle!r} so a reply routes back; the stub replied to "
        f"{state['reply_to']!r} (relayed From: {relayed_from!r}) instead (a "
        f"non-replyable From would silently lose every reply on the live box)"
    )

    # ── 8b. The auto-reply surfaces DECRYPTED in the conversations list (via the
    # fauna.mail.received arrival push or the periodic poll backstop).
    deadline = time.monotonic() + 60.0
    found = None
    while time.monotonic() < deadline and found is None:
        for t in app.conversations.list_threads():
            if reply_nonce in (t.label or "") or reply_nonce in (t.snippet or ""):
                found = t
                break
        if found is None:
            time.sleep(1.0)
    assert found is not None, (
        f"the external auto-reply {reply_nonce!r} never surfaced decrypted in the "
        f"conversations list — the client receive path (inbox.fetch → "
        f"open_inbound_record → parse → render) did not complete.\n"
        f"  threads: {[(t.label, t.snippet, t.rail) for t in app.conversations.list_threads()]}\n"
        f"  conversations error: {app.error_text()!r}; {nest.bridge_log_hint()}"
    )
    assert found.rail == "Smtp", f"received mail must land on the Smtp rail; got {found.rail!r}"
