//! Shared orchestration for the flat **`admin-contacts`** page — the admin-tier
//! deployment-wide **CardDAV-enable** toggle (`admin.md` § Contacts).
//!
//! Authority for the enablement model: [`carddav-server.md`](../../../docs/goal/behavior/carddav-server.md)
//! § Independent enablement (email, calendar, and contacts are three
//! independently enableable features of one MDA bridge). Authority for UX/IDs:
//! `docs/goal/behavior/admin.md` § Contacts + `tests/e2e-unified/ui.yaml`
//! `admin-contacts`.
//!
//! This is the **Admin-class** contacts twin of [`super::caldav_policy`] and
//! [`super::webdav_policy`] — the same focused-machine shape over the same
//! admin read twin, minus the port knob: CardDAV rides the **shared DAV
//! listener** (`carddav-server.md` § Process topology — path-muxed beside
//! CalDAV on one `:443`/`caldav_port` listener), so there is no `carddav_port`
//! to expose; `admin-calendar-caldav-port-input` already governs the
//! router-less direct listener both protocols share. Generated by
//! [`crate::bool_toggle_policy::bool_toggle_policy_machine`] — this file was
//! byte-for-byte identical to `webdav_policy.rs` modulo naming before round 68
//! of the shared-Rust lift sweep lifted the shape out.
//!
//! **Read + write are both live.** The toggle *hydrates* `carddav_enabled` from
//! the admin read twin `fauna.bridges.get_mail_config`
//! (`FetchConfigReply.carddav_enabled`, which the nest reports as `mail_enabled`
//! while the CardDAV toggle is unset — the same legacy fallback CalDAV uses;
//! `Refresh`), and *saves* via the Admin-class write kind
//! `fauna.bridges.set_carddav_enabled`. The MDA bridge runs iff
//! `mail_enabled || caldav_enabled || carddav_enabled`
//! (`bins/fauna-nest/src/mail_enable.rs`), so flipping this toggle (or the
//! `admin-mail` / `admin-calendar` siblings) is what brings the one MDA bridge
//! up/down — "enabled if any".
//!
//! A focused machine (not folded into `MailPolicyMachine` or
//! `CaldavPolicyMachine`) so the `admin-contacts` page stays a dumb renderer of a
//! small snapshot, mirroring the other focused machines. The other 5 clients lift
//! it over the UniFFI/wasm `build_carddav_policy_machine` export.

use crate::bool_toggle_policy::bool_toggle_policy_machine;

bool_toggle_policy_machine! {
    protocol: "CardDAV",
    status: CarddavPolicyStatus,
    snapshot: CarddavPolicySnapshot,
    action: CarddavPolicyAction,
    nest: CarddavPolicyNest,
    machine: CarddavPolicyMachine,
    field: carddav_enabled,
    set_variant: SetCarddavEnabled,
    set_method: set_carddav_enabled,
}
