//! Shared orchestration for the flat **`admin-files`** page — the admin-tier
//! deployment-wide **WebDAV-enable** toggle (`admin.md` § Files).
//!
//! Authority for the enablement model: [`webdav-server.md`](../../../docs/goal/behavior/webdav-server.md)
//! § Independent enablement (email, calendar, contacts, and files/WebDAV are
//! independently enableable features of one MDA bridge). Authority for UX/IDs:
//! `docs/goal/behavior/admin.md` § Files + `tests/e2e-unified/ui.yaml`
//! `admin-files`.
//!
//! This is the **Admin-class** files twin of [`super::caldav_policy`] and
//! [`super::carddav_policy`] — the same focused-machine shape over the same
//! admin read twin, minus the port knob: WebDAV rides the **shared DAV
//! listener** (`webdav-server.md` § Process topology — path-muxed beside
//! CalDAV/CardDAV on one `:443`/`caldav_port` listener), so there is no
//! `webdav_port` to expose; `admin-calendar-caldav-port-input` already governs
//! the router-less direct listener all three protocols share. Generated by
//! [`crate::bool_toggle_policy::bool_toggle_policy_machine`] — this file was
//! byte-for-byte identical to `carddav_policy.rs` modulo naming before round 68
//! of the shared-Rust lift sweep lifted the shape out.
//!
//! **Read + write are both live.** The toggle *hydrates* `webdav_enabled` from
//! the admin read twin `fauna.bridges.get_mail_config`
//! (`FetchConfigReply.webdav_enabled`, which the nest reports as `mail_enabled`
//! while the WebDAV toggle is unset — the same out-of-the-box fallback CalDAV uses;
//! `Refresh`), and *saves* via the Admin-class write kind
//! `fauna.bridges.set_webdav_enabled`. The MDA bridge runs iff
//! `mail_enabled || caldav_enabled || carddav_enabled || webdav_enabled`
//! (`bins/fauna-nest/src/mail_enable.rs`), so flipping this toggle (or the
//! `admin-mail` / `admin-calendar` / `admin-contacts` siblings) is what brings
//! the one MDA bridge up/down — "enabled if any".
//!
//! A focused machine (not folded into `MailPolicyMachine` or
//! `CarddavPolicyMachine`) so the `admin-files` page stays a dumb renderer of a
//! small snapshot, mirroring the other focused machines. The other 5 clients lift
//! it over the UniFFI/wasm `build_webdav_policy_machine` export.

use crate::bool_toggle_policy::bool_toggle_policy_machine;

bool_toggle_policy_machine! {
    protocol: "WebDAV",
    status: WebdavPolicyStatus,
    snapshot: WebdavPolicySnapshot,
    action: WebdavPolicyAction,
    nest: WebdavPolicyNest,
    machine: WebdavPolicyMachine,
    field: webdav_enabled,
    set_variant: SetWebdavEnabled,
    set_method: set_webdav_enabled,
}
