

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureDroppedCallback(
				UniffiForeignFutureDroppedCallback cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static uint64_t call_UniffiCallbackInterfaceClone(
				UniffiCallbackInterfaceClone cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureResultU8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureResultU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureResultI8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureResultI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureResultU16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureResultU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureResultI16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureResultI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureResultU32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureResultU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureResultI32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureResultI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureResultU64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureResultU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureResultI64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureResultI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureResultF32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureResultF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureResultF64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureResultF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureResultRustBuffer result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureResultRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureResultVoid result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureResultVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_VERIFY_INBOUND
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_VERIFY_INBOUND
uint64_t uniffi_fauna_mail_fn_func_verify_inbound(RustBuffer raw, RustBuffer mail_from, RustBuffer client_ip, RustBuffer client_helo
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_JOIN_SEALED_MAIL_BODY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_JOIN_SEALED_MAIL_BODY
RustBuffer uniffi_fauna_mail_fn_func_join_sealed_mail_body(RustBuffer chunks, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_MAIL_BODY_NEEDS_REFERENCE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_MAIL_BODY_NEEDS_REFERENCE
int8_t uniffi_fauna_mail_fn_func_mail_body_needs_reference(uint64_t sealed_body_len, uint64_t sealed_hint_len, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_SPLIT_SEALED_MAIL_BODY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_SPLIT_SEALED_MAIL_BODY
RustBuffer uniffi_fauna_mail_fn_func_split_sealed_mail_body(RustBuffer body, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_FETCH_BINARY_SECTION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_FETCH_BINARY_SECTION
RustBuffer uniffi_fauna_mail_fn_func_fetch_binary_section(RustBuffer raw, RustBuffer spec, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_FETCH_BINARY_SIZE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_FETCH_BINARY_SIZE
uint32_t uniffi_fauna_mail_fn_func_fetch_binary_size(RustBuffer raw, RustBuffer part, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_FETCH_BODY_SECTION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_FETCH_BODY_SECTION
RustBuffer uniffi_fauna_mail_fn_func_fetch_body_section(RustBuffer raw, RustBuffer spec, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_DERIVE_BODY_STRUCTURE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_DERIVE_BODY_STRUCTURE
RustBuffer uniffi_fauna_mail_fn_func_derive_body_structure(RustBuffer raw, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_MAIL_DEDUP_KEYS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_MAIL_DEDUP_KEYS
RustBuffer uniffi_fauna_mail_fn_func_mail_dedup_keys(RustBuffer raw_message, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_DERIVE_ENVELOPE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_DERIVE_ENVELOPE
RustBuffer uniffi_fauna_mail_fn_func_derive_envelope(RustBuffer raw, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_FROM_MAILBOXES
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_FROM_MAILBOXES
RustBuffer uniffi_fauna_mail_fn_func_from_mailboxes(RustBuffer raw, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_SENDER_DOMAIN_WITH_ENVELOPE_FALLBACK
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_SENDER_DOMAIN_WITH_ENVELOPE_FALLBACK
RustBuffer uniffi_fauna_mail_fn_func_sender_domain_with_envelope_fallback(RustBuffer raw, RustBuffer mail_from, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_AUTO_REPLY_DECISION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_AUTO_REPLY_DECISION
RustBuffer uniffi_fauna_mail_fn_func_auto_reply_decision(RustBuffer envelope_from, RustBuffer headers, RustBuffer recipient_addr, RustBuffer local_domains, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_EVALUATE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_EVALUATE
RustBuffer uniffi_fauna_mail_fn_func_evaluate(RustBuffer filters, RustBuffer ctx, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_FROM_FIELD_COUNT
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_FROM_FIELD_COUNT
uint32_t uniffi_fauna_mail_fn_func_from_field_count(RustBuffer raw, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_BUILD_ATTENDEE_REPLY_FROM_ICS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_BUILD_ATTENDEE_REPLY_FROM_ICS
RustBuffer uniffi_fauna_mail_fn_func_build_attendee_reply_from_ics(RustBuffer new_ics, RustBuffer prior_ics, RustBuffer attendee_email, RustBuffer dtstamp, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_BUILD_EVENT_IMIP_FROM_ICS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_BUILD_EVENT_IMIP_FROM_ICS
RustBuffer uniffi_fauna_mail_fn_func_build_event_imip_from_ics(RustBuffer method, RustBuffer raw_ics, RustBuffer dtstamp, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_EXPAND_RECURRENCE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_EXPAND_RECURRENCE
RustBuffer uniffi_fauna_mail_fn_func_expand_recurrence(RustBuffer component, int64_t window_start, int64_t window_end, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_GENERATE_ICAL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_GENERATE_ICAL
RustBuffer uniffi_fauna_mail_fn_func_generate_ical(RustBuffer event, RustBuffer attendees, RustBuffer organizer_email, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_GENERATE_ITIP
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_GENERATE_ITIP
RustBuffer uniffi_fauna_mail_fn_func_generate_itip(RustBuffer method, RustBuffer event, RustBuffer attendees, RustBuffer organizer_email, RustBuffer dtstamp, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_INVITE_FROM_MAIL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_INVITE_FROM_MAIL
RustBuffer uniffi_fauna_mail_fn_func_invite_from_mail(RustBuffer raw_rfc5322, int64_t timestamp, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_PARSE_ICAL_ORGANIZER_FROM_ICS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_PARSE_ICAL_ORGANIZER_FROM_ICS
RustBuffer uniffi_fauna_mail_fn_func_parse_ical_organizer_from_ics(RustBuffer raw_ics, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_PARSE_ICALENDAR
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_PARSE_ICALENDAR
RustBuffer uniffi_fauna_mail_fn_func_parse_icalendar(RustBuffer bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_LOOKUP_KIND
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_LOOKUP_KIND
RustBuffer uniffi_fauna_mail_fn_func_lookup_kind(RustBuffer kind, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_NEW_FAUNA_MSGID_LOCAL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_NEW_FAUNA_MSGID_LOCAL
RustBuffer uniffi_fauna_mail_fn_func_new_fauna_msgid_local(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_COMPOSE_AUTO_REPLY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_COMPOSE_AUTO_REPLY
RustBuffer uniffi_fauna_mail_fn_func_compose_auto_reply(RustBuffer msg, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_PARSE_RFC5322
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_PARSE_RFC5322
RustBuffer uniffi_fauna_mail_fn_func_parse_rfc5322(RustBuffer raw, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_BUILD_RECEIVED_HEADER
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_BUILD_RECEIVED_HEADER
RustBuffer uniffi_fauna_mail_fn_func_build_received_header(int64_t now_unix_secs, RustBuffer opts, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_REPORT_HASH
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_REPORT_HASH
RustBuffer uniffi_fauna_mail_fn_func_report_hash(RustBuffer subject, RustBuffer body_text, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_CLAMD_PARSE_REPLY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_CLAMD_PARSE_REPLY
RustBuffer uniffi_fauna_mail_fn_func_clamd_parse_reply(RustBuffer reply, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_DECIDE_SCAN_ACTION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_DECIDE_SCAN_ACTION
RustBuffer uniffi_fauna_mail_fn_func_decide_scan_action(RustBuffer clamav, RustBuffer policy, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_RSPAMD_PARSE_REPLY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_RSPAMD_PARSE_REPLY
RustBuffer uniffi_fauna_mail_fn_func_rspamd_parse_reply(RustBuffer json, uint16_t scaling_per_mille, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_BUILD_SCHEDULING_DELIVERY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_BUILD_SCHEDULING_DELIVERY
RustBuffer uniffi_fauna_mail_fn_func_build_scheduling_delivery(RustBuffer recipient_kp, RustBuffer sender_actor_id, RustBuffer imip_rfc5322, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_BUILD_AUTHENTICATED_SENDER_STAMP
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_BUILD_AUTHENTICATED_SENDER_STAMP
RustBuffer uniffi_fauna_mail_fn_func_build_authenticated_sender_stamp(RustBuffer addr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_APPLY_UNLISTED_RECIPIENT_PENALTY_MILLI
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_APPLY_UNLISTED_RECIPIENT_PENALTY_MILLI
int32_t uniffi_fauna_mail_fn_func_apply_unlisted_recipient_penalty_milli(int32_t combined_milli, uint32_t penalty_points, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_COMBINED_SPAM_SCORE_MILLI
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_COMBINED_SPAM_SCORE_MILLI
int32_t uniffi_fauna_mail_fn_func_combined_spam_score_milli(int32_t rspamd_scaled_milli, int32_t weighted_bayesian_milli, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_DECIDE_SPAM_DISPOSITION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_DECIDE_SPAM_DISPOSITION
RustBuffer uniffi_fauna_mail_fn_func_decide_spam_disposition(int32_t combined_score_milli, RustBuffer verdicts, RustBuffer policy, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_APPLY_SPAM_TRAINING
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_APPLY_SPAM_TRAINING
RustBuffer uniffi_fauna_mail_fn_func_apply_spam_training(RustBuffer model_bytes, RustBuffer text, int8_t is_spam, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_DEFAULT_BAYESIAN_KNOBS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_DEFAULT_BAYESIAN_KNOBS
RustBuffer uniffi_fauna_mail_fn_func_default_bayesian_knobs(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_FOLD_SPAM_MODEL_BASELINE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_FOLD_SPAM_MODEL_BASELINE
RustBuffer uniffi_fauna_mail_fn_func_fold_spam_model_baseline(RustBuffer model_bytes, RustBuffer baseline_bytes, uint32_t full_confidence_samples, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_WEIGHTED_BAYESIAN_MILLI_FOR_MODEL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_WEIGHTED_BAYESIAN_MILLI_FOR_MODEL
int32_t uniffi_fauna_mail_fn_func_weighted_bayesian_milli_for_model(RustBuffer model_bytes, RustBuffer text, RustBuffer knobs, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_OPEN_STAGED_BODY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_OPEN_STAGED_BODY
RustBuffer uniffi_fauna_mail_fn_func_open_staged_body(RustBuffer sealed, RustBuffer key, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_SEAL_STAGED_BODY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_SEAL_STAGED_BODY
RustBuffer uniffi_fauna_mail_fn_func_seal_staged_body(RustBuffer plain, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_TOKENIZE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_TOKENIZE
RustBuffer uniffi_fauna_mail_fn_func_tokenize(RustBuffer input, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_EFFECTIVE_MAX_RAW_MESSAGE_BYTES
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_EFFECTIVE_MAX_RAW_MESSAGE_BYTES
uint32_t uniffi_fauna_mail_fn_func_effective_max_raw_message_bytes(uint32_t max_message_bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_INLINE_MAIL_REQUEST_BUDGET_BYTES
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_INLINE_MAIL_REQUEST_BUDGET_BYTES
uint32_t uniffi_fauna_mail_fn_func_inline_mail_request_budget_bytes(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_MAX_INLINE_RAW_MESSAGE_BYTES
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_MAX_INLINE_RAW_MESSAGE_BYTES
uint32_t uniffi_fauna_mail_fn_func_max_inline_raw_message_bytes(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_MAX_MESSAGE_BYTES_CEILING
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_FN_FUNC_MAX_MESSAGE_BYTES_CEILING
uint32_t uniffi_fauna_mail_fn_func_max_message_bytes_ceiling(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUSTBUFFER_ALLOC
RustBuffer ffi_fauna_mail_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_fauna_mail_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUSTBUFFER_FREE
void ffi_fauna_mail_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUSTBUFFER_RESERVE
RustBuffer ffi_fauna_mail_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_U8
void ffi_fauna_mail_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_U8
void ffi_fauna_mail_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_U8
void ffi_fauna_mail_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_fauna_mail_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_I8
void ffi_fauna_mail_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_I8
void ffi_fauna_mail_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_I8
void ffi_fauna_mail_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_I8
int8_t ffi_fauna_mail_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_U16
void ffi_fauna_mail_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_U16
void ffi_fauna_mail_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_U16
void ffi_fauna_mail_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_fauna_mail_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_I16
void ffi_fauna_mail_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_I16
void ffi_fauna_mail_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_I16
void ffi_fauna_mail_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_I16
int16_t ffi_fauna_mail_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_U32
void ffi_fauna_mail_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_U32
void ffi_fauna_mail_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_U32
void ffi_fauna_mail_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_fauna_mail_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_I32
void ffi_fauna_mail_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_I32
void ffi_fauna_mail_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_I32
void ffi_fauna_mail_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_I32
int32_t ffi_fauna_mail_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_U64
void ffi_fauna_mail_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_U64
void ffi_fauna_mail_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_U64
void ffi_fauna_mail_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_fauna_mail_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_I64
void ffi_fauna_mail_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_I64
void ffi_fauna_mail_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_I64
void ffi_fauna_mail_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_I64
int64_t ffi_fauna_mail_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_F32
void ffi_fauna_mail_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_F32
void ffi_fauna_mail_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_F32
void ffi_fauna_mail_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_F32
float ffi_fauna_mail_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_F64
void ffi_fauna_mail_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_F64
void ffi_fauna_mail_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_F64
void ffi_fauna_mail_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_F64
double ffi_fauna_mail_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_fauna_mail_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_fauna_mail_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_fauna_mail_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_fauna_mail_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_POLL_VOID
void ffi_fauna_mail_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_CANCEL_VOID
void ffi_fauna_mail_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_FREE_VOID
void ffi_fauna_mail_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_RUST_FUTURE_COMPLETE_VOID
void ffi_fauna_mail_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_VERIFY_INBOUND
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_VERIFY_INBOUND
uint16_t uniffi_fauna_mail_checksum_func_verify_inbound(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_JOIN_SEALED_MAIL_BODY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_JOIN_SEALED_MAIL_BODY
uint16_t uniffi_fauna_mail_checksum_func_join_sealed_mail_body(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_MAIL_BODY_NEEDS_REFERENCE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_MAIL_BODY_NEEDS_REFERENCE
uint16_t uniffi_fauna_mail_checksum_func_mail_body_needs_reference(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_SPLIT_SEALED_MAIL_BODY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_SPLIT_SEALED_MAIL_BODY
uint16_t uniffi_fauna_mail_checksum_func_split_sealed_mail_body(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_FETCH_BINARY_SECTION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_FETCH_BINARY_SECTION
uint16_t uniffi_fauna_mail_checksum_func_fetch_binary_section(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_FETCH_BINARY_SIZE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_FETCH_BINARY_SIZE
uint16_t uniffi_fauna_mail_checksum_func_fetch_binary_size(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_FETCH_BODY_SECTION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_FETCH_BODY_SECTION
uint16_t uniffi_fauna_mail_checksum_func_fetch_body_section(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_DERIVE_BODY_STRUCTURE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_DERIVE_BODY_STRUCTURE
uint16_t uniffi_fauna_mail_checksum_func_derive_body_structure(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_MAIL_DEDUP_KEYS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_MAIL_DEDUP_KEYS
uint16_t uniffi_fauna_mail_checksum_func_mail_dedup_keys(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_DERIVE_ENVELOPE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_DERIVE_ENVELOPE
uint16_t uniffi_fauna_mail_checksum_func_derive_envelope(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_FROM_MAILBOXES
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_FROM_MAILBOXES
uint16_t uniffi_fauna_mail_checksum_func_from_mailboxes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_SENDER_DOMAIN_WITH_ENVELOPE_FALLBACK
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_SENDER_DOMAIN_WITH_ENVELOPE_FALLBACK
uint16_t uniffi_fauna_mail_checksum_func_sender_domain_with_envelope_fallback(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_AUTO_REPLY_DECISION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_AUTO_REPLY_DECISION
uint16_t uniffi_fauna_mail_checksum_func_auto_reply_decision(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_EVALUATE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_EVALUATE
uint16_t uniffi_fauna_mail_checksum_func_evaluate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_FROM_FIELD_COUNT
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_FROM_FIELD_COUNT
uint16_t uniffi_fauna_mail_checksum_func_from_field_count(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_BUILD_ATTENDEE_REPLY_FROM_ICS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_BUILD_ATTENDEE_REPLY_FROM_ICS
uint16_t uniffi_fauna_mail_checksum_func_build_attendee_reply_from_ics(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_BUILD_EVENT_IMIP_FROM_ICS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_BUILD_EVENT_IMIP_FROM_ICS
uint16_t uniffi_fauna_mail_checksum_func_build_event_imip_from_ics(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_EXPAND_RECURRENCE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_EXPAND_RECURRENCE
uint16_t uniffi_fauna_mail_checksum_func_expand_recurrence(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_GENERATE_ICAL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_GENERATE_ICAL
uint16_t uniffi_fauna_mail_checksum_func_generate_ical(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_GENERATE_ITIP
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_GENERATE_ITIP
uint16_t uniffi_fauna_mail_checksum_func_generate_itip(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_INVITE_FROM_MAIL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_INVITE_FROM_MAIL
uint16_t uniffi_fauna_mail_checksum_func_invite_from_mail(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_PARSE_ICAL_ORGANIZER_FROM_ICS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_PARSE_ICAL_ORGANIZER_FROM_ICS
uint16_t uniffi_fauna_mail_checksum_func_parse_ical_organizer_from_ics(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_PARSE_ICALENDAR
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_PARSE_ICALENDAR
uint16_t uniffi_fauna_mail_checksum_func_parse_icalendar(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_LOOKUP_KIND
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_LOOKUP_KIND
uint16_t uniffi_fauna_mail_checksum_func_lookup_kind(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_NEW_FAUNA_MSGID_LOCAL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_NEW_FAUNA_MSGID_LOCAL
uint16_t uniffi_fauna_mail_checksum_func_new_fauna_msgid_local(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_COMPOSE_AUTO_REPLY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_COMPOSE_AUTO_REPLY
uint16_t uniffi_fauna_mail_checksum_func_compose_auto_reply(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_PARSE_RFC5322
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_PARSE_RFC5322
uint16_t uniffi_fauna_mail_checksum_func_parse_rfc5322(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_BUILD_RECEIVED_HEADER
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_BUILD_RECEIVED_HEADER
uint16_t uniffi_fauna_mail_checksum_func_build_received_header(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_REPORT_HASH
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_REPORT_HASH
uint16_t uniffi_fauna_mail_checksum_func_report_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_CLAMD_PARSE_REPLY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_CLAMD_PARSE_REPLY
uint16_t uniffi_fauna_mail_checksum_func_clamd_parse_reply(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_DECIDE_SCAN_ACTION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_DECIDE_SCAN_ACTION
uint16_t uniffi_fauna_mail_checksum_func_decide_scan_action(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_RSPAMD_PARSE_REPLY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_RSPAMD_PARSE_REPLY
uint16_t uniffi_fauna_mail_checksum_func_rspamd_parse_reply(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_BUILD_SCHEDULING_DELIVERY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_BUILD_SCHEDULING_DELIVERY
uint16_t uniffi_fauna_mail_checksum_func_build_scheduling_delivery(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_BUILD_AUTHENTICATED_SENDER_STAMP
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_BUILD_AUTHENTICATED_SENDER_STAMP
uint16_t uniffi_fauna_mail_checksum_func_build_authenticated_sender_stamp(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_APPLY_UNLISTED_RECIPIENT_PENALTY_MILLI
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_APPLY_UNLISTED_RECIPIENT_PENALTY_MILLI
uint16_t uniffi_fauna_mail_checksum_func_apply_unlisted_recipient_penalty_milli(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_COMBINED_SPAM_SCORE_MILLI
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_COMBINED_SPAM_SCORE_MILLI
uint16_t uniffi_fauna_mail_checksum_func_combined_spam_score_milli(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_DECIDE_SPAM_DISPOSITION
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_DECIDE_SPAM_DISPOSITION
uint16_t uniffi_fauna_mail_checksum_func_decide_spam_disposition(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_APPLY_SPAM_TRAINING
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_APPLY_SPAM_TRAINING
uint16_t uniffi_fauna_mail_checksum_func_apply_spam_training(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_DEFAULT_BAYESIAN_KNOBS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_DEFAULT_BAYESIAN_KNOBS
uint16_t uniffi_fauna_mail_checksum_func_default_bayesian_knobs(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_FOLD_SPAM_MODEL_BASELINE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_FOLD_SPAM_MODEL_BASELINE
uint16_t uniffi_fauna_mail_checksum_func_fold_spam_model_baseline(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_WEIGHTED_BAYESIAN_MILLI_FOR_MODEL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_WEIGHTED_BAYESIAN_MILLI_FOR_MODEL
uint16_t uniffi_fauna_mail_checksum_func_weighted_bayesian_milli_for_model(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_OPEN_STAGED_BODY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_OPEN_STAGED_BODY
uint16_t uniffi_fauna_mail_checksum_func_open_staged_body(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_SEAL_STAGED_BODY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_SEAL_STAGED_BODY
uint16_t uniffi_fauna_mail_checksum_func_seal_staged_body(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_TOKENIZE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_TOKENIZE
uint16_t uniffi_fauna_mail_checksum_func_tokenize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_EFFECTIVE_MAX_RAW_MESSAGE_BYTES
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_EFFECTIVE_MAX_RAW_MESSAGE_BYTES
uint16_t uniffi_fauna_mail_checksum_func_effective_max_raw_message_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_INLINE_MAIL_REQUEST_BUDGET_BYTES
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_INLINE_MAIL_REQUEST_BUDGET_BYTES
uint16_t uniffi_fauna_mail_checksum_func_inline_mail_request_budget_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_MAX_INLINE_RAW_MESSAGE_BYTES
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_MAX_INLINE_RAW_MESSAGE_BYTES
uint16_t uniffi_fauna_mail_checksum_func_max_inline_raw_message_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_MAX_MESSAGE_BYTES_CEILING
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_MAIL_CHECKSUM_FUNC_MAX_MESSAGE_BYTES_CEILING
uint16_t uniffi_fauna_mail_checksum_func_max_message_bytes_ceiling(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_MAIL_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_FAUNA_MAIL_UNIFFI_CONTRACT_VERSION
uint32_t ffi_fauna_mail_uniffi_contract_version(void
    
);
#endif


void fauna_mail_uniffiFutureContinuationCallback(uint64_t, int8_t);
void fauna_mail_uniffiFreeGorutine(uint64_t);
