// Generated by scripts/providers-generate.py. DO NOT EDIT.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProviderId {
    Cloudflare,
    Porkbun,
    Hetzner,
    Namecheap,
    Gandi,
    Digitalocean,
    Vultr,
    Ovh,
    Linode,
    Bundled,
}

impl ProviderId {
    pub fn as_str(self) -> &'static str {
        match self {
            ProviderId::Cloudflare => "cloudflare",
            ProviderId::Porkbun => "porkbun",
            ProviderId::Hetzner => "hetzner",
            ProviderId::Namecheap => "namecheap",
            ProviderId::Gandi => "gandi",
            ProviderId::Digitalocean => "digitalocean",
            ProviderId::Vultr => "vultr",
            ProviderId::Ovh => "ovh",
            ProviderId::Linode => "linode",
            ProviderId::Bundled => "bundled",
        }
    }

    #[allow(clippy::should_implement_trait)] // returns Option, not Result
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "cloudflare" => Some(ProviderId::Cloudflare),
            "porkbun" => Some(ProviderId::Porkbun),
            "hetzner" => Some(ProviderId::Hetzner),
            "namecheap" => Some(ProviderId::Namecheap),
            "gandi" => Some(ProviderId::Gandi),
            "digitalocean" => Some(ProviderId::Digitalocean),
            "vultr" => Some(ProviderId::Vultr),
            "ovh" => Some(ProviderId::Ovh),
            "linode" => Some(ProviderId::Linode),
            "bundled" => Some(ProviderId::Bundled),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Capability { Dns, Vps, Registrar }

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CorsPolicy { Open, Proxy, Native }

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FieldType { Text, Secret, Select, HostedAuth }

pub struct FieldMeta {
    pub id: &'static str,
    pub field_type: FieldType,
    pub label_key: &'static str,
    pub required: bool,
    /// Credential flows this field applies to. The dns_config form
    /// renders fields where `kinds.contains(&Capability::Dns)`; when
    /// `same_provider_for_vps` is checked AND the provider has VPS
    /// capability, it also includes fields where `kinds.contains(&Capability::Vps)`.
    pub kinds: &'static [Capability],
}

pub struct PostVerifySelect {
    pub id: &'static str,
    pub label_key: &'static str,
    pub source: &'static str,
    pub required: bool,
}

static PVS_CLOUDFLARE: PostVerifySelect = PostVerifySelect {
    id: "zone-select",
    label_key: "provisioning.cloudflare.zone",
    source: "zones",
    required: true,
};

static PVS_PORKBUN: PostVerifySelect = PostVerifySelect {
    id: "domain-select",
    label_key: "provisioning.porkbun.domain",
    source: "zones",
    required: true,
};

static PVS_HETZNER: PostVerifySelect = PostVerifySelect {
    id: "location-select",
    label_key: "provisioning.hetzner.location",
    source: "regions",
    required: true,
};

static PVS_NAMECHEAP: PostVerifySelect = PostVerifySelect {
    id: "domain-select",
    label_key: "provisioning.namecheap.domain",
    source: "zones",
    required: true,
};

static PVS_GANDI: PostVerifySelect = PostVerifySelect {
    id: "domain-select",
    label_key: "provisioning.gandi.domain",
    source: "zones",
    required: true,
};

static PVS_DIGITALOCEAN: PostVerifySelect = PostVerifySelect {
    id: "location-select",
    label_key: "provisioning.digitalocean.location",
    source: "regions",
    required: true,
};

static PVS_VULTR: PostVerifySelect = PostVerifySelect {
    id: "location-select",
    label_key: "provisioning.vultr.location",
    source: "regions",
    required: true,
};

static PVS_OVH: PostVerifySelect = PostVerifySelect {
    id: "project-select",
    label_key: "provisioning.ovh.project",
    source: "projects",
    required: true,
};

static PVS_LINODE: PostVerifySelect = PostVerifySelect {
    id: "location-select",
    label_key: "provisioning.linode.location",
    source: "regions",
    required: true,
};

static PVS_BUNDLED: PostVerifySelect = PostVerifySelect {
    id: "location-select",
    label_key: "provisioning.bundled.location",
    source: "regions",
    required: true,
};

// Extended from the original narrow shape to include i18n keys and
// post-verify-select metadata needed by native Linux/macOS UI rendering.
// The TS/Swift/Kotlin/C# shapes already carry these fields; this Rust
// extension mirrors them additively without breaking other crates.
pub struct ProviderMeta {
    pub id: ProviderId,
    pub display_name_key: &'static str,
    pub help_key: &'static str,
    pub signup_url: &'static str,
    pub capabilities: &'static [Capability],
    pub cors_policy: CorsPolicy,
    pub fields: &'static [FieldMeta],
    pub post_verify_select: Option<&'static PostVerifySelect>,
    pub registrar_requires_contact: Option<bool>,
    pub registrar_notes_key: Option<&'static str>,
    pub curated_offers: &'static [&'static str],
    pub tld_pricing_endpoint: Option<&'static str>,
    /// Name of the `DnsDispatch` variant serving this provider, or
    /// `None` when it has no DNS capability. Pinned against the
    /// hand-written `dispatch.rs` by `tests/dispatch_registry_bijection.rs`.
    pub dns_dispatch: Option<&'static str>,
    /// Name of the `VpsDispatch` variant serving this provider, or
    /// `None` when it has no VPS capability.
    pub vps_dispatch: Option<&'static str>,
    /// Name of the `RegistrarDispatch` variant serving this provider,
    /// or `None` when it has no registrar capability.
    pub registrar_dispatch: Option<&'static str>,
}

impl ProviderMeta {
    /// The dispatch-enum variant name serving `cap` for this provider,
    /// or `None` when the provider does not declare that capability.
    ///
    /// This is the registry's half of the dispatch contract: the other
    /// half is `DnsDispatch::variant_name` and friends, and
    /// `tests/dispatch_registry_bijection.rs` asserts they agree for
    /// every provider x declared capability.
    pub fn dispatch_variant(&self, cap: Capability) -> Option<&'static str> {
        match cap {
            Capability::Dns => self.dns_dispatch,
            Capability::Vps => self.vps_dispatch,
            Capability::Registrar => self.registrar_dispatch,
        }
    }
}

pub static PROVIDERS: &[ProviderMeta] = &[
    ProviderMeta {
        id: ProviderId::Cloudflare,
        display_name_key: "provisioning.cloudflare.name",
        help_key: "provisioning.cloudflare.help",
        signup_url: "https://dash.cloudflare.com/sign-up",
        capabilities: &[Capability::Dns, Capability::Registrar],
        cors_policy: CorsPolicy::Proxy,
        fields: &[FieldMeta { id: "api-token", field_type: FieldType::Secret, label_key: "provisioning.cloudflare.api_token", required: true, kinds: &[Capability::Dns, Capability::Registrar] }, FieldMeta { id: "account-id", field_type: FieldType::Text, label_key: "provisioning.cloudflare.account_id", required: true, kinds: &[Capability::Registrar] }],
        post_verify_select: Some(&PVS_CLOUDFLARE),
        registrar_requires_contact: Some(false),
        registrar_notes_key: Some("provisioning.cloudflare.registrar_account_contact_note"),
        curated_offers: &[],
        tld_pricing_endpoint: None,
        dns_dispatch: Some("CloudflareDns"),
        vps_dispatch: None,
        registrar_dispatch: Some("CloudflareRegistrar"),
    },
    ProviderMeta {
        id: ProviderId::Porkbun,
        display_name_key: "provisioning.porkbun.name",
        help_key: "provisioning.porkbun.help",
        signup_url: "https://porkbun.com/account/signup",
        capabilities: &[Capability::Dns, Capability::Registrar],
        cors_policy: CorsPolicy::Open,
        fields: &[FieldMeta { id: "api-key", field_type: FieldType::Secret, label_key: "provisioning.porkbun.key", required: true, kinds: &[Capability::Dns, Capability::Registrar] }, FieldMeta { id: "secret-api-key", field_type: FieldType::Secret, label_key: "provisioning.porkbun.secret", required: true, kinds: &[Capability::Dns, Capability::Registrar] }],
        post_verify_select: Some(&PVS_PORKBUN),
        registrar_requires_contact: Some(false),
        registrar_notes_key: Some("provisioning.porkbun.registrar_account_contact_note"),
        curated_offers: &[],
        tld_pricing_endpoint: Some("https://api.porkbun.com/api/json/v3/pricing/get"),
        dns_dispatch: Some("PorkbunDns"),
        vps_dispatch: None,
        registrar_dispatch: Some("PorkbunRegistrar"),
    },
    ProviderMeta {
        id: ProviderId::Hetzner,
        display_name_key: "provisioning.hetzner.name",
        help_key: "provisioning.hetzner.help",
        signup_url: "https://accounts.hetzner.com/signUp",
        capabilities: &[Capability::Dns, Capability::Vps],
        cors_policy: CorsPolicy::Open,
        fields: &[FieldMeta { id: "api-token", field_type: FieldType::Secret, label_key: "provisioning.hetzner.api_token", required: true, kinds: &[Capability::Vps, Capability::Dns] }],
        post_verify_select: Some(&PVS_HETZNER),
        registrar_requires_contact: None,
        registrar_notes_key: None,
        curated_offers: &["cx23", "cx33", "cx43", "ccx13", "ccx23"],
        tld_pricing_endpoint: None,
        dns_dispatch: Some("HetznerDns"),
        vps_dispatch: Some("HetznerVps"),
        registrar_dispatch: None,
    },
    ProviderMeta {
        id: ProviderId::Namecheap,
        display_name_key: "provisioning.namecheap.name",
        help_key: "provisioning.namecheap.help",
        signup_url: "https://www.namecheap.com/myaccount/signup/",
        capabilities: &[Capability::Dns, Capability::Registrar],
        cors_policy: CorsPolicy::Proxy,
        fields: &[FieldMeta { id: "api-user", field_type: FieldType::Text, label_key: "provisioning.namecheap.api_user", required: true, kinds: &[Capability::Dns, Capability::Registrar] }, FieldMeta { id: "api-key", field_type: FieldType::Secret, label_key: "provisioning.namecheap.api_key", required: true, kinds: &[Capability::Dns, Capability::Registrar] }],
        post_verify_select: Some(&PVS_NAMECHEAP),
        registrar_requires_contact: Some(true),
        registrar_notes_key: None,
        curated_offers: &[],
        tld_pricing_endpoint: None,
        dns_dispatch: Some("NamecheapDns"),
        vps_dispatch: None,
        registrar_dispatch: Some("NamecheapRegistrar"),
    },
    ProviderMeta {
        id: ProviderId::Gandi,
        display_name_key: "provisioning.gandi.name",
        help_key: "provisioning.gandi.help",
        signup_url: "https://id.gandi.net/sign-up",
        capabilities: &[Capability::Dns, Capability::Registrar],
        cors_policy: CorsPolicy::Proxy,
        fields: &[FieldMeta { id: "personal-access-token", field_type: FieldType::Secret, label_key: "provisioning.gandi.personal_access_token", required: true, kinds: &[Capability::Dns, Capability::Registrar] }],
        post_verify_select: Some(&PVS_GANDI),
        registrar_requires_contact: Some(true),
        registrar_notes_key: None,
        curated_offers: &[],
        tld_pricing_endpoint: None,
        dns_dispatch: Some("GandiDns"),
        vps_dispatch: None,
        registrar_dispatch: Some("GandiRegistrar"),
    },
    ProviderMeta {
        id: ProviderId::Digitalocean,
        display_name_key: "provisioning.digitalocean.name",
        help_key: "provisioning.digitalocean.help",
        signup_url: "https://cloud.digitalocean.com/registrations/new",
        capabilities: &[Capability::Vps],
        cors_policy: CorsPolicy::Open,
        fields: &[FieldMeta { id: "api-token", field_type: FieldType::Secret, label_key: "provisioning.digitalocean.api_token", required: true, kinds: &[Capability::Vps] }],
        post_verify_select: Some(&PVS_DIGITALOCEAN),
        registrar_requires_contact: None,
        registrar_notes_key: None,
        curated_offers: &["s-1vcpu-1gb", "s-1vcpu-2gb", "s-2vcpu-2gb", "s-2vcpu-4gb", "s-4vcpu-8gb"],
        tld_pricing_endpoint: None,
        dns_dispatch: None,
        vps_dispatch: Some("DigitaloceanVps"),
        registrar_dispatch: None,
    },
    ProviderMeta {
        id: ProviderId::Vultr,
        display_name_key: "provisioning.vultr.name",
        help_key: "provisioning.vultr.help",
        signup_url: "https://www.vultr.com/register/",
        capabilities: &[Capability::Vps],
        cors_policy: CorsPolicy::Proxy,
        fields: &[FieldMeta { id: "api-key", field_type: FieldType::Secret, label_key: "provisioning.vultr.api_key", required: true, kinds: &[Capability::Vps] }],
        post_verify_select: Some(&PVS_VULTR),
        registrar_requires_contact: None,
        registrar_notes_key: None,
        curated_offers: &["vc2-1c-1gb", "vc2-1c-2gb", "vc2-2c-4gb", "vhf-1c-2gb", "vhf-2c-4gb"],
        tld_pricing_endpoint: None,
        dns_dispatch: None,
        vps_dispatch: Some("VultrVps"),
        registrar_dispatch: None,
    },
    ProviderMeta {
        id: ProviderId::Ovh,
        display_name_key: "provisioning.ovh.name",
        help_key: "provisioning.ovh.help",
        signup_url: "https://www.ovhcloud.com/en/auth/signup/",
        capabilities: &[Capability::Vps],
        cors_policy: CorsPolicy::Open,
        fields: &[FieldMeta { id: "app-key", field_type: FieldType::Secret, label_key: "provisioning.ovh.app_key", required: true, kinds: &[Capability::Vps] }, FieldMeta { id: "app-secret", field_type: FieldType::Secret, label_key: "provisioning.ovh.app_secret", required: true, kinds: &[Capability::Vps] }, FieldMeta { id: "consumer-key", field_type: FieldType::Secret, label_key: "provisioning.ovh.consumer_key", required: true, kinds: &[Capability::Vps] }],
        post_verify_select: Some(&PVS_OVH),
        registrar_requires_contact: None,
        registrar_notes_key: None,
        curated_offers: &[],
        tld_pricing_endpoint: None,
        dns_dispatch: None,
        vps_dispatch: Some("OvhVps"),
        registrar_dispatch: None,
    },
    ProviderMeta {
        id: ProviderId::Linode,
        display_name_key: "provisioning.linode.name",
        help_key: "provisioning.linode.help",
        signup_url: "https://login.linode.com/signup",
        capabilities: &[Capability::Vps],
        cors_policy: CorsPolicy::Open,
        fields: &[FieldMeta { id: "api-token", field_type: FieldType::Secret, label_key: "provisioning.linode.api_token", required: true, kinds: &[Capability::Vps] }],
        post_verify_select: Some(&PVS_LINODE),
        registrar_requires_contact: None,
        registrar_notes_key: None,
        curated_offers: &["g6-nanode-1", "g6-standard-1", "g6-standard-2", "g6-standard-4", "g6-dedicated-2"],
        tld_pricing_endpoint: None,
        dns_dispatch: None,
        vps_dispatch: Some("LinodeVps"),
        registrar_dispatch: None,
    },
    ProviderMeta {
        id: ProviderId::Bundled,
        display_name_key: "provisioning.bundled.name",
        help_key: "provisioning.bundled.help",
        signup_url: "https://github.com/faunasocial/fauna/blob/main/docs/goal/architecture/provisioning/bundled-provider-api.md",
        capabilities: &[Capability::Dns, Capability::Vps, Capability::Registrar],
        cors_policy: CorsPolicy::Open,
        fields: &[FieldMeta { id: "base-url", field_type: FieldType::Text, label_key: "provisioning.bundled.base_url", required: true, kinds: &[Capability::Dns, Capability::Vps, Capability::Registrar] }, FieldMeta { id: "api-token", field_type: FieldType::HostedAuth, label_key: "provisioning.bundled.account", required: true, kinds: &[Capability::Dns, Capability::Vps, Capability::Registrar] }],
        post_verify_select: Some(&PVS_BUNDLED),
        registrar_requires_contact: Some(true),
        registrar_notes_key: None,
        curated_offers: &["*"],
        tld_pricing_endpoint: None,
        dns_dispatch: Some("BundledDns"),
        vps_dispatch: Some("BundledVps"),
        registrar_dispatch: Some("BundledRegistrar"),
    },
];
