//! ISO 3166-1 alpha-3 → alpha-2, for the one leaf that hands over a
//! three-letter code: an app store's storefront (Apple's StoreKit
//! `Storefront.countryCode` is alpha-3). Shared so no shell grows its own table
//! (`region-blocking.md` § Region determination: a store build reads its
//! storefront).

/// Every officially assigned ISO 3166-1 code, `(alpha-3, alpha-2)`, plus Apple's
/// storefront code for Kosovo (`XKS` → `XK`, a user-assigned code in both
/// alphabets that Apple's store uses for its Kosovo storefront).
const ALPHA3_TO_ALPHA2: &[(&str, &str)] = &[
    ("ABW", "AW"),
    ("AFG", "AF"),
    ("AGO", "AO"),
    ("AIA", "AI"),
    ("ALA", "AX"),
    ("ALB", "AL"),
    ("AND", "AD"),
    ("ARE", "AE"),
    ("ARG", "AR"),
    ("ARM", "AM"),
    ("ASM", "AS"),
    ("ATA", "AQ"),
    ("ATF", "TF"),
    ("ATG", "AG"),
    ("AUS", "AU"),
    ("AUT", "AT"),
    ("AZE", "AZ"),
    ("BDI", "BI"),
    ("BEL", "BE"),
    ("BEN", "BJ"),
    ("BES", "BQ"),
    ("BFA", "BF"),
    ("BGD", "BD"),
    ("BGR", "BG"),
    ("BHR", "BH"),
    ("BHS", "BS"),
    ("BIH", "BA"),
    ("BLM", "BL"),
    ("BLR", "BY"),
    ("BLZ", "BZ"),
    ("BMU", "BM"),
    ("BOL", "BO"),
    ("BRA", "BR"),
    ("BRB", "BB"),
    ("BRN", "BN"),
    ("BTN", "BT"),
    ("BVT", "BV"),
    ("BWA", "BW"),
    ("CAF", "CF"),
    ("CAN", "CA"),
    ("CCK", "CC"),
    ("CHE", "CH"),
    ("CHL", "CL"),
    ("CHN", "CN"),
    ("CIV", "CI"),
    ("CMR", "CM"),
    ("COD", "CD"),
    ("COG", "CG"),
    ("COK", "CK"),
    ("COL", "CO"),
    ("COM", "KM"),
    ("CPV", "CV"),
    ("CRI", "CR"),
    ("CUB", "CU"),
    ("CUW", "CW"),
    ("CXR", "CX"),
    ("CYM", "KY"),
    ("CYP", "CY"),
    ("CZE", "CZ"),
    ("DEU", "DE"),
    ("DJI", "DJ"),
    ("DMA", "DM"),
    ("DNK", "DK"),
    ("DOM", "DO"),
    ("DZA", "DZ"),
    ("ECU", "EC"),
    ("EGY", "EG"),
    ("ERI", "ER"),
    ("ESH", "EH"),
    ("ESP", "ES"),
    ("EST", "EE"),
    ("ETH", "ET"),
    ("FIN", "FI"),
    ("FJI", "FJ"),
    ("FLK", "FK"),
    ("FRA", "FR"),
    ("FRO", "FO"),
    ("FSM", "FM"),
    ("GAB", "GA"),
    ("GBR", "GB"),
    ("GEO", "GE"),
    ("GGY", "GG"),
    ("GHA", "GH"),
    ("GIB", "GI"),
    ("GIN", "GN"),
    ("GLP", "GP"),
    ("GMB", "GM"),
    ("GNB", "GW"),
    ("GNQ", "GQ"),
    ("GRC", "GR"),
    ("GRD", "GD"),
    ("GRL", "GL"),
    ("GTM", "GT"),
    ("GUF", "GF"),
    ("GUM", "GU"),
    ("GUY", "GY"),
    ("HKG", "HK"),
    ("HMD", "HM"),
    ("HND", "HN"),
    ("HRV", "HR"),
    ("HTI", "HT"),
    ("HUN", "HU"),
    ("IDN", "ID"),
    ("IMN", "IM"),
    ("IND", "IN"),
    ("IOT", "IO"),
    ("IRL", "IE"),
    ("IRN", "IR"),
    ("IRQ", "IQ"),
    ("ISL", "IS"),
    ("ISR", "IL"),
    ("ITA", "IT"),
    ("JAM", "JM"),
    ("JEY", "JE"),
    ("JOR", "JO"),
    ("JPN", "JP"),
    ("KAZ", "KZ"),
    ("KEN", "KE"),
    ("KGZ", "KG"),
    ("KHM", "KH"),
    ("KIR", "KI"),
    ("KNA", "KN"),
    ("KOR", "KR"),
    ("KWT", "KW"),
    ("LAO", "LA"),
    ("LBN", "LB"),
    ("LBR", "LR"),
    ("LBY", "LY"),
    ("LCA", "LC"),
    ("LIE", "LI"),
    ("LKA", "LK"),
    ("LSO", "LS"),
    ("LTU", "LT"),
    ("LUX", "LU"),
    ("LVA", "LV"),
    ("MAC", "MO"),
    ("MAF", "MF"),
    ("MAR", "MA"),
    ("MCO", "MC"),
    ("MDA", "MD"),
    ("MDG", "MG"),
    ("MDV", "MV"),
    ("MEX", "MX"),
    ("MHL", "MH"),
    ("MKD", "MK"),
    ("MLI", "ML"),
    ("MLT", "MT"),
    ("MMR", "MM"),
    ("MNE", "ME"),
    ("MNG", "MN"),
    ("MNP", "MP"),
    ("MOZ", "MZ"),
    ("MRT", "MR"),
    ("MSR", "MS"),
    ("MTQ", "MQ"),
    ("MUS", "MU"),
    ("MWI", "MW"),
    ("MYS", "MY"),
    ("MYT", "YT"),
    ("NAM", "NA"),
    ("NCL", "NC"),
    ("NER", "NE"),
    ("NFK", "NF"),
    ("NGA", "NG"),
    ("NIC", "NI"),
    ("NIU", "NU"),
    ("NLD", "NL"),
    ("NOR", "NO"),
    ("NPL", "NP"),
    ("NRU", "NR"),
    ("NZL", "NZ"),
    ("OMN", "OM"),
    ("PAK", "PK"),
    ("PAN", "PA"),
    ("PCN", "PN"),
    ("PER", "PE"),
    ("PHL", "PH"),
    ("PLW", "PW"),
    ("PNG", "PG"),
    ("POL", "PL"),
    ("PRI", "PR"),
    ("PRK", "KP"),
    ("PRT", "PT"),
    ("PRY", "PY"),
    ("PSE", "PS"),
    ("PYF", "PF"),
    ("QAT", "QA"),
    ("REU", "RE"),
    ("ROU", "RO"),
    ("RUS", "RU"),
    ("RWA", "RW"),
    ("SAU", "SA"),
    ("SDN", "SD"),
    ("SEN", "SN"),
    ("SGP", "SG"),
    ("SGS", "GS"),
    ("SHN", "SH"),
    ("SJM", "SJ"),
    ("SLB", "SB"),
    ("SLE", "SL"),
    ("SLV", "SV"),
    ("SMR", "SM"),
    ("SOM", "SO"),
    ("SPM", "PM"),
    ("SRB", "RS"),
    ("SSD", "SS"),
    ("STP", "ST"),
    ("SUR", "SR"),
    ("SVK", "SK"),
    ("SVN", "SI"),
    ("SWE", "SE"),
    ("SWZ", "SZ"),
    ("SXM", "SX"),
    ("SYC", "SC"),
    ("SYR", "SY"),
    ("TCA", "TC"),
    ("TCD", "TD"),
    ("TGO", "TG"),
    ("THA", "TH"),
    ("TJK", "TJ"),
    ("TKL", "TK"),
    ("TKM", "TM"),
    ("TLS", "TL"),
    ("TON", "TO"),
    ("TTO", "TT"),
    ("TUN", "TN"),
    ("TUR", "TR"),
    ("TUV", "TV"),
    ("TWN", "TW"),
    ("TZA", "TZ"),
    ("UGA", "UG"),
    ("UKR", "UA"),
    ("UMI", "UM"),
    ("URY", "UY"),
    ("USA", "US"),
    ("UZB", "UZ"),
    ("VAT", "VA"),
    ("VCT", "VC"),
    ("VEN", "VE"),
    ("VGB", "VG"),
    ("VIR", "VI"),
    ("VNM", "VN"),
    ("VUT", "VU"),
    ("WLF", "WF"),
    ("WSM", "WS"),
    ("XKS", "XK"),
    ("YEM", "YE"),
    ("ZAF", "ZA"),
    ("ZMB", "ZM"),
    ("ZWE", "ZW"),
];

/// The alpha-2 code for one alpha-3 code — `None` for anything not in the
/// table. Never case-folds, like `RegionCode::parse`: a store hands over the
/// canonical upper-case form, and a lower-case code is not one.
pub fn alpha2_for_alpha3(alpha3: &str) -> Option<&'static str> {
    ALPHA3_TO_ALPHA2
        .binary_search_by(|(a3, _)| (*a3).cmp(alpha3))
        .ok()
        .map(|i| ALPHA3_TO_ALPHA2[i].1)
}

#[cfg(test)]
mod tests {
    use super::*;
    use fauna_core::region_authority::RegionCode;
    use std::collections::BTreeSet;

    #[test]
    fn the_table_is_sorted_complete_and_one_to_one() {
        // Sorted, so the binary search is sound.
        assert!(ALPHA3_TO_ALPHA2.windows(2).all(|w| w[0].0 < w[1].0));
        // The 249 officially assigned codes + Apple's Kosovo storefront.
        assert_eq!(ALPHA3_TO_ALPHA2.len(), 250);
        let alpha2: BTreeSet<_> = ALPHA3_TO_ALPHA2.iter().map(|(_, a2)| a2).collect();
        assert_eq!(
            alpha2.len(),
            ALPHA3_TO_ALPHA2.len(),
            "an alpha-2 code appears twice"
        );
        for (a3, a2) in ALPHA3_TO_ALPHA2 {
            assert!(
                a3.len() == 3 && a3.bytes().all(|b| b.is_ascii_uppercase()),
                "{a3}"
            );
            assert!(RegionCode::parse(*a2).is_ok(), "{a2} is not a region code");
        }
    }

    #[test]
    fn known_codes_map_and_others_do_not() {
        assert_eq!(alpha2_for_alpha3("NOR"), Some("NO"));
        assert_eq!(alpha2_for_alpha3("USA"), Some("US"));
        assert_eq!(alpha2_for_alpha3("GBR"), Some("GB"));
        assert_eq!(alpha2_for_alpha3("DEU"), Some("DE"));
        assert_eq!(alpha2_for_alpha3("ABW"), Some("AW"));
        assert_eq!(alpha2_for_alpha3("ZWE"), Some("ZW"));
        assert_eq!(alpha2_for_alpha3("nor"), None, "never case-folds");
        assert_eq!(alpha2_for_alpha3("NO"), None);
        assert_eq!(alpha2_for_alpha3("XXX"), None);
        assert_eq!(alpha2_for_alpha3(""), None);
    }
}
