<script lang="ts">
  // User-settings "Mail" section: the user-facing mail-credential lifecycle
  // (enable mail, add/revoke credentials, rotate keys). A dumb renderer of the
  // shared `MailSettingsMachine` (`libs/fauna-client-mail-settings`, WASM twin
  // `WasmMailSettingsMachine`): build over the singleton WS-RPC client →
  // `hydrate()` → render `snapshot()` → `dispatch(action)` → re-render. No mail
  // logic in the SPA (priority #2). Lifts the linux lead shape
  // (apps/fauna-linux/src/settings/mail.rs), which embeds the surface in the
  // settings view with an inline add-credential reveal (not a modal) — the e2e
  // (`tests/e2e-unified/actions/mail_settings.py`) navigates to the settings tab
  // and drives the toggle + inline form. Reuses the settings page's single
  // `error-message` (no duplicate IDs) via the bindable `error`.
  // Behavior + IDs: docs/goal/ui/mail-settings.md, ui.yaml § mail-settings.
  import { identity } from '$lib/store';
  import { mailSettingsMachine, setupStatus } from '$lib/rpc';
  import {
    ensureWasm,
    generateBridgeToken,
    resolveAutogeneratedBridgePassword,
    warnManualBridgePassword,
    passwordStrengthLabel,
    credentialKindBadge,
    settingsStatusLabel,
    resolveMuaUsername,
  } from '$lib/wasm';
  import { resolveLocalized } from '$lib/i18n/localized';
  import { onMount } from 'svelte';
  import { configStageSettled } from '$lib/succession-aftermath';
  import { t } from '$lib/i18n/strings';
  import type { WasmMailSettingsMachine } from '../../../static/fauna_wasm.js';
  import { IDS } from '$lib/generated/uiIds';

  // The parent settings page owns the single error surface; mail dispatch errors
  // flow into it.
  let { error = $bindable('') } = $props();

  // Shapes mirror the shared `MailSettingsSnapshot` serde JSON (snake_case across
  // the serde_wasm_bindgen boundary). Typed locally over the `any` snapshot.
  interface CredentialRow {
    credential_id: string;
    display_name: string;
    kind: string; // "OAuthBearer" | "Plain"
    created_at: number;
    // The concrete MUA username with the `+<credential_id>` suffix, `default`→bare
    // rule, and domain already resolved in shared Rust — only `{handle}` remains
    // (mail-settings.md § State). Rendered via the shared `resolveMuaUsername`.
    mua_username: string;
    // Succession's *Compromised — access revoked* state (`mail-credentials.md`
    // § Rotation and recovery → Succession) — the row survives so the user
    // knows what to set up again, but must never read as usable.
    revoked: boolean;
  }
  interface MuaInstructions {
    imap_host: string;
    imap_port: number;
    smtp_host: string;
    smtp_port: number;
    // CalDAV server URL host + port (= `mail.<domain>` / 443). The one shared
    // credential AUTHs CalDAV too, so a CalDAV-only actor needs these connection
    // details (mail-settings.md § CalDAV-only mailbox; caldav-server.md § Network
    // exposure). Additive over wasm — the snapshot JSON already carries them.
    caldav_host: string;
    caldav_port: number;
    // The full WebDAV collection-root URL to mount (`https://mail.<domain>/webdav/`,
    // or the bare locator + DAV port on a local-target box). A full URL, not a
    // host+port pair: no SRV autodiscovery exists for WebDAV, so this line is the
    // primary setup surface (mail-settings.md § WebDAV files). Built in shared Rust.
    webdav_url: string;
    username_format: string;
    auth_mechanism: string;
  }
  interface MailSnapshot {
    // True iff **email** (SMTP + IMAP) is on for this actor (keys on the
    // `mail_enabled` flag, NOT merely on having an MSEK). A CalDAV-only actor
    // reads `enabled: false` with `caldav_enabled: true`.
    enabled: boolean;
    // True iff **CalDAV** (calendar) is on, independent of email. Both ride the
    // one shared MSEK + `default` credential (caldav-server.md § Authentication —
    // "no separate CalDAV credential"), so the credential-management section +
    // serve-here toggle render whenever the mailbox is provisioned
    // (`enabled || caldav_enabled`), not only when email is on
    // (mail-settings.md § CalDAV-only mailbox).
    caldav_enabled: boolean;
    // True iff **CardDAV** (contacts / address book) is on — the contacts
    // sibling of `caldav_enabled`, same shared MSEK + credential, so it joins
    // the credential-section render predicate
    // (`enabled || caldav_enabled || carddav_enabled`;
    // carddav-server.md § Independent enablement).
    carddav_enabled: boolean;
    // True iff this actor serves >=1 folder over WebDAV (the per-actor serve
    // state, folded from `fauna.folders.list` — NOT the deployment-wide
    // `webdav_enabled` toggle, which defaults on). Joins the reachability
    // predicate and gates the MUA WebDAV URL row (webdav-server.md
    // § Independent enablement pt 1).
    serves_webdav_set: boolean;
    // The credential-management reachability predicate, computed once in shared
    // Rust: `enabled || caldav_enabled || carddav_enabled || serves_webdav_set`.
    // Read it — never re-derive it here (priority #2/#4).
    credential_management_reachable: boolean;
    // Per-actor "serve my mailbox over IMAP/CalDAV on this nest" flag (default
    // on). A nest-side flag, not synced — set via SetServingEnabled, read on
    // hydrate (mail-settings.md § Local IMAP/CalDAV-serving toggle).
    serving_enabled: boolean;
    credentials: CredentialRow[];
    pending_rotation: { credentials_remaining: string[] } | null;
    mua: MuaInstructions;
    // SettingsStatus is "Idle" / "Syncing" / { RotationInProgress: { credentials_remaining } }.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    status: any;
    error: string | null;
  }

  let machine: WasmMailSettingsMachine | null = null;
  let snap = $state<MailSnapshot | null>(null);

  // The credential-management reachability predicate — email OR CalDAV OR CardDAV
  // on, OR >=1 folder served over WebDAV. All ride the one shared MSEK +
  // `default` credential, so the credential-management section (keys explainer,
  // credentials list, add/rotate) and the serve-here toggle render whenever a
  // mailbox exists or is needed, NOT only when email is on (mail-settings.md
  // § CalDAV-only mailbox). The email IMAP/SMTP connection block stays gated on
  // `enabled`. Computed once in shared Rust (`MailSettingsSnapshot::
  // credential_management_reachable`) — every app reads the field rather than
  // re-deriving the disjunction, so a future DAV sibling widens it in one place
  // (priority #2/#4).
  const mailbox = $derived(Boolean(snap?.credential_management_reachable));

  // Inline add-credential form (reveal, not modal — matches linux). The form is
  // opened from two entry points with different intent: the enabled-toggle
  // ('enable' → first-credential EnableMail) and the add-credential button
  // ('add' → AddCredential onto the existing mailbox). The intent is captured at
  // open time, mirroring the linux lead's `FormMode::Enable`/`FormMode::Add` — a
  // live-`snap.enabled` inference can't distinguish a CalDAV-only mailbox
  // (enabled=false but a mailbox/MSEK already exists, so add-credential must
  // dispatch AddCredential, never EnableMail which would turn email on).
  let formOpen = $state(false);
  let formIntent = $state<'enable' | 'add'>('enable');
  let nameInput = $state('Default');
  let isPlain = $state(false); // type-selector: false = OAUTHBEARER (default), true = PLAIN
  // PLAIN auto-generate (mail-add-credential-autogenerate-toggle): ON by default
  // (mail-credentials.md § Auto-generated bridge password). When on, the password
  // input holds a shared-Rust-generated a-zA-Z0-9 secret and is read-only; turning
  // it off enables manual entry (and, on an encrypted nest, the weak-password
  // warning). All decision logic is shared Rust (priority #2) — see applyAutogen.
  let autoGenerate = $state(true);
  let showWeakWarning = $state(false);
  let passwordInput = $state('');
  let showPassword = $state(false);
  let tokenShown = $state(''); // OAUTHBEARER one-time token reveal (after submit)
  // Every nest stores at rest encrypted (no-modes, ratified 2026-07-12 —
  // docs/goal/architecture/nest/storage-modes.md), so the manual-password
  // warning's `nest_encrypted` input is unconditionally true — the same
  // constant tui and apple pass (`warn_manual_password(auto, true)`).
  const nestEncrypted = true;

  // Rotate-keys confirm (inline reveal).
  let rotateOpen = $state(false);

  // Disable-mail confirm (destructive overlay — mail-settings.md § Disable mail).
  // Flipping the enabled-toggle off opens this; confirming dispatches DisableMail
  // (bulk-revoke every credential + clear the MSEK). The toggle keeps rendering
  // "Mail enabled" until the confirmed DisableMail re-render flips snap.enabled —
  // no lying off-state, mirroring the linux lead's snap-back-on behavior.
  let disableConfirmOpen = $state(false);

  // Per-credential secret reveal (mail-settings.md § Credentials list). The secret
  // is NOT in the passive snapshot — clicking reveal fetches it on demand from the
  // client's own `fauna.state.mail` entries via the shared `MailSettingsMachine::reveal_credential_secret`
  // (wasm `revealCredentialSecret`), mirroring the shown-once reveal at credential-add
  // time. Held hidden by default and never logged or persisted; a second click hides it.
  let revealedSecrets = $state<Record<string, string>>({});

  async function toggleSecret(credentialId: string): Promise<void> {
    if (credentialId in revealedSecrets) {
      const next = { ...revealedSecrets };
      delete next[credentialId];
      revealedSecrets = next;
      return;
    }
    if (!machine) return;
    try {
      const secret = (await machine.revealCredentialSecret(credentialId)) as string;
      revealedSecrets = { ...revealedSecrets, [credentialId]: secret };
    } catch (e) {
      error = String(e);
    }
  }

  // The `mail-settings-status-indicator` decision (Syncing / RotationInProgress /
  // Idle-gated-on-enabled → which `settings.mail.status_*` key) lives in shared
  // Rust `fauna_client_mail_settings::settings_status_label` (over wasm) — the
  // same source of truth the native apps consume via UniFFI, so web no longer
  // hand-rolls the ternary. `Idle` reads `status_enabled` ONLY when mail is on
  // (a disabled or pre-hydrate mailbox reads `status_disabled` — the cross-app
  // "mail enabled" signal the e2e `wait_for_enabled_status` probe reads).
  // mail-settings.md § the status indicator.
  function statusLabel(status: unknown, enabled: boolean): string {
    return resolveLocalized(settingsStatusLabel(status, enabled));
  }

  // The exact MUA username for a credential. The shared snapshot already resolved
  // the `+<credential_id>` suffix, the `default`→bare rule, and the domain into
  // `MailCredentialSummary.mua_username` (mail-settings.md § State) — only
  // `{handle}` is left, which we substitute via the shared `resolveMuaUsername`
  // (priority #2: web no longer re-derives the bug-prone suffix, the gap that let
  // a user pick the wrong bare form for a `+suffix` credential). Callers run after
  // `ensureWasm()` — credential rows render only once the hydrated snapshot exists.
  function muaUsername(template: string): string {
    return resolveMuaUsername(template, $identity?.handle ?? '');
  }

  function applySnapshot(): void {
    if (!machine) return;
    snap = machine.snapshot() as unknown as MailSnapshot;
    if (snap?.error) error = snap.error;
  }

  onMount(async () => {
    const id = $identity;
    if (!id?.secretHex) return;
    try {
      await ensureWasm();
      machine = await mailSettingsMachine(id.secretHex);
      await machine.hydrate();
      applySnapshot();
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    }
    // Read the nest's storage mode once — only an ENCRYPTED nest surfaces the
  });

  // The post-store-ready aftermath pass settled — its last leg, the mail burn,
  // marks rows on the account's mail custody that this page's machine hydrated
  // before (succession-aftermath.md § Re-key scope → *Where the plane raises
  // run*). Re-read so a burn landing while the page is open shows its rows as
  // revoked, as the review surfaces re-read on the same hook.
  $effect(() => {
    if ($configStageSettled > 0 && machine) {
      void machine.hydrate().then(applySnapshot, () => {});
    }
  });

  // Click the enable toggle (mail-settings.md § Disable mail). Off → on: reveal the
  // first-credential form (EnableMail). On → off: open the destructive disable-confirm
  // overlay — the dialog is the real decision point, so the toggle keeps rendering
  // "Mail enabled" until a confirmed DisableMail flips snap.enabled (no lying off-state;
  // mirrors the linux lead's snap-back-on). Branch on the live snapshot, not a mode flag,
  // so a slow hydrate can't strand the wrong path.
  function onToggle(): void {
    if (snap?.enabled) {
      disableConfirmOpen = true;
      error = '';
    } else {
      // Enabling email from the toggle (works on a never-enabled OR a CalDAV-only
      // actor — EnableMail reuses the shared MSEK when one already exists).
      openForm('enable');
    }
  }

  function openAddCredential(): void {
    // Add a credential onto the existing mailbox (the button only renders when a
    // mailbox is provisioned, so the MSEK is always present → AddCredential).
    openForm('add');
  }

  function openForm(intent: 'enable' | 'add'): void {
    formIntent = intent;
    formOpen = true;
    nameInput = 'Default';
    isPlain = false;
    autoGenerate = true;
    showWeakWarning = false;
    passwordInput = '';
    showPassword = false;
    tokenShown = '';
    error = '';
  }

  // Select the PLAIN credential kind: reveal the password box and, since
  // auto-generate defaults ON, mint the first generated password into it.
  function selectPlain(): void {
    isPlain = !isPlain;
    if (isPlain) applyAutogen();
  }

  // Flip the auto-generate toggle and re-apply its effect on the password input.
  function onAutogenToggle(): void {
    autoGenerate = !autoGenerate;
    applyAutogen();
  }

  // Auto-generate ON (default): shared Rust mints a strong a-zA-Z0-9 password into
  // the read-only, revealed input, shown-once for the user to copy. OFF: clear it
  // for masked manual entry, show the strength meter, and — on an ENCRYPTED nest —
  // the manual-password warning (warn_manual_bridge_password). The mint-once
  // decision (kind + autoGenerate → fresh secret or clear) lives in shared Rust
  // via `resolveAutogeneratedBridgePassword` (mail-credentials.md § Mint-once
  // sequencing) — called only at this settled toggle edge, never again at submit,
  // so the persisted credential is byte-identical to what the user copied.
  // `applyAutogen` is only ever invoked while `isPlain` is true (selectPlain
  // guards its call, and the autogenerate toggle only renders `{#if isPlain}`),
  // so `kind` is always `'Plain'` here.
  function applyAutogen(): void {
    const resolved = resolveAutogeneratedBridgePassword('Plain', autoGenerate);
    if (resolved !== null) {
      passwordInput = resolved;
      showPassword = true; // reveal the generated secret so the user can copy it
    } else {
      passwordInput = '';
      showPassword = false;
    }
    showWeakWarning = warnManualBridgePassword(autoGenerate, nestEncrypted);
  }

  function cancelForm(): void {
    formOpen = false;
    tokenShown = '';
  }

  async function submitForm(): Promise<void> {
    if (!machine) return;
    const display_name = nameInput.trim() || 'Default';
    error = '';
    let secretBytes: Uint8Array;
    let tokenToShow = '';
    if (isPlain) {
      if (!passwordInput) {
        error = t.settings.mail.password_required;
        return;
      }
      secretBytes = new TextEncoder().encode(passwordInput);
    } else {
      // A fresh OAUTHBEARER token (shared Rust: 32 random bytes → 64 lowercase hex
      // chars) the human copies into their MUA; its UTF-8 bytes are the secret.
      tokenToShow = generateBridgeToken();
      secretBytes = new TextEncoder().encode(tokenToShow);
    }
    const kind = isPlain ? 'Plain' : 'OAuthBearer';
    // Decide enable-vs-add from the form's entry intent (linux `FormMode`), with a
    // hydrate-race guard:
    //  - 'add' (add-credential button) ⇒ AddCredential — the button renders only
    //    when a mailbox is provisioned, so the MSEK exists; this is correct for a
    //    CalDAV-only actor (where `snap.enabled` is false but a mailbox exists),
    //    the case a live-`snap.enabled` inference got wrong (it would EnableMail,
    //    turning email on).
    //  - 'enable' (enabled-toggle) ⇒ EnableMail, UNLESS `snap.enabled` already
    //    flipped true between open and submit (a slow hydrate / another tab), in
    //    which case AddCredential — EnableMail on an already-email-enabled actor
    //    errors.
    const variant =
      formIntent === 'add' || snap?.enabled ? 'AddCredential' : 'EnableMail';
    try {
      await machine.dispatch({ [variant]: { display_name, kind, secret: secretBytes } });
      applySnapshot();
      if (snap?.error) return; // leave the form open for retry
      if (tokenToShow) {
        // OAUTHBEARER success: reveal the one-time token; keep the form open.
        tokenShown = tokenToShow;
      } else {
        formOpen = false;
      }
    } catch (e) {
      applySnapshot();
      if (!error) error = e instanceof Error ? e.message : String(e);
    }
  }

  async function revokeCredential(credentialId: string): Promise<void> {
    if (!machine) return;
    try {
      await machine.dispatch({ RevokeCredential: { credential_id: credentialId } });
      applySnapshot();
    } catch (e) {
      applySnapshot();
      if (!error) error = e instanceof Error ? e.message : String(e);
    }
  }

  // Disable mail entirely (mail-settings.md § Disable mail): dispatch the shared
  // DisableMail (a unit `MailSettingsAction` → the bare string, like ResumeRotation)
  // — bulk soft-revoke every credential + clear the MSEK. The shared machine
  // deliberately does NOT touch the Admin-scoped deployment-wide set_mail_enabled
  // flag. The snapshot returns enabled:false with an empty credentials list; the
  // re-render flips the toggle back to "Enable mail". Cancel/dismiss is a no-op.
  async function confirmDisable(): Promise<void> {
    if (!machine) return;
    error = '';
    try {
      await machine.dispatch('DisableMail');
      applySnapshot();
    } catch (e) {
      applySnapshot();
      if (!error) error = e instanceof Error ? e.message : String(e);
    } finally {
      disableConfirmOpen = false;
    }
  }

  function cancelDisable(): void {
    disableConfirmOpen = false;
  }

  // Flip this nest's IMAP/CalDAV-serving for this actor. Non-optimistic: the
  // shared machine flips `serving_enabled` only after `set_mail_serving_enabled`
  // returns ok, so the rendered state (and the `data-state` attr the e2e reads)
  // reflects the nest's flag, not an optimistic local guess
  // (mail-settings.md § Local IMAP/CalDAV-serving toggle).
  async function onServeHereToggle(): Promise<void> {
    if (!machine || !snap) return;
    error = '';
    try {
      await machine.dispatch({ SetServingEnabled: { enabled: !snap.serving_enabled } });
      applySnapshot();
    } catch (e) {
      applySnapshot();
      if (!error) error = e instanceof Error ? e.message : String(e);
    }
  }

  async function confirmRotate(): Promise<void> {
    if (!machine) return;
    try {
      await machine.dispatch({ StartRotation: { excluded_credentials: [] } });
      applySnapshot();
      rotateOpen = false;
    } catch (e) {
      applySnapshot();
      if (!error) error = e instanceof Error ? e.message : String(e);
    }
  }

  async function resumeRotation(): Promise<void> {
    if (!machine) return;
    try {
      await machine.dispatch('ResumeRotation');
      applySnapshot();
    } catch (e) {
      applySnapshot();
      if (!error) error = e instanceof Error ? e.message : String(e);
    }
  }

  async function copyText(value: string): Promise<void> {
    try { await navigator.clipboard.writeText(value); } catch { /* headless / no perm */ }
  }
</script>

<section class="section">
  <!-- "Mail & Calendar" — the page covers the one shared credential + connection
       details for both the email and calendar protocols (mail-settings.md, the
       2026-06-18 rename; §3). Svelte auto-escapes `&`. -->
  <h2>{t.settings.mail.section_title}</h2>

  <!-- Enable toggle: off → "Enable mail" (reveals the first-credential form);
       on → "Mail enabled". `data-state` mirrors the serve-here toggle below —
       the e2e harness's `ensure_mail_enabled` phase-1 gate reads it via
       `driver.get_attr(id, "state")` instead of the derived status label. -->
  <button
    class="btn toggle"
    class:on={snap?.enabled}
    data-testid={IDS.MAIL_SETTINGS_ENABLED_TOGGLE}
    data-state={snap?.enabled ? 'on' : 'off'}
    onclick={onToggle}
  >{t.settings.mail.enable_title}</button>

  <span class="status muted" data-testid={IDS.MAIL_SETTINGS_STATUS_INDICATOR}>
    {statusLabel(snap?.status, Boolean(snap?.enabled))}
  </span>

  <!-- (i) keys explainer: what the encryption keys protect + when to rotate
       (suspected compromise) vs revoke a single retired credential. Copy is the
       shared S.mail_settings.keys_info. Part of the credential-management section,
       so it renders whenever a mailbox is provisioned (email OR CalDAV). -->
  {#if mailbox}
    <p class="muted small keys-info" data-testid={IDS.MAIL_SETTINGS_KEYS_INFO}>{t.mail_settings.keys_info}</p>
  {/if}

  {#if snap?.pending_rotation}
    <div class="banner" data-testid={IDS.MAIL_SETTINGS_PENDING_ROTATION_BANNER}>
      <span>{t.settings.mail.banner_title}</span>
      <button class="btn" data-testid={IDS.MAIL_SETTINGS_PENDING_ROTATION_RESUME_BUTTON} onclick={resumeRotation}>
        {t.settings.mail.resume}
      </button>
    </div>
  {/if}

  <!-- Add-credential is reachable whenever a mailbox is provisioned (email OR
       CalDAV) so a CalDAV-only actor can mint + manage its one shared bridge
       password; rotate appears once ≥1 credential exists (mirrors the linux lead:
       manage_group on `mailbox`, rotate on `!credentials.is_empty()`). -->
  {#if mailbox}
    <div class="actions">
      <button class="btn" data-testid={IDS.MAIL_SETTINGS_ADD_CREDENTIAL_BUTTON} onclick={openAddCredential}>
        {t.settings.mail.add_credential}
      </button>
      {#if (snap?.credentials.length ?? 0) >= 1}
        <button class="btn" data-testid={IDS.MAIL_SETTINGS_ROTATE_KEYS_BUTTON} onclick={() => { rotateOpen = true; error = ''; }}>
          {t.settings.mail.rotate_keys}
        </button>
      {/if}
    </div>
  {/if}

  <!-- Local IMAP/CalDAV-serving toggle (mail-settings.md § Local IMAP/CalDAV-
       serving toggle). User-set, default on; visible once a mailbox is
       provisioned (email OR CalDAV — nothing to serve otherwise). It applies to a
       CalDAV-only mailbox as much as an email one, so it follows `mailbox`, not
       `enabled`. One flag covers IMAP + CalDAV; it never gates the user's own
       in-client mail/Events reads. The on/off rides `snapshot().serving_enabled`;
       the flip dispatches SetServingEnabled and is non-optimistic, so `data-state`
       (the e2e read idiom) tracks the nest. -->
  {#if mailbox}
    <div class="serve-here">
      <button
        class="btn toggle"
        class:on={snap?.serving_enabled}
        data-testid={IDS.MAIL_SETTINGS_SERVE_HERE_TOGGLE}
        data-state={snap?.serving_enabled ? 'on' : 'off'}
        onclick={onServeHereToggle}
      >{t.mail_settings.serve_here_label}</button>
      <p class="muted small">{t.mail_settings.serve_here_subtitle}</p>
    </div>
  {/if}

  <!-- Inline add-credential form (EnableMail / AddCredential). -->
  {#if formOpen}
    <div class="form">
      {#if !tokenShown}
        <input
          class="input"
          data-testid={IDS.MAIL_ADD_CREDENTIAL_NAME_INPUT}
          placeholder={t.settings.mail.name_placeholder}
          bind:value={nameInput}
        />
        <button
          class="btn toggle"
          class:on={isPlain}
          data-testid={IDS.MAIL_ADD_CREDENTIAL_TYPE_SELECTOR}
          onclick={selectPlain}
        >{t.settings.mail.type_selector}</button>

        {#if isPlain}
          <!-- Auto-generate (default ON): a shared-Rust strong password fills the
               read-only input shown-once for copy; off → manual entry. -->
          <button
            class="btn toggle"
            class:on={autoGenerate}
            data-testid={IDS.MAIL_ADD_CREDENTIAL_AUTOGENERATE_TOGGLE}
            onclick={onAutogenToggle}
          >{t.settings.mail.autogenerate}</button>
          <div class="pw-row">
            <input
              class="input"
              data-testid={IDS.MAIL_ADD_CREDENTIAL_PASSWORD_INPUT}
              type={showPassword || autoGenerate ? 'text' : 'password'}
              readonly={autoGenerate}
              placeholder={t.settings.mail.password_placeholder}
              bind:value={passwordInput}
            />
            {#if !autoGenerate}
              <button
                class="btn"
                data-testid={IDS.MAIL_ADD_CREDENTIAL_PASSWORD_SHOW_TOGGLE}
                onclick={() => { showPassword = !showPassword; }}
              >{showPassword ? t.settings.mail.hide : t.settings.mail.show}</button>
            {/if}
          </div>
          {#if !autoGenerate}
            {@const strength = passwordStrengthLabel(passwordInput)}
            <span class="muted small" data-testid={IDS.MAIL_ADD_CREDENTIAL_PASSWORD_STRENGTH_METER}>
              {strength ? resolveLocalized(strength) : ''}
            </span>
          {/if}
          {#if showWeakWarning}
            <span class="warn small" data-testid={IDS.MAIL_ADD_CREDENTIAL_WEAK_PASSWORD_WARNING}>{t.settings.mail.weak_password_warning}</span>
          {/if}
        {/if}
      {:else}
        <!-- OAUTHBEARER one-time token reveal (shown only once). -->
        <p class="muted small">{t.settings.mail.token_warning}</p>
        <code class="mono token" data-testid={IDS.MAIL_ADD_CREDENTIAL_TOKEN_DISPLAY}>{tokenShown}</code>
        <button class="btn" data-testid={IDS.MAIL_ADD_CREDENTIAL_TOKEN_COPY_BUTTON} onclick={() => copyText(tokenShown)}>
          {t.settings.mail.copy_token}
        </button>
      {/if}

      <div class="form-actions">
        {#if !tokenShown}
          <button class="btn primary" data-testid={IDS.MAIL_ADD_CREDENTIAL_SUBMIT_BUTTON} onclick={submitForm}>
            {formIntent === 'enable' ? t.settings.mail.submit_enable : t.settings.mail.submit_add}
          </button>
        {/if}
        <button class="btn" data-testid={IDS.MAIL_ADD_CREDENTIAL_CANCEL_BUTTON} onclick={cancelForm}>
          {tokenShown ? t.settings.mail.done : t.settings.mail.cancel}
        </button>
      </div>
    </div>
  {/if}

  <!-- Rotate-keys confirm (inline reveal). -->
  {#if rotateOpen}
    <div class="form">
      <p class="muted small" data-testid={IDS.MAIL_ROTATE_KEYS_WARNING_TEXT}>{t.settings.mail.rotate_warning}</p>
      <div data-testid={IDS.MAIL_ROTATE_KEYS_EXCLUDE_LIST}>
        <!-- Per-credential exclude checkboxes; the e2e drives a no-exclusion rotation. -->
        {#each snap?.credentials ?? [] as c}
          <label class="exclude-row">
            <input type="checkbox" disabled />
            <span>{c.display_name}</span>
          </label>
        {/each}
      </div>
      <span class="muted small" data-testid={IDS.MAIL_ROTATE_KEYS_PROGRESS_INDICATOR}>{statusLabel(snap?.status, Boolean(snap?.enabled))}</span>
      <div class="form-actions">
        <button class="btn primary" data-testid={IDS.MAIL_ROTATE_KEYS_CONFIRM_BUTTON} onclick={confirmRotate}>
          {t.settings.mail.rotate_confirm}
        </button>
        <button class="btn" data-testid={IDS.MAIL_ROTATE_KEYS_CANCEL_BUTTON} onclick={() => { rotateOpen = false; }}>
          {t.settings.mail.cancel}
        </button>
      </div>
    </div>
  {/if}

  <!-- Disable-mail confirmation (destructive overlay — mail-settings.md § Disable
       mail). Opened by flipping the enabled-toggle off; confirming dispatches the
       shared DisableMail (bulk-revoke every credential + clear the MSEK). Cancel is
       a no-op — the toggle was never actually flipped off. The dialog carries
       `mail-settings-disable-confirm` for e2e discovery/scoping; the destructive
       button carries `mail-settings-disable-confirm-button`. -->
  {#if disableConfirmOpen}
    <div class="overlay" role="dialog">
      <div class="dialog" data-testid={IDS.MAIL_SETTINGS_DISABLE_CONFIRM}>
        <p><strong>{t.settings.mail.disable_title}</strong></p>
        <p>{t.settings.mail.disable_warning}</p>
        <div class="dialog-actions">
          <button class="btn danger" data-testid={IDS.MAIL_SETTINGS_DISABLE_CONFIRM_BUTTON} onclick={confirmDisable}>
            {t.settings.mail.disable_confirm}
          </button>
          <button class="btn" onclick={cancelDisable}>{t.settings.mail.cancel}</button>
        </div>
      </div>
    </div>
  {/if}

  <!-- Mail-disabled view: heading + toggle + a short explanation sentence
       (mail-settings.md § "When mail is disabled: only the toggle + heading + a
       short explanation sentence"). Gated on !mailbox to match the linux lead and
       android (apps/fauna-linux/src/settings/mail.rs:215;
       MailSettingsScreen.kt's `if (!mailbox)` arm). -->
  {#if !mailbox}
    <p class="muted section-description">{t.settings.mail.section_description}</p>
  {/if}

  <!-- Per-credential rows. Part of the credential-management section, so the list
       renders whenever a mailbox is provisioned (email OR CalDAV), matching the
       linux lead's `credentials_group` gate. Title + empty-state mirror the linux
       lead (`CREDENTIALS_TITLE` / `CREDENTIALS_EMPTY`) and android. -->
  {#if mailbox}
  <div class="creds" data-testid={IDS.MAIL_SETTINGS_CREDENTIALS_LIST}>
    <h3 class="creds-title">{t.settings.mail.credentials_title}</h3>
    {#if (snap?.credentials ?? []).length === 0}
      <p class="muted small creds-empty">{t.settings.mail.credentials_empty}</p>
    {/if}
    {#each snap?.credentials ?? [] as c}
      <div class="cred-item" data-testid={IDS.MAIL_SETTINGS_CREDENTIAL_ITEM}>
        <span class="cred-name" data-testid={IDS.MAIL_SETTINGS_CREDENTIAL_ITEM_NAME}>{c.display_name}</span>
        <!-- Succession's compromised state (`mail-credentials.md` § Rotation and
             recovery → Succession) — the row survives so the user knows what to
             set up again, but must never read as usable. Mirrors the linux lead's
             placement: directly under the name, above the MUA username. -->
        {#if c.revoked}
          <span class="warn small" data-testid={IDS.MAIL_SETTINGS_CREDENTIAL_ITEM_REVOKED}>
            {t.settings.mail.credential_revoked}
          </span>
        {/if}
        <span class="badge" data-testid={IDS.MAIL_SETTINGS_CREDENTIAL_ITEM_TYPE}>
          {resolveLocalized(credentialKindBadge(c.kind))}
        </span>
        <span class="muted small" data-testid={IDS.MAIL_SETTINGS_CREDENTIAL_ITEM_CREATED_AT}>{c.created_at}</span>
        <span class="muted small" data-testid={IDS.MAIL_SETTINGS_CREDENTIAL_ITEM_LAST_USED_AT}>—</span>
        <button class="btn danger small" data-testid={IDS.MAIL_SETTINGS_CREDENTIAL_ITEM_REVOKE_BUTTON} onclick={() => revokeCredential(c.credential_id)}>
          {t.settings.mail.revoke}
        </button>
        <!-- The exact MUA username this credential logs in with (mail-settings.md
             § Credentials list) — copied verbatim into a third-party MUA. -->
        <div class="cred-field">
          <span class="field-label">{t.settings.mail.mua_username}</span>
          <code class="mono" data-testid={IDS.MAIL_SETTINGS_CREDENTIAL_ITEM_USERNAME}>{muaUsername(c.mua_username)}</code>
          <button class="btn small" data-testid={IDS.MAIL_SETTINGS_CREDENTIAL_ITEM_COPY_USERNAME} onclick={() => copyText(muaUsername(c.mua_username))}>
            {t.settings.mail.copy_username}
          </button>
        </div>
        <!-- The credential's secret: hidden by default; revealed on demand from
             the client's own `fauna.state.mail` entries (never in the snapshot). -->
        <div class="cred-field">
          <span class="field-label">{t.settings.mail.secret_label}</span>
          <code class="mono secret" data-testid={IDS.MAIL_SETTINGS_CREDENTIAL_ITEM_SECRET}>{revealedSecrets[c.credential_id] ?? ''}</code>
          <button class="btn small" data-testid={IDS.MAIL_SETTINGS_CREDENTIAL_ITEM_REVEAL_SECRET} onclick={() => toggleSecret(c.credential_id)}>
            {c.credential_id in revealedSecrets ? t.settings.mail.hide_secret : t.settings.mail.reveal_secret}
          </button>
          <button class="btn small" data-testid={IDS.MAIL_SETTINGS_CREDENTIAL_ITEM_COPY_SECRET} onclick={() => copyText(revealedSecrets[c.credential_id] ?? '')}>
            {t.settings.mail.copy_secret}
          </button>
        </div>
      </div>
    {/each}
  </div>
  {/if}

  <!-- Connection details (read-only; each field copyable). The block renders
       whenever a mailbox is provisioned (email OR CalDAV); PER-PROTOCOL gating
       WITHIN it (mail-settings.md § CalDAV-only mailbox;
       §2, mirroring the linux lead): the IMAP/SMTP rows on `enabled`, the CalDAV
       rows on `caldav_enabled`, and username/auth (the one shared credential)
       whenever a mailbox is provisioned. (`mailbox && snap` narrows `snap` for the
       non-optional `snap.mua` reads below.) -->
  {#if mailbox && snap}
    <div class="mua" data-testid={IDS.MAIL_SETTINGS_MUA_INSTRUCTIONS}>
      <p class="mua-title">{t.settings.mail.mua_title}</p>
      {#if snap.enabled}
        <div class="mua-row">
          <span class="field-label">{t.settings.mail.mua_imap_host}</span>
          <code class="mono" data-testid={IDS.MAIL_SETTINGS_MUA_IMAP_HOST}>{snap.mua.imap_host}</code>
        </div>
        <div class="mua-row">
          <span class="field-label">{t.settings.mail.mua_imap_port}</span>
          <code class="mono" data-testid={IDS.MAIL_SETTINGS_MUA_IMAP_PORT}>{snap.mua.imap_port}</code>
        </div>
        <div class="mua-row">
          <span class="field-label">{t.settings.mail.mua_smtp_host}</span>
          <code class="mono" data-testid={IDS.MAIL_SETTINGS_MUA_SMTP_HOST}>{snap.mua.smtp_host}</code>
        </div>
        <div class="mua-row">
          <span class="field-label">{t.settings.mail.mua_smtp_port}</span>
          <code class="mono" data-testid={IDS.MAIL_SETTINGS_MUA_SMTP_PORT}>{snap.mua.smtp_port}</code>
        </div>
      {/if}
      {#if snap.caldav_enabled}
        <!-- CalDAV server URL — the one shared credential AUTHs CalDAV too -->
        <div class="mua-row">
          <span class="field-label">{t.settings.mail.mua_caldav_host}</span>
          <code class="mono" data-testid={IDS.MAIL_SETTINGS_MUA_CALDAV_HOST}>{snap.mua.caldav_host}</code>
        </div>
        <div class="mua-row">
          <span class="field-label">{t.settings.mail.mua_caldav_port}</span>
          <code class="mono" data-testid={IDS.MAIL_SETTINGS_MUA_CALDAV_PORT}>{snap.mua.caldav_port}</code>
        </div>
      {/if}
      {#if snap.serves_webdav_set}
        <!-- WebDAV collection root — one full URL (no SRV autodiscovery exists),
             shown once the actor actually serves a folder over WebDAV. -->
        <div class="mua-row">
          <span class="field-label">{t.settings.mail.mua_webdav_url}</span>
          <code class="mono" data-testid={IDS.MAIL_SETTINGS_MUA_WEBDAV_URL}>{snap.mua.webdav_url}</code>
        </div>
      {/if}
      <div class="mua-row">
        <span class="field-label">{t.settings.mail.mua_username}</span>
        <code class="mono" data-testid={IDS.MAIL_SETTINGS_MUA_USERNAME_FORMAT}>
          {muaUsername(snap.credentials[0]?.mua_username ?? snap.mua.username_format)}
        </code>
      </div>
      <div class="mua-row">
        <span class="field-label">{t.settings.mail.mua_auth}</span>
        <code class="mono" data-testid={IDS.MAIL_SETTINGS_MUA_AUTH_MECHANISM}>{snap.mua.auth_mechanism}</code>
      </div>
    </div>
  {/if}
</section>

<style>
  .section { margin-bottom: 2rem; }
  .section h2 { margin-bottom: 0.75rem; font-size: 1.125rem; }
  .muted { color: var(--text-muted); }
  .warn { color: var(--danger); }
  .small { font-size: 0.8rem; }
  .status { margin-left: 0.75rem; font-size: 0.8rem; }
  .keys-info { display: block; margin-top: 0.5rem; max-width: 520px; line-height: 1.4; }
  .serve-here { margin-top: 0.75rem; max-width: 520px; }
  .serve-here p { margin-top: 0.375rem; line-height: 1.4; }
  .actions { display: flex; gap: 0.5rem; margin-top: 0.75rem; flex-wrap: wrap; }
  .banner {
    display: flex; align-items: center; gap: 0.75rem; margin-top: 0.75rem;
    padding: 0.5rem 0.75rem; border: 1px solid var(--accent); border-radius: 6px;
  }
  .form {
    display: flex; flex-direction: column; gap: 0.5rem; max-width: 420px;
    margin-top: 0.75rem; padding: 0.75rem; border: 1px solid var(--border);
    border-radius: 6px; background: var(--bg-surface);
  }
  .form-actions { display: flex; gap: 0.5rem; }
  .pw-row { display: flex; gap: 0.5rem; align-items: center; }
  .pw-row .input { flex: 1; }
  .exclude-row { display: flex; align-items: center; gap: 0.5rem; font-size: 0.85rem; }
  .input {
    padding: 0.5rem; border: 1px solid var(--border); border-radius: 6px;
    background: var(--bg); color: var(--text); font-size: 0.875rem;
  }
  .token { display: block; padding: 0.5rem; background: var(--bg); border-radius: 6px; word-break: break-all; }
  .mono { font-family: monospace; font-size: 0.8rem; }
  .creds { display: flex; flex-direction: column; gap: 0.5rem; margin-top: 0.75rem; }
  .cred-item {
    display: flex; align-items: center; gap: 0.5rem; padding: 0.5rem;
    border: 1px solid var(--border); border-radius: 6px; flex-wrap: wrap;
  }
  .cred-name { font-weight: 600; flex: 1; }
  .cred-field { display: flex; align-items: center; gap: 0.5rem; flex-basis: 100%; }
  .cred-field .mono { flex: 1; word-break: break-all; }
  .secret { min-height: 1rem; }
  .mua { margin-top: 1rem; display: flex; flex-direction: column; gap: 0.375rem; }
  .mua-title { font-weight: 600; margin-bottom: 0.25rem; }
  .mua-row { display: flex; gap: 0.75rem; align-items: baseline; }
  .field-label { color: var(--text-muted); font-size: 0.8rem; min-width: 5rem; }
  .badge {
    font-size: 0.75rem; padding: 0.125rem 0.5rem; border-radius: 4px;
    background: var(--bg-hover); color: var(--text-muted);
  }
  .btn {
    padding: 0.5rem 1rem; border: 1px solid var(--border); border-radius: 6px;
    background: var(--bg-surface); color: var(--text); cursor: pointer;
    font-size: 0.875rem;
  }
  .btn:hover { background: var(--bg-hover); }
  .btn.primary { background: var(--accent); color: #fff; border-color: var(--accent); }
  .btn.danger { border-color: var(--danger); color: var(--danger); }
  .btn.small { padding: 0.25rem 0.625rem; font-size: 0.8rem; }
  .btn.toggle.on { background: rgba(63, 185, 80, 0.15); border-color: var(--success, #3fb950); color: var(--success, #3fb950); }
  /* Destructive disable-mail confirmation overlay (matches the devices/folder
     delete-confirm shape). */
  .overlay {
    position: fixed; inset: 0; background: rgba(0, 0, 0, 0.6);
    display: flex; align-items: center; justify-content: center; z-index: 100;
  }
  .dialog {
    background: var(--bg-surface); border: 1px solid var(--border);
    border-radius: 8px; padding: 1.5rem; max-width: 400px; width: 90%;
  }
  .dialog p { margin-bottom: 1rem; line-height: 1.4; }
  .dialog-actions { display: flex; gap: 0.5rem; justify-content: flex-end; }
</style>
