//! Cross-language interop verifier — reads the Go-produced fixture under
//! `bins/fauna-bridges/internal/dagcbor/testdata/` and re-verifies it
//! from Rust using `fauna_cbor::{decode_strict, SignedEnvelope, Cid}`.
//!
//! This is the second half of the byte-parity proof: Task 2.9 covered
//! Rust signs → Go verifies; this file covers Go signs → Rust verifies.
//! Together they prove the load-bearing claim of
//! `docs/goal/architecture/serialization.md` § 4: any party with BLAKE3 +
//! Ed25519 + a dag-cbor decoder can verify the other's signed content,
//! independent of which language produced it.
//!
//! Fixture layout (3 files, regenerated by
//! `go test -C bins/fauna-bridges ./internal/dagcbor/ -run TestGenCrossLanguage -update`):
//!
//!   testdata/go-signed.bin           — canonical dag-cbor bytes for the demo payload.
//!   testdata/go-signed.envelope.bin  — 100 bytes: 36-byte CID || 64-byte Ed25519 sig.
//!   testdata/go-pubkey.bin           — 32 bytes: the Ed25519 verifying key.
//!
//! The Go producer uses the same seed `[7u8; 32]` and same `Demo` payload
//! as the Rust producer (`libs/fauna-cbor/examples/gen_cross_language_fixtures.rs`),
//! so the canonical bytes — and hence the CID, signature, and verifying
//! key — are byte-identical to the Rust-side fixture. The Go regen step
//! asserts that byte-parity inline. This test asserts that Rust's
//! `SignedEnvelope::verify_permissive` accepts the Go-produced envelope.

use std::fs;
use std::path::PathBuf;

use ed25519_dalek::VerifyingKey;
use fauna_cbor::{Cid, SignedEnvelope, decode_strict};
use serde::{Deserialize, Serialize};
use serde_bytes::ByteBuf;

/// Demo payload — must match the Go and Rust producers exactly. The struct
/// itself doesn't enforce the wire-byte key order (the canonical encoder
/// does); but for the decode step to succeed, the field names and types
/// must match what's on disk.
#[derive(Serialize, Deserialize, PartialEq, Debug)]
struct Demo {
    v: u32,
    name: String,
    data: ByteBuf,
}

/// Path to the Go fixture directory relative to this crate's manifest dir
/// (`libs/fauna-cbor`). The Go producer writes its testdata under
/// `bins/fauna-bridges/internal/dagcbor/testdata/`; from
/// `libs/fauna-cbor` that's `../../bins/fauna-bridges/internal/dagcbor/testdata`.
fn go_fixture_dir() -> PathBuf {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    PathBuf::from(manifest).join("../../bins/fauna-bridges/internal/dagcbor/testdata")
}

/// Reads the Go-produced fixture and runs the full verification pipeline:
///
///  1. `decode_strict::<Demo>(&bytes)` — the signed bytes are canonical
///     dag-cbor AND decode into the expected schema. Mirrors the
///     receiver's first move: parse the payload it just verified.
///  2. Reconstruct the `SignedEnvelope` from the 100-byte on-disk envelope
///     by splitting into a 36-byte `Cid` and a 64-byte signature.
///  3. `env.verify_permissive(&bytes, &pk)` — runs `blake3(bytes) == cid.multihash`
///     AND `ed25519_verify(sig, cid.bytes, pk)` (no encoder in the
///     security path).
///
/// All three steps must succeed for the load-bearing claim to hold.
#[test]
fn go_signed_verifies_in_rust() {
    let dir = go_fixture_dir();
    let signed_bytes = fs::read(dir.join("go-signed.bin")).unwrap_or_else(|e| {
        panic!(
            "read go-signed.bin: {e} (run `go test -C bins/fauna-bridges ./internal/dagcbor/ -run TestGenCrossLanguage -update` to regenerate)"
        )
    });
    let envelope_bytes =
        fs::read(dir.join("go-signed.envelope.bin")).expect("read go-signed.envelope.bin");
    let pubkey_bytes = fs::read(dir.join("go-pubkey.bin")).expect("read go-pubkey.bin");

    // Envelope shape: 36-byte CID || 64-byte sig = 100 bytes.
    assert_eq!(
        envelope_bytes.len(),
        100,
        "envelope must be 36+64 = 100 bytes, got {}",
        envelope_bytes.len()
    );
    assert_eq!(
        pubkey_bytes.len(),
        32,
        "Ed25519 public key must be 32 bytes, got {}",
        pubkey_bytes.len()
    );

    // Step 1: decode the signed bytes via the strict canonical-form path.
    // A non-canonical or schema-mismatched input fails here before any
    // crypto runs.
    let demo: Demo = decode_strict(&signed_bytes).expect("decode_strict::<Demo>(go-signed.bin)");
    assert_eq!(
        demo,
        Demo {
            v: 42,
            name: "fauna".to_string(),
            data: ByteBuf::from(vec![0x01, 0x02, 0x03, 0x04, 0x05]),
        },
        "decoded payload must match the Go producer's input"
    );

    // Step 2: reconstruct the envelope from the on-disk 100 bytes.
    let mut cid_arr = [0u8; 36];
    cid_arr.copy_from_slice(&envelope_bytes[0..36]);
    let cid = Cid::from_bytes(cid_arr).expect("CID prefix must be v1+dag-cbor+blake3-256+len32");
    let mut sig_arr = [0u8; 64];
    sig_arr.copy_from_slice(&envelope_bytes[36..100]);
    let envelope = SignedEnvelope::from_parts(cid, sig_arr);

    // Step 3: verify against the Go signer's public key. Internally this
    // runs `blake3(bytes) == cid.multihash` and `ed25519_verify(sig, cid.bytes, pk)`.
    let mut pk_arr = [0u8; 32];
    pk_arr.copy_from_slice(&pubkey_bytes);
    let pk = VerifyingKey::from_bytes(&pk_arr).expect("Ed25519 verifying key from 32 bytes");
    envelope
        .verify_permissive(&signed_bytes, &pk)
        .expect("Go-signed envelope must verify with Rust");
}
