#!/usr/bin/env -S uv run --quiet
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Generate per-platform element-id constants from tests/e2e-unified/ui.yaml.

Targets:
  - Rust:   libs/fauna-ui-ids/src/lib.rs          (shared crate — tui + linux)
  - TS:     apps/fauna-web/src/lib/generated/uiIds.ts
  - Swift:  apps/fauna-apple/FaunaKit/Sources/FaunaKit/Generated/UiIds.swift
  - Kotlin: apps/fauna-android/app/src/main/kotlin/social/fauna/generated/UiIds.kt
  - C#:     apps/fauna-windows/FaunaApp/FaunaApp/Generated/UiIds.cs
  - Python: tests/e2e-unified/generated/ui_ids.py

Owner doc: docs/goal/architecture/build-system.md § Generated element-id constants.

Three decisions a later session would otherwise re-derive:

0. **Nothing here is spelled twice.** "What ui.yaml declares" is imported from
   `scripts/lint-ui-registry.py`; how an id becomes a member name is imported from
   `scripts/ui_id_names.py`, which the two ui lints import as well so they can
   recognise a *constant reference* as an implementation once an app adopts.

1. **"What ui.yaml declares" is imported from `scripts/lint-ui-registry.py`, never
   reimplemented.** That script is the gate which decides whether an id an app renders
   is declared; a generator with its own second answer could emit a constant the gate
   rejects, or omit one it demands. One definition, so they cannot drift. The lint's
   own history is the argument: three separate id-list keys (`components:`,
   `navigation.tabs`, `children:`) were each found unwalked *after* it shipped, and a
   private copy here would have inherited exactly those blind spots and then diverged
   as they were fixed.

2. **The declared set is filtered to the element-id shape** (`KEBAB` below, the same
   class the lint uses to recognise a rendered id). `collect_declared` deliberately
   also returns top-level `pages:`/`onboarding:` block *names* — 43 of them, snake_case
   things like `feed`, `devices`, `dns_config` — because an app may render a block's
   own key as an id. Those are page names, not elements, and emitting them would both
   produce junk constants and create a real collision: the onboarding page
   `launch_instance_chooser` and the registry element `launch-instance-chooser` derive
   the same `LAUNCH_INSTANCE_CHOOSER`. The shape filter drops the page names and the
   collision together, on a rule rather than an exception list.

3. **No per-constant doc comments** (the registry rows carry `type` + `description`).
   The id name is the documentation, and 1567 free-text descriptions round-tripped
   through six languages' string-literal rules is escaping risk bought for very little.
   ui.yaml stays the place to read what an id means.

Derived member names are checked for collisions in every language *before* anything is
written: two ids that differ only where a separator was (`a-b_c` vs `a-b-c`) would
silently collapse into one constant, so a collision is a hard error naming both ids.
Reserved words are escaped rather than assumed absent — none collide today across 1604
ids, and a future id must not be the thing that discovers that.

Per-file byte comparison before writing is load-bearing, not boilerplate: the Rust
target lands inside `libs/`, which every `wasm-<name>` build gate keys on by mtime, so
rewriting an unchanged file would silently mark all of them stale
(build-system.md § How the gate works).

Gated features (2026-08-17)
---------------------------

ui.yaml's `gated_features:` block says which ids belong to a controversial-class feature
(`docs/goal/architecture/dynamic-features.md` § The gated-feature registry). A store-safe
artifact must not carry those ids **structurally** — criterion 1 of § What "completely
compiled away" means — and an unqualified table of every id is exactly the structural
carry that criterion forbids. So each target emits its gated families behind that
family's own compile condition, which differs per platform family and, for two targets,
does not exist at all. `GATED_EMISSION` below is that per-target answer, with the reason
recorded on every entry — including the two that deliberately emit nothing special,
because "this target needs no gate" is a claim about the language and it must be
readable, not inferred from an absence.
"""
from __future__ import annotations

import argparse
import importlib.util
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
LINT = ROOT / "scripts" / "lint-ui-registry.py"

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from ui_id_names import KEBAB, camel, pascal, scream  # noqa: E402

BANNER = "Generated by scripts/ui-ids-generate.py from tests/e2e-unified/ui.yaml. DO NOT EDIT."

# Escaped rather than assumed absent — see module docstring.
SWIFT_KEYWORDS = {
    "as", "associatedtype", "any", "break", "case", "catch", "class", "continue",
    "default", "defer", "deinit", "do", "else", "enum", "extension", "fallthrough",
    "false", "fileprivate", "for", "func", "guard", "if", "import", "in", "init",
    "inout", "internal", "is", "let", "nil", "open", "operator", "precedencegroup",
    "private", "protocol", "public", "repeat", "rethrows", "return", "self", "some",
    "static", "struct", "subscript", "super", "switch", "throw", "throws", "true",
    "try", "typealias", "var", "where", "while",
}
KOTLIN_KEYWORDS = {
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if",
    "in", "interface", "is", "null", "object", "package", "return", "super", "this",
    "throw", "true", "try", "typealias", "typeof", "val", "var", "when", "while",
}
CSHARP_KEYWORDS = {
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
    "checked", "class", "const", "continue", "decimal", "default", "delegate", "do",
    "double", "else", "enum", "event", "explicit", "extern", "false", "finally",
    "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int",
    "interface", "internal", "is", "lock", "long", "namespace", "new", "null",
    "object", "operator", "out", "override", "params", "private", "protected",
    "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof",
    "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
    "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
    "virtual", "void", "volatile", "while",
}


def load_ui_doc() -> dict:
    """ui.yaml, parsed by the lint's own loader — never a second parse of our own."""
    spec = importlib.util.spec_from_file_location("lint_ui_registry", LINT)
    lint = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(lint)
    doc, _ = lint.load_ui(ROOT)
    registry = doc.get("elements") or {}
    doc["__declared__"] = lint.collect_declared(doc, registry, lint.collect_referenced(doc))
    return doc


def load_ids(doc: dict) -> list[str]:
    """Every element id ui.yaml declares, sorted — the lint's answer, shape-filtered."""
    return sorted(i for i in doc["__declared__"] if KEBAB.fullmatch(i))


def load_gated(doc: dict, ids: list[str]) -> dict[str, list[str]]:
    """`feature key -> its ids`, resolved from ui.yaml's `gated_features:` prefixes.

    Vacuity is a hard error, not a warning: a prefix matching nothing means either the
    ids were renamed or the block rotted, and in both cases every store-safe witness
    downstream of it would go quietly green while covering less than it claims. That is
    the exact failure the artifact witnesses' second column exists to prevent, applied
    one level earlier.
    """
    gated: dict[str, list[str]] = {}
    for key, spec in (doc.get("gated_features") or {}).items():
        prefixes = (spec or {}).get("id_prefixes") or []
        if not prefixes:
            raise SystemExit(
                f"ui-ids-generate: gated_features.{key} declares no `id_prefixes`. "
                f"Remove the member or give it the prefixes it paints."
            )
        members: list[str] = []
        for prefix in prefixes:
            hits = [i for i in ids if i.startswith(prefix)]
            if not hits:
                raise SystemExit(
                    f"ui-ids-generate: gated_features.{key} declares the prefix "
                    f"'{prefix}', which matches no declared element id. Either the ids "
                    f"were renamed (fix the prefix) or the surface is gone (drop it) — "
                    f"a prefix matching nothing makes every store-safe witness that "
                    f"reads this block vacuous."
                )
            members.extend(hits)
        gated[key] = sorted(set(members))

    owner: dict[str, str] = {}
    for key, members in gated.items():
        for element_id in members:
            if element_id in owner:
                raise SystemExit(
                    f"ui-ids-generate: '{element_id}' is claimed by two gated features "
                    f"('{owner[element_id]}' and '{key}'). A gated id belongs to exactly "
                    f"one member — a subset member (zaps ⊂ payments) rides its "
                    f"superset's prefixes rather than repeating them."
                )
            owner[element_id] = key
    return gated


def check_collisions(ids: list[str]) -> None:
    """Hard-fail if any language's member names are not unique. See module docstring."""
    for label, derive in (("SCREAMING_SNAKE", scream), ("camelCase", camel), ("PascalCase", pascal)):
        seen: dict[str, str] = {}
        for element_id in ids:
            name = derive(element_id)
            if name in seen:
                raise SystemExit(
                    f"ui-ids-generate: {label} collision — ui.yaml declares both "
                    f"'{seen[name]}' and '{element_id}', which both derive '{name}'. "
                    f"Rename one in ui.yaml (rule A) before regenerating."
                )
            seen[name] = element_id


# Which registry members each target can excise, and HOW — one line per (target,
# member) pair that this target expresses, and a recorded reason for every pair it
# does not. A member absent from a target's map is emitted in the ordinary table.
#
# ⚠ The reasons are not commentary. "This target needs no gate" is a claim about the
# language, and the two targets making it (rust, python) are the two where a reader
# would otherwise assume an oversight; the one that CANNOT make it (kotlin) is a live
# residual with an owning row, and burying it in an absence is how a residual stops
# being tracked.
GATED_EMISSION: dict[str, dict[str, str]] = {
    # `pub const` is a compile-time value: an unreferenced one emits no symbol and no
    # bytes, so a store-safe tui/linux binary cannot carry an id whose only users are
    # its gated renders. Measured on tui POST-adoption — `tui-store-safe-check` green
    # 2026-08-17 18:43 against a tree already carrying tui's ~1751 constant
    # references. ⚠ linux still spells its ids as literals, so its column is not yet
    # evidence about this crate; see dynamic-features.md § Which element IDs belong
    # to a gated feature, rust row.
    "rust": {},
    # Never shipped in any artifact — it is the e2e harness's own copy.
    "python": {},
    # A Swift compilation condition, and the family's is NEGATIVE by toolchain
    # necessity (dynamic-features.md § Platform-family surface excision). The gated
    # members ride an `extension Ids`, so every call site keeps the same spelling and
    # a store-safe build turns a payments render that forgot its own `#if` into a
    # compile error rather than a shipped id.
    # `zaps` rides the SAME condition, and that is the subset relation rather than a
    # shortcut: ui.yaml's `gated_features:` declares it a subset member of `payments`,
    # and apple's store-safe FFI is `--no-default-features --features store-safe`, so it
    # drops the `zaps` cargo feature with the `payments` one — a store-safe
    # `FaunaFFI.xcframework` exports no `FfiZapSignerEntry` at all. Excising `zaps`
    # ALONE (the Damus hatch) is not expressible on apple and does not need to be: the
    # family has one artifact flavor. Landed with the gating of the renders that paint
    # these ids (2026-08-28) — before that the ids shipped in the ordinary table while
    # `FaunaKit`'s zap-signer surface did not even compile in the store-safe flavor.
    # `p2p-share` is NOT a subset of `payments`, so it takes a condition of its own —
    # the one-condition-per-registry-member rule (dynamic-features.md § Platform-family
    # surface excision). Every store-safe Swift invocation passes both conditions.
    # Landed with the gating of the plane's and the ceremony's renders (2026-09-26).
    "swift": {
        "payments": "FAUNA_EXCISE_PAYMENTS",
        "zaps": "FAUNA_EXCISE_PAYMENTS",
        "p2p-share": "FAUNA_EXCISE_P2P_SHARE",
    },
    # Folding `__FAUNA_PAYMENTS__` to false does NOT unlink a module, so web's
    # mechanism is module isolation: the gated members move into the payments render
    # directory, which ships only when something behind the condition imports it.
    "ts": {"payments": "apps/fauna-web/src/lib/components/payments/generatedIds.ts"},
    # ⚠ RESIDUAL — android cannot express this today. Kotlin has no compile-time
    # exclusion, and the source-set split that carries the GLUE cannot carry the ids:
    # android's payments *renders* stay in shared Compose behind `BuildConfig.PAYMENTS`
    # (dynamic-features.md § Platform-family surface excision), so a shared render
    # referencing a payments id would not typecheck if the constant lived only in the
    # `payments` source set, and a `noPayments` twin would put the strings straight
    # back. What stands between the table and the artifact is R8 — the half that
    # section itself says to distrust — and the only thing that can settle it is
    # `just android-store-safe-check` scanning `classes*.dex`.
    "kotlin": {},
    # A C# `#define`, and windows' is POSITIVE and default-ON — the ordinary rule
    # (dynamic-features.md § Platform-family surface excision); apple's negative
    # condition is the exception SwiftPM forces, and MSBuild has no such limit.
    # The gated members ride a second `partial class Ids` half, so every call site
    # keeps the same spelling and a store-safe build turns a payments render that
    # forgot its own `#if` into a compile error rather than a shipped id — the same
    # property Swift's `extension Ids` buys. This is NOT belt-and-braces on C#: a
    # `const string` is stored in the assembly's `Constant` metadata table whether
    # or not anything reads it, so an ungated table ships every payments id in the
    # store-safe artifact by itself.
    # `zaps` rides the SAME condition as `payments` for the identical subset-relation
    # reason as the swift row above: windows' store-safe FFI is `--no-default-features
    # --features store-safe`, which drops `zaps` with `payments`, so a store-safe
    # `fauna_ffi.dll`'s generated C# face has no `FfiZapSignerEntry`/
    # `FfiNostrZapSignerClient` at all. Landed with the gating of the render that
    # paints these ids (windows' zap-signer leg) — before that the ids shipped in the
    # ordinary table while the render did not even compile in the store-safe flavor.
    # `p2p-share` is NOT a subset of `payments`, so it takes a define of its own
    # (`P2P_SHARE`, the one-condition-per-registry-member rule, as the swift row).
    # Landed with the gating of the ceremony render that paints these ids (windows'
    # offline-share leg: Views\P2pShare\ + its `#if P2P_SHARE` glue); windows
    # renders no plane half, so those two prefixes ride the table alone.
    "csharp": {"payments": "PAYMENTS", "zaps": "PAYMENTS", "p2p-share": "P2P_SHARE"},
}


def check_emission(gated: dict[str, list[str]]) -> None:
    """Every member a target claims to gate must be one ui.yaml actually declares.

    Without this the failure is SILENT and in the dangerous direction: a member
    renamed in the catalog (or dropped) leaves `GATED_EMISSION` naming a key that
    resolves to no group, `_split` excises nothing, and every target quietly goes
    back to emitting the plane's ids in the ordinary table — with the gated block
    simply absent rather than empty, so nothing looks wrong.
    """
    for target, members in GATED_EMISSION.items():
        for key in members:
            if key not in gated:
                raise SystemExit(
                    f"ui-ids-generate: target '{target}' claims to gate '{key}', which "
                    f"ui.yaml's `gated_features:` block does not declare. Either the "
                    f"member was renamed (fix GATED_EMISSION) or the catalog lost it "
                    f"(fix ui.yaml) — as written, {target} would emit that plane's ids "
                    f"in the ordinary table with no gated block at all."
                )


def _split(ids: list[str], gated: dict[str, list[str]], target: str) -> tuple[list[str], dict]:
    """`(ids that stay in the ordinary table, the groups this target gates)`."""
    groups = {key: members for key, members in gated.items() if key in GATED_EMISSION[target]}
    excised = {i for members in groups.values() for i in members}
    return [i for i in ids if i not in excised], groups


def emit_rust(ids: list[str], gated: dict[str, list[str]]) -> list[tuple[str, str]]:
    plain, _ = _split(ids, gated, "rust")
    out = [
        f"// {BANNER}",
        "//!",
        "//! Element-id constants shared by the Rust apps (tui, linux). Ids are not i18n:",
        "//! they are the automation contract `tests/e2e-unified/ui.yaml` declares, so they",
        "//! live here rather than in `fauna_i18n`.",
        "//!",
        "//! Gated-feature ids are NOT split out here, and that is deliberate: an",
        "//! unreferenced `pub const` emits nothing, so a store-safe binary cannot carry",
        "//! one (scripts/ui-ids-generate.py § GATED_EMISSION).",
        "",
        "/// Number of element ids ui.yaml declares.",
        f"pub const COUNT: usize = {len(plain)};",
        "",
    ]
    for element_id in plain:
        out.append(f'pub const {scream(element_id)}: &str = "{element_id}";')
    out.append("")
    return [(TARGET_PATHS["rust"], "\n".join(out))]


def emit_ts(ids: list[str], gated: dict[str, list[str]]) -> list[tuple[str, str]]:
    plain, groups = _split(ids, gated, "ts")
    out = [f"// {BANNER}", "", "export const IDS = {"]
    for element_id in plain:
        out.append(f"  {scream(element_id)}: '{element_id}',")
    out += ["} as const;", "", "export type ElementId = (typeof IDS)[keyof typeof IDS];", ""]
    files = [(TARGET_PATHS["ts"], "\n".join(out))]

    for key, members in groups.items():
        const = scream(key) + "_IDS"
        gate = [
            f"// {BANNER}",
            "//",
            f"// The `{key}` plane's element ids, in the isolated render directory rather",
            "// than in the shared table: folding the build condition to false does not",
            "// unlink a module, so a shared table would ship these ids in every flavor",
            "// (dynamic-features.md § What \"completely compiled away\" means, criterion 1).",
            "// Import this ONLY from behind `__FAUNA_PAYMENTS__`.",
            "",
            f"export const {const} = {{",
        ]
        for element_id in members:
            gate.append(f"  {scream(element_id)}: '{element_id}',")
        gate += [
            "} as const;",
            "",
            f"export type {pascal(key)}ElementId = (typeof {const})[keyof typeof {const}];",
            "",
        ]
        files.append((GATED_EMISSION["ts"][key], "\n".join(gate)))
    return files


def emit_swift(ids: list[str], gated: dict[str, list[str]]) -> list[tuple[str, str]]:
    plain, groups = _split(ids, gated, "swift")

    def member(element_id: str) -> str:
        name = camel(element_id)
        if name in SWIFT_KEYWORDS:
            name = f"`{name}`"
        return f'    public static let {name} = "{element_id}"'

    out = [f"// {BANNER}", "", "public enum Ids {"]
    out += [member(i) for i in plain]
    out += ["}"]
    for key, members in groups.items():
        condition = GATED_EMISSION["swift"][key]
        out += [
            "",
            f"// The `{key}` plane's element ids. A store-safe build must not carry them at",
            "// all — not as unreferenced `public` API a linker may or may not strip",
            "// (dynamic-features.md § What \"completely compiled away\" means, criterion 1).",
            f"#if !{condition}",
            "extension Ids {",
        ]
        out += [member(i) for i in members]
        out += ["}", "#endif"]
    out += [""]
    return [(TARGET_PATHS["swift"], "\n".join(out))]


def emit_kotlin(ids: list[str], gated: dict[str, list[str]]) -> list[tuple[str, str]]:
    plain, _ = _split(ids, gated, "kotlin")
    out = [
        f"// {BANNER}",
        "//",
        "// ⚠ Gated-feature ids are NOT split out here — Kotlin has no compile-time",
        "// exclusion and android's payments renders are shared Compose behind",
        "// `BuildConfig.PAYMENTS`, so R8 is what must remove them from `classes*.dex`.",
        "// See scripts/ui-ids-generate.py § GATED_EMISSION.",
        "package social.fauna.generated",
        "",
        "object Ids {",
    ]
    for element_id in plain:
        name = scream(element_id)
        if name in KOTLIN_KEYWORDS:
            name = f"`{name}`"
        out.append(f'    const val {name} = "{element_id}"')
    out += ["}", ""]
    return [(TARGET_PATHS["kotlin"], "\n".join(out))]


def emit_csharp(ids: list[str], gated: dict[str, list[str]]) -> list[tuple[str, str]]:
    # Namespace and class name are fixed by build-system.md § Generated element-id
    # constants, whose XAML shape (`xmlns:ids="using:FaunaApp.UiIds"`,
    # `{x:Bind ids:Ids.PageHeading}`) was proven on Windows. `const` over a static
    # property is the doc's stated preference — it is what the other five emit.
    #
    # `partial` costs nothing today and is what lets the shell excision move the
    # gated members into a `#if PAYMENTS` half without touching one call site.
    plain, groups = _split(ids, gated, "csharp")

    def member(element_id: str) -> str:
        name = pascal(element_id)
        if name in CSHARP_KEYWORDS:
            name = f"@{name}"
        return f'    public const string {name} = "{element_id}";'

    out = [
        f"// {BANNER}",
        "//",
        "// Gated-feature ids ride a second `partial class Ids` half behind their",
        "// family's compile condition (scripts/ui-ids-generate.py § GATED_EMISSION).",
        "// A C# `const string` lives in the assembly's `Constant` metadata table",
        "// whether or not anything reads it, so an ungated table would ship every",
        "// gated id in the store-safe artifact on its own — dynamic-features.md",
        '// § What "completely compiled away" means, criterion 1.',
        "namespace FaunaApp.UiIds;",
        "",
        "public static partial class Ids",
        "{",
    ]
    out += [member(i) for i in plain]
    out += ["}"]
    for key, members in groups.items():
        condition = GATED_EMISSION["csharp"][key]
        out += [
            "",
            f"// The `{key}` plane's element ids. A store-safe build must not carry them at",
            "// all, not even as unreferenced constants nothing reads: see the header above.",
            "// The half keeps every call site's spelling, so a render that forgets its own",
            f"// `#if {condition}` becomes a compile error instead of a shipped id.",
            f"#if {condition}",
            "public static partial class Ids",
            "{",
        ]
        out += [member(i) for i in members]
        out += ["}", "#endif"]
    out += [""]
    return [(TARGET_PATHS["csharp"], "\n".join(out))]


def emit_python(ids: list[str], gated: dict[str, list[str]]) -> list[tuple[str, str]]:
    plain, _ = _split(ids, gated, "python")
    out = [f"# {BANNER}", "", f"COUNT = {len(plain)}", ""]
    for element_id in plain:
        out.append(f'{scream(element_id)} = "{element_id}"')
    out.append("")
    return [(TARGET_PATHS["python"], "\n".join(out))]


TARGET_PATHS = {
    "rust": "libs/fauna-ui-ids/src/lib.rs",
    "ts": "apps/fauna-web/src/lib/generated/uiIds.ts",
    "swift": "apps/fauna-apple/FaunaKit/Sources/FaunaKit/Generated/UiIds.swift",
    "kotlin": "apps/fauna-android/app/src/main/kotlin/social/fauna/generated/UiIds.kt",
    "csharp": "apps/fauna-windows/FaunaApp/FaunaApp/Generated/UiIds.cs",
    "python": "tests/e2e-unified/generated/ui_ids.py",
}

TARGETS = {
    "rust": emit_rust,
    "ts": emit_ts,
    "swift": emit_swift,
    "kotlin": emit_kotlin,
    "csharp": emit_csharp,
    "python": emit_python,
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate element-id constants from ui.yaml")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated files are up-to-date (exit 1 if not)",
    )
    args = parser.parse_args()

    doc = load_ui_doc()
    ids = load_ids(doc)
    check_collisions(ids)
    gated = load_gated(doc, ids)
    check_emission(gated)

    all_ok = True
    for target, emit in TARGETS.items():
        for path, content in emit(ids, gated):
            out = ROOT / path
            if args.check:
                if not out.exists():
                    print(f"MISSING: {path}")
                    all_ok = False
                elif out.read_text() != content:
                    print(f"OUT-OF-DATE: {path}")
                    all_ok = False
                else:
                    print(f"OK: {path}")
                continue
            out.parent.mkdir(parents=True, exist_ok=True)
            # Byte comparison before writing — see module docstring.
            if out.exists() and out.read_text() == content:
                print(f"unchanged {path}")
            else:
                out.write_text(content)
                print(f"wrote {path}")
    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
