//! CI entry point for the additive-only struct-evolution gate.
//!
//! Diffs the working tree against a base commit (the same model as
//! `scripts/check-cddl-evolution.py`: HEAD shapes read from disk, base shapes
//! from `git show <base>:<path>`) and fails on any non-additive change to a
//! tracked struct. Wired into CI's `protocol-checks` job and, via `--base`,
//! into the async dev-fleet merge-gate check.
//!
//! The base defaults to `merge-base(HEAD, origin/main)` — meaningful when run
//! from a feature branch ahead of `origin/main` (`just
//! additive-evolution-check` before a merge). Pass `--base <rev>` to override
//! it explicitly: `merge-gate-check.sh` builds in a tree pinned at the tip
//! under test, where HEAD *is* `origin/main`, so the default would diff that
//! tree against itself and report zero violations unconditionally — it passes
//! the previous verified-green tip instead
//! (`docs/goal/architecture/merge-gate-check.md` § Merge-gate check).
//!
//! Exit codes: 0 = clean, 1 = violations, 2 = tool/config error (e.g. no
//! `origin/main` to diff against — run after `git fetch origin main` — or a
//! malformed `--base`).
//!
//! `--update-catch-all-baseline` is a separate mode (needs no `--base`):
//! regenerates [`CATCH_ALL_BASELINE_PATH`] from the current working tree. See
//! that constant's doc.
//!
//! Enums ([`check_additive_evolution::enums`]) are held against
//! [`ENUM_LEDGER_PATH`] across every crate [`enum_crates`] finds; the pass
//! banner counts the ledger's `owed-` lines, and `--no-owed` fails on any —
//! an `owed-` line is a debt, and none may land on main.

use std::collections::BTreeSet;
use std::path::Path;
use std::process::{Command, ExitCode};

use check_additive_evolution::enums::{
    EnumLedger, EnumMap, EnumScan, check_enum_ledger, check_no_owed, diff_enum_maps,
    parse_enum_ledger,
};
use check_additive_evolution::{
    RatifiedBreaks, StructMap, StructScan, Violation, check_catch_all_violations,
    check_ratified_breaks_monotonic, diff_struct_maps_allowing, parse_catch_all_baseline,
    parse_ratified_breaks,
};

/// A crate whose serde structs are part of the frozen compatibility surface.
struct CrateSpec {
    /// Source root, relative to the repo root (the gate's cwd).
    root: &'static str,
    /// Run the catch-all state check (wire crate only — at-rest types use
    /// per-field `#[serde(default)]`, not a flatten catch-all).
    check_catch_all: bool,
    /// Why this crate is in scope (printed in the pass banner for cold-readers).
    note: &'static str,
}

/// The committed grandfather baseline for the rule-4 catch-all check
/// (`check_catch_all_violations`): struct keys exempt from needing the
/// catch-all, one `module::Struct` per line. Regenerated by
/// `--update-catch-all-baseline`, which only ever SHRINKS it — a struct
/// drops out once it carries the catch-all or stops deriving `Deserialize`;
/// the mode REFUSES to add an entry, so a genuinely new violation must be
/// fixed rather than silently grandfathered in: a blanket per-module skip was the failure mode this baseline
/// exists to avoid — the file lists exact keys, so an admin-mail struct
/// transport.md:2225's who-decodes ruling pulled under the rule cannot hide
/// in a `bridge_routing`-wide exemption.
const CATCH_ALL_BASELINE_PATH: &str = "tools/check-additive-evolution/catch_all_baseline.txt";

/// The user-ratified in-place breaks both evolution gates honour (`rust`
/// entries here, `cddl` entries in `scripts/check-cddl-evolution.py`).
const RATIFIED_BREAKS_PATH: &str = "libs/fauna-protocol/schemas/ratified-breaks.txt";

/// Every deserializable enum's rule-3 answer (transport.md § Schema and
/// forward-compat discipline → *Rule 3 in full*; grammar in its header).
const ENUM_LEDGER_PATH: &str = "tools/check-additive-evolution/enum_ledger.txt";

/// Where the enum scan looks for crates: every child of `parent` whose name
/// starts with `prefix`, plus the Rust apps by path. The `fauna-` prefix
/// leaves out the vendored `libs/ksni` and `libs/uniffi-bindgen-cs`; a child
/// with no `[package]` in a `Cargo.toml` (the Go mail bridge) is no crate.
/// Each crate's `src/` tree is scanned.
const ENUM_SCOPE: &[(&str, &str)] = &[("libs", "fauna-"), ("bins", "")];
const ENUM_SCOPE_APPS: &[&str] = &["apps/fauna-tui", "apps/fauna-linux"];

const CATCH_ALL_BASELINE_HEADER: &str = r#"# Committed grandfather baseline for tools/check-additive-evolution's rule-4
# catch-all check (transport.md § Schema and forward-compat discipline).
#
# Struct keys here are exempt from needing the `#[serde(flatten)] extra`
# catch-all. Four categories, NOT two — this list is regenerated mechanically
# (below) and so absorbs anything violating the rule at generation time
# regardless of category, which is exactly the silent-grandfather failure
# mode a verify-back
# warned about; each entry outside the first two categories needs its OWN
# doc comment on the struct explaining which of the other two applies, or
# it is an open gap, not a documented exemption:
#   1. The 2026-06-15 sweep's pre-existing exclusions.
#   2. bridge_routing's version-locked, in-image (bridge-decoded) structs.
#      NOT the module's app-callable admin-mail kinds — the 2026-08-27
#      who-decodes ruling (transport.md:2225) pulled those under the
#      catch-all rule, and they already carry it in code, so they never
#      appear here.
#   3. The tagged-union `Unknown` fallback itself (rule 3) — not a growable
#      payload struct, so rule 4's protection is inapplicable by definition.
#   4. Whole-struct canonical-signed cryptographic statements, where the
#      signature covers the full serde encoding (e.g. `nest_rotation::*`,
#      `merge_policy::LwwStamp`) — a flatten field would change signed bytes;
#      evolution goes through a new domain-separation tag instead.
#
# Regenerate with `cargo run -p check-additive-evolution -- --update-catch-all-baseline`
# — it only ever SHRINKS this file (a struct drops out once it carries the
# catch-all or stops deriving Deserialize); it REFUSES to add an entry, so a
# genuinely new violation must be fixed, not silently grandfathered in.
"#;

const CRATES: &[CrateSpec] = &[
    CrateSpec {
        root: "libs/fauna-protocol/src",
        check_catch_all: true,
        note: "client↔nest↔nest wire payloads",
    },
    CrateSpec {
        root: "libs/fauna-segment-store/src",
        check_catch_all: false,
        note: "at-rest segment-store types (Manifest / SegmentSidecar / KindManifest)",
    },
    CrateSpec {
        root: "libs/fauna-core/src",
        check_catch_all: false,
        note: "FFI-crossing and at-rest strict types",
    },
];

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.iter().any(|a| a == "--update-catch-all-baseline") {
        return update_catch_all_baseline();
    }

    let base = match resolve_base(args.into_iter()) {
        Ok(b) => b,
        Err(e) => {
            eprintln!("error: {e}");
            return ExitCode::from(2);
        }
    };

    let ratified = match load_ratified_breaks() {
        Ok(r) => r,
        Err(e) => {
            eprintln!("error: {RATIFIED_BREAKS_PATH}: {e}");
            return ExitCode::from(2);
        }
    };
    let base_ratified = match load_base_ratified_breaks(&base) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("error: {RATIFIED_BREAKS_PATH} at merge base: {e}");
            return ExitCode::from(2);
        }
    };
    // The list only grows: a head whose own-gate entries drop one the merge
    // base carried is refused here, independently of whether the dropped
    // name is also revived (see `check_ratified_breaks_monotonic`'s doc).
    let mut violations = check_ratified_breaks_monotonic(&base_ratified, &ratified);
    let no_owed = std::env::args().any(|a| a == "--no-owed");
    let ledger = match std::fs::read_to_string(ENUM_LEDGER_PATH) {
        Ok(text) => parse_enum_ledger(&text),
        Err(_) => Ok(EnumLedger::default()),
    };
    let base_ledger = git_show(&base, ENUM_LEDGER_PATH)
        .map(|text| parse_enum_ledger(&text))
        .unwrap_or_else(|| Ok(EnumLedger::default()));
    let (ledger, base_ledger) = match (ledger, base_ledger) {
        (Ok(h), Ok(b)) => (h, b),
        (Err(e), _) => {
            eprintln!("error: {ENUM_LEDGER_PATH}: {e}");
            return ExitCode::from(2);
        }
        (_, Err(e)) => {
            eprintln!("error: {ENUM_LEDGER_PATH} at merge base: {e}");
            return ExitCode::from(2);
        }
    };
    let crates = enum_crates();
    let head_enums = build_head_enum_map(&crates);
    let base_enums = build_base_enum_map(&base, &crates);
    violations.extend(check_enum_ledger(&head_enums, &ledger));
    violations.extend(diff_enum_maps(
        &base_enums,
        &head_enums,
        &base_ledger,
        &ledger,
        &ratified,
    ));
    if no_owed {
        violations.extend(check_no_owed(&ledger));
    }
    for spec in CRATES {
        if !Path::new(spec.root).is_dir() {
            eprintln!("warn: {} does not exist; skipping", spec.root);
            continue;
        }
        let head = build_head_map(spec.root);
        let base_map = build_base_map(&base, spec.root);
        violations.extend(diff_struct_maps_allowing(&base_map, &head, &ratified));
        if spec.check_catch_all {
            violations.extend(check_catch_all_violations(
                &head,
                &load_catch_all_baseline(),
            ));
        }
    }

    if violations.is_empty() {
        println!("Additive-evolution check passed.");
        for spec in CRATES {
            println!("  scanned {} ({})", spec.root, spec.note);
        }
        println!(
            "  scanned {} deserializable enum(s) in {} crate(s) against {ENUM_LEDGER_PATH}",
            head_enums.len(),
            crates.len()
        );
        print_owed(&ledger);
        if !ratified.is_empty() {
            println!(
                "  honouring {} ratified in-place break(s) from {RATIFIED_BREAKS_PATH}",
                ratified.len()
            );
        }
        return ExitCode::SUCCESS;
    }

    report(&violations);
    ExitCode::from(1)
}

fn report(violations: &[Violation]) {
    eprintln!("Additive-evolution violations (within a major version):");
    for v in violations {
        eprintln!("  {}: {}", v.key, v.message);
    }
    eprintln!();
    eprintln!("Allowed: add a field (optional or required), add a struct, rename/move a struct.");
    eprintln!("Blocked: remove/rename/retype a wire field, tighten optional -> required.");
    eprintln!("For a breaking change: introduce a `.v2` kind alongside the old one at a major");
    eprintln!("bump (version-compatibility.md I3 / transport.md § forward-compat discipline).");
    eprintln!(
        "A user-ratified in-place break is listed in {RATIFIED_BREAKS_PATH} (version-compatibility.md"
    );
    eprintln!("§ Dimension 2) — never by a session's own call.");
    eprintln!(
        "Enums: every deserializable enum has its rule-3 answer in {ENUM_LEDGER_PATH}; a removed"
    );
    eprintln!(
        "variant is blocked like a removed field; a variant added to an enum closed by design"
    );
    eprintln!("needs its ledger line changed in the same change (transport.md § Rule 3 in full).");
}

/// The ledger's `owed-` debt, counted by answer — printed on every pass so the
/// count stays in sight (`--no-owed` turns each line into a finding).
fn print_owed(ledger: &EnumLedger) {
    let owed = ledger.owed();
    if owed.is_empty() {
        println!("  {ENUM_LEDGER_PATH}: no `owed-` lines");
        return;
    }
    let mut by_answer = std::collections::BTreeMap::<&str, usize>::new();
    for (_, answer) in &owed {
        *by_answer.entry(answer.as_str()).or_default() += 1;
    }
    let parts: Vec<String> = by_answer.iter().map(|(a, n)| format!("{n} {a}")).collect();
    println!(
        "  {ENUM_LEDGER_PATH}: {} `owed-` line(s) ({}) — a debt: none may land on main \
         (`--no-owed` fails on them)",
        owed.len(),
        parts.join(", ")
    );
}

fn load_ratified_breaks() -> Result<RatifiedBreaks, String> {
    match std::fs::read_to_string(RATIFIED_BREAKS_PATH) {
        Ok(text) => parse_ratified_breaks(&text),
        Err(_) => Ok(RatifiedBreaks::new()),
    }
}

/// [`load_ratified_breaks`]'s twin for the merge base: the allowlist as it
/// stood before this change, read via `git show` rather than the working
/// tree. Absent at the base (a pre-allowlist commit, or a base predating the
/// file) reads as empty — nothing to have dropped — same as a missing
/// working-tree file does for HEAD.
fn load_base_ratified_breaks(base: &str) -> Result<RatifiedBreaks, String> {
    match git_show(base, RATIFIED_BREAKS_PATH) {
        Some(text) => parse_ratified_breaks(&text),
        None => Ok(RatifiedBreaks::new()),
    }
}

// ── catch-all baseline ───────────────────────────────────────────────────

fn load_catch_all_baseline() -> BTreeSet<String> {
    match std::fs::read_to_string(CATCH_ALL_BASELINE_PATH) {
        Ok(text) => parse_catch_all_baseline(&text),
        Err(_) => BTreeSet::new(),
    }
}

/// Regenerate [`CATCH_ALL_BASELINE_PATH`] from the current working tree.
/// Every violation `check_catch_all_violations` reports against an EMPTY
/// baseline becomes an entry — but this mode REFUSES to add any key not
/// already in the existing committed baseline: a down-only ratchet, the same
/// shape as `scripts/check_app_gate_ratchet.py --update-baseline`. A struct
/// leaves the baseline once it's fixed (gains the catch-all, or stops
/// deriving `Deserialize`); nothing new is ever silently grandfathered in —
/// a genuine new violation must be fixed in code, or the addition argued for
/// and made by hand in the same commit as the code that needs it.
fn update_catch_all_baseline() -> ExitCode {
    let Some(spec) = CRATES.iter().find(|s| s.check_catch_all) else {
        eprintln!("error: no CrateSpec has check_catch_all set — nothing to baseline");
        return ExitCode::from(2);
    };
    let head = build_head_map(spec.root);
    let mut keys: Vec<String> = check_catch_all_violations(&head, &BTreeSet::new())
        .into_iter()
        .map(|v| v.key)
        .collect();
    keys.sort();
    keys.dedup();

    let existing = load_catch_all_baseline();
    let widened: Vec<&String> = keys.iter().filter(|k| !existing.contains(*k)).collect();
    if !existing.is_empty() && !widened.is_empty() {
        eprintln!(
            "error: --update-catch-all-baseline would ADD {} struct(s) not already in the \
             committed baseline. This mode only ever shrinks it as violations get fixed —",
            widened.len()
        );
        eprintln!("       add the catch-all to the struct(s) below, or edit the baseline by hand");
        eprintln!("       with a reason, in the same commit as whatever introduced them:");
        for k in &widened {
            eprintln!("  - {k}");
        }
        return ExitCode::from(2);
    }

    let mut out = CATCH_ALL_BASELINE_HEADER.to_string();
    for k in &keys {
        out.push_str(k);
        out.push('\n');
    }
    if let Err(e) = std::fs::write(CATCH_ALL_BASELINE_PATH, &out) {
        eprintln!("error: failed to write {CATCH_ALL_BASELINE_PATH}: {e}");
        return ExitCode::from(2);
    }
    println!(
        "wrote {} struct key(s) to {CATCH_ALL_BASELINE_PATH} — commit it alongside your fix.",
        keys.len()
    );
    ExitCode::SUCCESS
}

// ── base resolution ──────────────────────────────────────────────────────

/// The base commit to diff HEAD against: an explicit `--base <rev>` /
/// `--base=<rev>` wins, else fall back to `merge-base(HEAD, origin/main)`.
fn resolve_base(args: impl Iterator<Item = String>) -> Result<String, String> {
    match explicit_base_arg(args)? {
        Some(base) => Ok(base),
        None => merge_base().map_err(|e| {
            format!(
                "cannot determine merge-base with origin/main: {e}\n       run \
                 `git fetch origin main` first (CI uses fetch-depth: 0), or pass \
                 --base <rev> explicitly."
            )
        }),
    }
}

/// Parses a bare `--base <rev>` or `--base=<rev>` out of the argv tail.
///
/// An EMPTY value is refused as hard as a missing one, and for a sharper
/// reason: git accepts `""` as a revision in the two plumbing calls this tool
/// makes, without failing the way a garbage rev would. `git show ":path"`
/// resolves to the INDEX version of the file, and `git ls-tree -r
/// --name-only ""` fails — which [`git_ls_tree`] turns into an empty path
/// list. So an empty base would make the tool compare ZERO structs and report
/// zero violations: green, silently, forever. That is exactly the self-diff
/// the explicit `--base` was added to prevent
/// one layer down. `merge-gate-check.sh` guards its own call site with
/// `[ -n "$BASE" ]`; this refusal is the half no caller can get wrong.
fn explicit_base_arg(mut args: impl Iterator<Item = String>) -> Result<Option<String>, String> {
    while let Some(arg) = args.next() {
        if let Some(v) = arg.strip_prefix("--base=") {
            return non_empty_base(v.to_string());
        }
        if arg == "--base" {
            return match args.next() {
                Some(v) => non_empty_base(v),
                None => Err("--base requires a value".to_string()),
            };
        }
    }
    Ok(None)
}

/// Refuses an empty `--base`; see [`explicit_base_arg`] for why git makes it
/// silently green rather than loudly wrong.
fn non_empty_base(v: String) -> Result<Option<String>, String> {
    if v.trim().is_empty() {
        return Err(
            "--base was given an empty value: git would read the base side from the \n                    index (`git show \":path\"`) and list no files at all, so the gate would \n                    compare nothing and pass unconditionally. Pass a real revision, or omit \n                    --base to use merge-base(HEAD, origin/main)."
                .to_string(),
        );
    }
    Ok(Some(v))
}

// ── git plumbing ──────────────────────────────────────────────────────────

fn merge_base() -> Result<String, String> {
    let out = Command::new("git")
        .args(["merge-base", "HEAD", "origin/main"])
        .output()
        .map_err(|e| e.to_string())?;
    if !out.status.success() {
        return Err(String::from_utf8_lossy(&out.stderr).trim().to_string());
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

/// File contents at `ref:path`, or `None` if the file didn't exist there.
fn git_show(reference: &str, path: &str) -> Option<String> {
    let out = Command::new("git")
        .arg("show")
        .arg(format!("{reference}:{path}"))
        .output()
        .ok()?;
    out.status
        .success()
        .then(|| String::from_utf8_lossy(&out.stdout).into_owned())
}

/// `.rs` paths tracked at `reference` under `root` (repo-relative).
fn git_ls_tree(reference: &str, root: &str) -> Vec<String> {
    let out = match Command::new("git")
        .args(["ls-tree", "-r", "--name-only", reference, "--", root])
        .output()
    {
        Ok(o) if o.status.success() => o,
        _ => return Vec::new(),
    };
    String::from_utf8_lossy(&out.stdout)
        .lines()
        .filter(|l| l.ends_with(".rs"))
        .map(|l| l.to_string())
        .collect()
}

// ── enum scan ─────────────────────────────────────────────────────────────

/// `(crate dir, crate name)` for every crate [`ENUM_SCOPE`] and
/// [`ENUM_SCOPE_APPS`] name, in path order.
fn enum_crates() -> Vec<(String, String)> {
    let mut dirs: Vec<std::path::PathBuf> = ENUM_SCOPE_APPS.iter().map(Into::into).collect();
    for (parent, prefix) in ENUM_SCOPE {
        let Ok(entries) = std::fs::read_dir(parent) else {
            continue;
        };
        dirs.extend(entries.flatten().map(|e| e.path()).filter(|p| {
            p.file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| n.starts_with(prefix))
        }));
    }
    dirs.sort();
    dirs.into_iter()
        .filter_map(|dir| {
            let manifest = std::fs::read_to_string(dir.join("Cargo.toml")).ok()?;
            Some((dir.to_string_lossy().into_owned(), package_name(&manifest)?))
        })
        .collect()
}

/// The `[package]` table's `name` in a `Cargo.toml` (a workspace-only
/// manifest has none).
fn package_name(manifest: &str) -> Option<String> {
    let mut in_package = false;
    for line in manifest.lines().map(str::trim) {
        if line.starts_with('[') {
            in_package = line == "[package]";
        } else if in_package
            && let Some(rest) = line.strip_prefix("name")
            && let Some(value) = rest.trim_start().strip_prefix('=')
        {
            return Some(value.trim().trim_matches('"').to_string());
        }
    }
    None
}

fn build_head_enum_map(crates: &[(String, String)]) -> EnumMap {
    let mut map = EnumMap::new();
    for (dir, name) in crates {
        let root = format!("{dir}/src");
        let mut files = Vec::new();
        walk_rs(Path::new(&root), &mut files);
        let mut scan = EnumScan::default();
        for path in files {
            let Ok(src) = std::fs::read_to_string(&path) else {
                continue;
            };
            let rel = path.strip_prefix(&root).unwrap_or(&path).to_string_lossy();
            if let Err(e) = scan.add_file(&src, &module_prefix(&rel)) {
                eprintln!("warn: failed to parse {}: {e}", path.display());
            }
        }
        map.extend(scan.finish(name));
    }
    map
}

/// [`build_head_enum_map`] at `base`, read in ONE `git cat-file --batch`
/// rather than a `git show` per file: the scope is every crate's `src/`.
fn build_base_enum_map(base: &str, crates: &[(String, String)]) -> EnumMap {
    let roots: Vec<String> = crates
        .iter()
        .map(|(dir, _)| format!("{dir}/src/"))
        .collect();
    let files = git_read_rs_files(base, &roots);
    let mut map = EnumMap::new();
    for ((_, name), root) in crates.iter().zip(&roots) {
        let mut scan = EnumScan::default();
        for (path, src) in &files {
            let Some(rel) = path.strip_prefix(root.as_str()) else {
                continue;
            };
            if let Err(e) = scan.add_file(src, &module_prefix(rel)) {
                eprintln!("warn: failed to parse {path} at {base}: {e}");
            }
        }
        map.extend(scan.finish(name));
    }
    map
}

/// Every `.rs` file under `roots` at `reference`, `(path, contents)`, via one
/// `git ls-tree` and one `git cat-file --batch`.
fn git_read_rs_files(reference: &str, roots: &[String]) -> Vec<(String, String)> {
    use std::io::{BufRead, BufReader, Read, Write};
    if roots.is_empty() {
        return Vec::new();
    }
    let out = match Command::new("git")
        .args(["ls-tree", "-r", reference, "--"])
        .args(roots)
        .output()
    {
        Ok(o) if o.status.success() => o,
        _ => return Vec::new(),
    };
    // `<mode> blob <sha>\t<path>`
    let blobs: Vec<(String, String)> = String::from_utf8_lossy(&out.stdout)
        .lines()
        .filter_map(|l| {
            let (meta, path) = l.split_once('\t')?;
            let mut it = meta.split_whitespace();
            let (_, kind, sha) = (it.next()?, it.next()?, it.next()?);
            (kind == "blob" && path.ends_with(".rs")).then(|| (sha.to_string(), path.to_string()))
        })
        .collect();
    let Ok(mut child) = Command::new("git")
        .args(["cat-file", "--batch"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .spawn()
    else {
        return Vec::new();
    };
    let mut stdin = child.stdin.take().expect("piped stdin");
    let request: String = blobs.iter().map(|(sha, _)| format!("{sha}\n")).collect();
    // Written from a second thread: git answers as it reads, and a pipe that
    // fills on both sides would deadlock a single-threaded writer.
    let writer = std::thread::spawn(move || {
        let _ = stdin.write_all(request.as_bytes());
    });
    let mut reader = BufReader::new(child.stdout.take().expect("piped stdout"));
    let mut files = Vec::new();
    for (_, path) in &blobs {
        let mut header = String::new();
        if reader.read_line(&mut header).unwrap_or(0) == 0 {
            break;
        }
        // `<sha> blob <size>`, or `<sha> missing`
        let Some(size) = header
            .split_whitespace()
            .nth(2)
            .and_then(|s| s.parse::<usize>().ok())
        else {
            continue;
        };
        let mut body = vec![0u8; size + 1]; // + git's trailing newline
        if reader.read_exact(&mut body).is_err() {
            break;
        }
        body.pop();
        files.push((path.clone(), String::from_utf8_lossy(&body).into_owned()));
    }
    let _ = writer.join();
    let _ = child.wait();
    files
}

// ── map building ──────────────────────────────────────────────────────────

fn build_head_map(root: &str) -> StructMap {
    let mut scan = StructScan::default();
    let mut files = Vec::new();
    walk_rs(Path::new(root), &mut files);
    for path in files {
        let Ok(src) = std::fs::read_to_string(&path) else {
            continue;
        };
        let rel = path.strip_prefix(root).unwrap_or(&path).to_string_lossy();
        add_to_scan(
            &mut scan,
            &src,
            &module_prefix(&rel),
            &path.to_string_lossy(),
        );
    }
    scan.finish()
}

fn build_base_map(base: &str, root: &str) -> StructMap {
    let mut scan = StructScan::default();
    for path in git_ls_tree(base, root) {
        let Some(src) = git_show(base, &path) else {
            continue;
        };
        let rel = path.strip_prefix(&format!("{root}/")).unwrap_or(&path);
        add_to_scan(&mut scan, &src, &module_prefix(rel), &path);
    }
    scan.finish()
}

fn add_to_scan(scan: &mut StructScan, src: &str, prefix: &str, display_path: &str) {
    if let Err(e) = scan.add_file(src, prefix) {
        eprintln!("warn: failed to parse {display_path}: {e}");
    }
}

/// Recursively collect `*.rs` files under `dir`.
fn walk_rs(dir: &Path, out: &mut Vec<std::path::PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk_rs(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
}

/// Rust module path from a crate-root-relative file path: strip `.rs`, drop a
/// trailing `mod`/`lib`/`main`, join with `::`. `auth.rs` -> `auth`; `lib.rs`
/// and `main.rs` -> `` (crate root); `foo/mod.rs` -> `foo`; `foo/bar.rs` ->
/// `foo::bar`.
fn module_prefix(rel_path: &str) -> String {
    let stem = rel_path.strip_suffix(".rs").unwrap_or(rel_path);
    let mut parts: Vec<&str> = stem.split('/').filter(|p| !p.is_empty()).collect();
    if matches!(parts.last(), Some(&"mod") | Some(&"lib") | Some(&"main")) {
        parts.pop();
    }
    parts.join("::")
}

#[cfg(test)]
mod main_tests {
    use super::{CRATES, explicit_base_arg, module_prefix};

    /// `CRATES` is the gate's ENTIRE scope and was read by no test —
    /// deleting an entry (measured: a straight revert of an earlier
    /// `fauna-sync-engine` fix) left `cargo test -p check-additive-evolution`
    /// green (36/36) and made a real violation the gate WAS reporting
    /// silently disappear. Pins the
    /// table's contents by value, with an explanatory message, so a
    /// deleted/altered root reds here instead.
    #[test]
    fn crates_table_is_pinned() {
        let expected: &[(&str, bool, &str)] = &[
            (
                "libs/fauna-protocol/src",
                true,
                "client↔nest↔nest wire payloads",
            ),
            (
                "libs/fauna-segment-store/src",
                false,
                "at-rest segment-store types (Manifest / SegmentSidecar / KindManifest)",
            ),
            (
                "libs/fauna-core/src",
                false,
                "FFI-crossing and at-rest strict types",
            ),
        ];
        assert_eq!(
            CRATES.len(),
            expected.len(),
            "CRATES gained or lost a root — every root must be pinned here too, or this \
             gate's scope can silently narrow with nothing to notice"
        );
        for (spec, (root, check_catch_all, note)) in CRATES.iter().zip(expected.iter()) {
            assert_eq!(
                spec.root, *root,
                "CRATES root changed — update version-compatibility.md § 5 item 6 and this pin"
            );
            assert_eq!(spec.check_catch_all, *check_catch_all, "{}", spec.root);
            assert_eq!(spec.note, *note, "{}", spec.root);
        }
    }

    #[test]
    fn module_prefix_cases() {
        assert_eq!(module_prefix("auth.rs"), "auth");
        assert_eq!(module_prefix("lib.rs"), "");
        assert_eq!(module_prefix("foo/mod.rs"), "foo");
        assert_eq!(module_prefix("foo/bar.rs"), "foo::bar");
        assert_eq!(module_prefix("main.rs"), "");
    }

    #[test]
    fn package_name_reads_the_package_table() {
        use super::package_name;
        let manifest = "[workspace]\nname = \"no\"\n\n[package]\nversion = \"1\"\nname = \"fauna-x\"\n\n[dependencies]\nname = \"no\"\n";
        assert_eq!(package_name(manifest).as_deref(), Some("fauna-x"));
        assert_eq!(package_name("[workspace]\nmembers = []\n"), None);
    }

    fn args(v: &[&str]) -> impl Iterator<Item = String> {
        v.iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>()
            .into_iter()
    }

    #[test]
    fn no_base_flag_is_none() {
        assert_eq!(explicit_base_arg(args(&[])), Ok(None));
    }

    #[test]
    fn space_form() {
        assert_eq!(
            explicit_base_arg(args(&["--base", "abc123"])),
            Ok(Some("abc123".to_string()))
        );
    }

    #[test]
    fn equals_form() {
        assert_eq!(
            explicit_base_arg(args(&["--base=abc123"])),
            Ok(Some("abc123".to_string()))
        );
    }

    #[test]
    fn missing_value_is_an_error() {
        assert!(explicit_base_arg(args(&["--base"])).is_err());
    }

    /// again, one level down: an EMPTY `--base` must be refused, not
    /// accepted as a revision. `git show ":path"` succeeds and returns the
    /// INDEX version, and `git ls-tree -r --name-only ""` fails, so an empty
    /// base makes the tool compare zero paths and report zero violations —
    /// green, silently, forever. That is the very self-diff the explicit
    /// `--base` exists to prevent, wearing the fix's clothes. The check
    /// script's `[ -n "$BASE" ]` guard is the caller-side half; this is the
    /// half no caller can get wrong.
    #[test]
    fn empty_value_is_an_error() {
        assert!(explicit_base_arg(args(&["--base", ""])).is_err());
        assert!(explicit_base_arg(args(&["--base="])).is_err());
    }
}
