

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureDroppedCallback(
				UniffiForeignFutureDroppedCallback cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static uint64_t call_UniffiCallbackInterfaceClone(
				UniffiCallbackInterfaceClone cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureResultU8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureResultU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureResultI8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureResultI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureResultU16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureResultU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureResultI16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureResultI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureResultU32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureResultU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureResultI32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureResultI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureResultU64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureResultU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureResultI64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureResultI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureResultF32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureResultF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureResultF64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureResultF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureResultRustBuffer result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureResultRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureResultVoid result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureResultVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_OBSERVER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_OBSERVER_METHOD0
typedef void (*UniffiCallbackInterfaceLaunchObserverMethod0)(uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchObserverMethod0(
				UniffiCallbackInterfaceLaunchObserverMethod0 cb, uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD0
typedef void (*UniffiCallbackInterfaceLaunchPersistenceMethod0)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchPersistenceMethod0(
				UniffiCallbackInterfaceLaunchPersistenceMethod0 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD1
typedef void (*UniffiCallbackInterfaceLaunchPersistenceMethod1)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchPersistenceMethod1(
				UniffiCallbackInterfaceLaunchPersistenceMethod1 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD2
typedef void (*UniffiCallbackInterfaceLaunchPersistenceMethod2)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchPersistenceMethod2(
				UniffiCallbackInterfaceLaunchPersistenceMethod2 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD3
typedef void (*UniffiCallbackInterfaceLaunchPersistenceMethod3)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchPersistenceMethod3(
				UniffiCallbackInterfaceLaunchPersistenceMethod3 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD4
typedef void (*UniffiCallbackInterfaceLaunchPersistenceMethod4)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchPersistenceMethod4(
				UniffiCallbackInterfaceLaunchPersistenceMethod4 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD5
typedef void (*UniffiCallbackInterfaceLaunchPersistenceMethod5)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchPersistenceMethod5(
				UniffiCallbackInterfaceLaunchPersistenceMethod5 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD6
typedef void (*UniffiCallbackInterfaceLaunchPersistenceMethod6)(uint64_t uniffi_handle, RustBuffer record, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchPersistenceMethod6(
				UniffiCallbackInterfaceLaunchPersistenceMethod6 cb, uint64_t uniffi_handle, RustBuffer record, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, record, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD7
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD7
typedef void (*UniffiCallbackInterfaceLaunchPersistenceMethod7)(uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchPersistenceMethod7(
				UniffiCallbackInterfaceLaunchPersistenceMethod7 cb, uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD8
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD8
typedef void (*UniffiCallbackInterfaceLaunchPersistenceMethod8)(uint64_t uniffi_handle, RustBuffer nest_url, RustBuffer user_handle, RustBuffer domain, RustBuffer tier, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchPersistenceMethod8(
				UniffiCallbackInterfaceLaunchPersistenceMethod8 cb, uint64_t uniffi_handle, RustBuffer nest_url, RustBuffer user_handle, RustBuffer domain, RustBuffer tier, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, nest_url, user_handle, domain, tier, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD9
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD9
typedef void (*UniffiCallbackInterfaceLaunchPersistenceMethod9)(uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchPersistenceMethod9(
				UniffiCallbackInterfaceLaunchPersistenceMethod9 cb, uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD10
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD10
typedef void (*UniffiCallbackInterfaceLaunchPersistenceMethod10)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchPersistenceMethod10(
				UniffiCallbackInterfaceLaunchPersistenceMethod10 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD11
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE_METHOD11
typedef void (*UniffiCallbackInterfaceLaunchPersistenceMethod11)(uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLaunchPersistenceMethod11(
				UniffiCallbackInterfaceLaunchPersistenceMethod11 cb, uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_PENDING_PROVISION_STORE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_PENDING_PROVISION_STORE_METHOD0
typedef void (*UniffiCallbackInterfacePendingProvisionStoreMethod0)(uint64_t uniffi_handle, RustBuffer secret_hex, RustBuffer record, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfacePendingProvisionStoreMethod0(
				UniffiCallbackInterfacePendingProvisionStoreMethod0 cb, uint64_t uniffi_handle, RustBuffer secret_hex, RustBuffer record, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, secret_hex, record, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_PENDING_PROVISION_STORE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_PENDING_PROVISION_STORE_METHOD1
typedef void (*UniffiCallbackInterfacePendingProvisionStoreMethod1)(uint64_t uniffi_handle, RustBuffer secret_hex, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfacePendingProvisionStoreMethod1(
				UniffiCallbackInterfacePendingProvisionStoreMethod1 cb, uint64_t uniffi_handle, RustBuffer secret_hex, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, secret_hex, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LAUNCH_OBSERVER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LAUNCH_OBSERVER
typedef struct UniffiVTableCallbackInterfaceLaunchObserver {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceLaunchObserverMethod0 onChanged;
} UniffiVTableCallbackInterfaceLaunchObserver;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LAUNCH_PERSISTENCE
typedef struct UniffiVTableCallbackInterfaceLaunchPersistence {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceLaunchPersistenceMethod0 accountIndexRefusal;
    UniffiCallbackInterfaceLaunchPersistenceMethod1 loadIdentity;
    UniffiCallbackInterfaceLaunchPersistenceMethod2 loadNestUrl;
    UniffiCallbackInterfaceLaunchPersistenceMethod3 loadPendingInvite;
    UniffiCallbackInterfaceLaunchPersistenceMethod4 loadAwaitingDns;
    UniffiCallbackInterfaceLaunchPersistenceMethod5 loadPendingFactoryReset;
    UniffiCallbackInterfaceLaunchPersistenceMethod6 savePendingFactoryReset;
    UniffiCallbackInterfaceLaunchPersistenceMethod7 deletePendingFactoryReset;
    UniffiCallbackInterfaceLaunchPersistenceMethod8 saveAuthenticated;
    UniffiCallbackInterfaceLaunchPersistenceMethod9 deletePendingInvite;
    UniffiCallbackInterfaceLaunchPersistenceMethod10 loadReachIpv4;
    UniffiCallbackInterfaceLaunchPersistenceMethod11 deleteReachIpv4;
} UniffiVTableCallbackInterfaceLaunchPersistence;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_PENDING_PROVISION_STORE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_PENDING_PROVISION_STORE
typedef struct UniffiVTableCallbackInterfacePendingProvisionStore {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfacePendingProvisionStoreMethod0 saveAwaitingDns;
    UniffiCallbackInterfacePendingProvisionStoreMethod1 clearAwaitingDns;
} UniffiVTableCallbackInterfacePendingProvisionStore;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_CLONE_LAUNCHMACHINE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_CLONE_LAUNCHMACHINE
uint64_t uniffi_fauna_launch_machine_fn_clone_launchmachine(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_FREE_LAUNCHMACHINE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_FREE_LAUNCHMACHINE
void uniffi_fauna_launch_machine_fn_free_launchmachine(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_CONSTRUCTOR_LAUNCHMACHINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_CONSTRUCTOR_LAUNCHMACHINE_NEW
uint64_t uniffi_fauna_launch_machine_fn_constructor_launchmachine_new(uint64_t observer, uint64_t persistence, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_CURRENT_BEARER
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_CURRENT_BEARER
RustBuffer uniffi_fauna_launch_machine_fn_method_launchmachine_current_bearer(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_IDENTITY_CHANGED_AUTHORITY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_IDENTITY_CHANGED_AUTHORITY
RustBuffer uniffi_fauna_launch_machine_fn_method_launchmachine_identity_changed_authority(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_NOTIFY_401
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_NOTIFY_401
uint64_t uniffi_fauna_launch_machine_fn_method_launchmachine_notify_401(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_REFRESH_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_REFRESH_TOKEN
uint64_t uniffi_fauna_launch_machine_fn_method_launchmachine_refresh_token(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_RETRY_SILENT_CHALLENGE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_RETRY_SILENT_CHALLENGE
uint64_t uniffi_fauna_launch_machine_fn_method_launchmachine_retry_silent_challenge(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_SNAPSHOT
RustBuffer uniffi_fauna_launch_machine_fn_method_launchmachine_snapshot(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_START
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_START
uint64_t uniffi_fauna_launch_machine_fn_method_launchmachine_start(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_TRUST_NEST_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHMACHINE_TRUST_NEST_IDENTITY
uint64_t uniffi_fauna_launch_machine_fn_method_launchmachine_trust_nest_identity(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_CLONE_LAUNCHOBSERVER
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_CLONE_LAUNCHOBSERVER
uint64_t uniffi_fauna_launch_machine_fn_clone_launchobserver(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_FREE_LAUNCHOBSERVER
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_FREE_LAUNCHOBSERVER
void uniffi_fauna_launch_machine_fn_free_launchobserver(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_INIT_CALLBACK_VTABLE_LAUNCHOBSERVER
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_INIT_CALLBACK_VTABLE_LAUNCHOBSERVER
void uniffi_fauna_launch_machine_fn_init_callback_vtable_launchobserver(UniffiVTableCallbackInterfaceLaunchObserver* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHOBSERVER_ON_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHOBSERVER_ON_CHANGED
void uniffi_fauna_launch_machine_fn_method_launchobserver_on_changed(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_CLONE_LAUNCHPERSISTENCE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_CLONE_LAUNCHPERSISTENCE
uint64_t uniffi_fauna_launch_machine_fn_clone_launchpersistence(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_FREE_LAUNCHPERSISTENCE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_FREE_LAUNCHPERSISTENCE
void uniffi_fauna_launch_machine_fn_free_launchpersistence(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_INIT_CALLBACK_VTABLE_LAUNCHPERSISTENCE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_INIT_CALLBACK_VTABLE_LAUNCHPERSISTENCE
void uniffi_fauna_launch_machine_fn_init_callback_vtable_launchpersistence(UniffiVTableCallbackInterfaceLaunchPersistence* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_ACCOUNT_INDEX_REFUSAL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_ACCOUNT_INDEX_REFUSAL
RustBuffer uniffi_fauna_launch_machine_fn_method_launchpersistence_account_index_refusal(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_LOAD_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_LOAD_IDENTITY
RustBuffer uniffi_fauna_launch_machine_fn_method_launchpersistence_load_identity(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_LOAD_NEST_URL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_LOAD_NEST_URL
RustBuffer uniffi_fauna_launch_machine_fn_method_launchpersistence_load_nest_url(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_LOAD_PENDING_INVITE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_LOAD_PENDING_INVITE
RustBuffer uniffi_fauna_launch_machine_fn_method_launchpersistence_load_pending_invite(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_LOAD_AWAITING_DNS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_LOAD_AWAITING_DNS
RustBuffer uniffi_fauna_launch_machine_fn_method_launchpersistence_load_awaiting_dns(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_LOAD_PENDING_FACTORY_RESET
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_LOAD_PENDING_FACTORY_RESET
RustBuffer uniffi_fauna_launch_machine_fn_method_launchpersistence_load_pending_factory_reset(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_SAVE_PENDING_FACTORY_RESET
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_SAVE_PENDING_FACTORY_RESET
void uniffi_fauna_launch_machine_fn_method_launchpersistence_save_pending_factory_reset(uint64_t ptr, RustBuffer record, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_DELETE_PENDING_FACTORY_RESET
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_DELETE_PENDING_FACTORY_RESET
void uniffi_fauna_launch_machine_fn_method_launchpersistence_delete_pending_factory_reset(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_SAVE_AUTHENTICATED
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_SAVE_AUTHENTICATED
void uniffi_fauna_launch_machine_fn_method_launchpersistence_save_authenticated(uint64_t ptr, RustBuffer nest_url, RustBuffer user_handle, RustBuffer domain, RustBuffer tier, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_DELETE_PENDING_INVITE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_DELETE_PENDING_INVITE
void uniffi_fauna_launch_machine_fn_method_launchpersistence_delete_pending_invite(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_LOAD_REACH_IPV4
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_LOAD_REACH_IPV4
RustBuffer uniffi_fauna_launch_machine_fn_method_launchpersistence_load_reach_ipv4(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_DELETE_REACH_IPV4
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_LAUNCHPERSISTENCE_DELETE_REACH_IPV4
void uniffi_fauna_launch_machine_fn_method_launchpersistence_delete_reach_ipv4(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_CLONE_PENDINGPROVISIONSTORE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_CLONE_PENDINGPROVISIONSTORE
uint64_t uniffi_fauna_launch_machine_fn_clone_pendingprovisionstore(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_FREE_PENDINGPROVISIONSTORE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_FREE_PENDINGPROVISIONSTORE
void uniffi_fauna_launch_machine_fn_free_pendingprovisionstore(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_INIT_CALLBACK_VTABLE_PENDINGPROVISIONSTORE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_INIT_CALLBACK_VTABLE_PENDINGPROVISIONSTORE
void uniffi_fauna_launch_machine_fn_init_callback_vtable_pendingprovisionstore(UniffiVTableCallbackInterfacePendingProvisionStore* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_PENDINGPROVISIONSTORE_SAVE_AWAITING_DNS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_PENDINGPROVISIONSTORE_SAVE_AWAITING_DNS
RustBuffer uniffi_fauna_launch_machine_fn_method_pendingprovisionstore_save_awaiting_dns(uint64_t ptr, RustBuffer secret_hex, RustBuffer record, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_PENDINGPROVISIONSTORE_CLEAR_AWAITING_DNS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_METHOD_PENDINGPROVISIONSTORE_CLEAR_AWAITING_DNS
void uniffi_fauna_launch_machine_fn_method_pendingprovisionstore_clear_awaiting_dns(uint64_t ptr, RustBuffer secret_hex, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_FUNC_RESOLVED_DIAL_URL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_FUNC_RESOLVED_DIAL_URL
RustBuffer uniffi_fauna_launch_machine_fn_func_resolved_dial_url(RustBuffer nest_url, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_FUNC_MINT_AND_PERSIST_PENDING_FACTORY_RESET
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_FN_FUNC_MINT_AND_PERSIST_PENDING_FACTORY_RESET
RustBuffer uniffi_fauna_launch_machine_fn_func_mint_and_persist_pending_factory_reset(uint64_t store, RustBuffer nest_url, RustBuffer handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUSTBUFFER_ALLOC
RustBuffer ffi_fauna_launch_machine_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_fauna_launch_machine_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUSTBUFFER_FREE
void ffi_fauna_launch_machine_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUSTBUFFER_RESERVE
RustBuffer ffi_fauna_launch_machine_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_U8
void ffi_fauna_launch_machine_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_U8
void ffi_fauna_launch_machine_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_U8
void ffi_fauna_launch_machine_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_fauna_launch_machine_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_I8
void ffi_fauna_launch_machine_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_I8
void ffi_fauna_launch_machine_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_I8
void ffi_fauna_launch_machine_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_fauna_launch_machine_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_U16
void ffi_fauna_launch_machine_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_U16
void ffi_fauna_launch_machine_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_U16
void ffi_fauna_launch_machine_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_fauna_launch_machine_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_I16
void ffi_fauna_launch_machine_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_I16
void ffi_fauna_launch_machine_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_I16
void ffi_fauna_launch_machine_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_fauna_launch_machine_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_U32
void ffi_fauna_launch_machine_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_U32
void ffi_fauna_launch_machine_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_U32
void ffi_fauna_launch_machine_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_fauna_launch_machine_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_I32
void ffi_fauna_launch_machine_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_I32
void ffi_fauna_launch_machine_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_I32
void ffi_fauna_launch_machine_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_fauna_launch_machine_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_U64
void ffi_fauna_launch_machine_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_U64
void ffi_fauna_launch_machine_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_U64
void ffi_fauna_launch_machine_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_fauna_launch_machine_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_I64
void ffi_fauna_launch_machine_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_I64
void ffi_fauna_launch_machine_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_I64
void ffi_fauna_launch_machine_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_fauna_launch_machine_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_F32
void ffi_fauna_launch_machine_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_F32
void ffi_fauna_launch_machine_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_F32
void ffi_fauna_launch_machine_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_F32
float ffi_fauna_launch_machine_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_F64
void ffi_fauna_launch_machine_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_F64
void ffi_fauna_launch_machine_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_F64
void ffi_fauna_launch_machine_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_F64
double ffi_fauna_launch_machine_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_fauna_launch_machine_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_fauna_launch_machine_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_fauna_launch_machine_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_fauna_launch_machine_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_POLL_VOID
void ffi_fauna_launch_machine_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_CANCEL_VOID
void ffi_fauna_launch_machine_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_FREE_VOID
void ffi_fauna_launch_machine_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_RUST_FUTURE_COMPLETE_VOID
void ffi_fauna_launch_machine_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_FUNC_RESOLVED_DIAL_URL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_FUNC_RESOLVED_DIAL_URL
uint16_t uniffi_fauna_launch_machine_checksum_func_resolved_dial_url(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_FUNC_MINT_AND_PERSIST_PENDING_FACTORY_RESET
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_FUNC_MINT_AND_PERSIST_PENDING_FACTORY_RESET
uint16_t uniffi_fauna_launch_machine_checksum_func_mint_and_persist_pending_factory_reset(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_CURRENT_BEARER
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_CURRENT_BEARER
uint16_t uniffi_fauna_launch_machine_checksum_method_launchmachine_current_bearer(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_IDENTITY_CHANGED_AUTHORITY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_IDENTITY_CHANGED_AUTHORITY
uint16_t uniffi_fauna_launch_machine_checksum_method_launchmachine_identity_changed_authority(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_NOTIFY_401
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_NOTIFY_401
uint16_t uniffi_fauna_launch_machine_checksum_method_launchmachine_notify_401(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_REFRESH_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_REFRESH_TOKEN
uint16_t uniffi_fauna_launch_machine_checksum_method_launchmachine_refresh_token(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_RETRY_SILENT_CHALLENGE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_RETRY_SILENT_CHALLENGE
uint16_t uniffi_fauna_launch_machine_checksum_method_launchmachine_retry_silent_challenge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_SNAPSHOT
uint16_t uniffi_fauna_launch_machine_checksum_method_launchmachine_snapshot(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_START
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_START
uint16_t uniffi_fauna_launch_machine_checksum_method_launchmachine_start(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_TRUST_NEST_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHMACHINE_TRUST_NEST_IDENTITY
uint16_t uniffi_fauna_launch_machine_checksum_method_launchmachine_trust_nest_identity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHOBSERVER_ON_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHOBSERVER_ON_CHANGED
uint16_t uniffi_fauna_launch_machine_checksum_method_launchobserver_on_changed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_ACCOUNT_INDEX_REFUSAL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_ACCOUNT_INDEX_REFUSAL
uint16_t uniffi_fauna_launch_machine_checksum_method_launchpersistence_account_index_refusal(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_LOAD_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_LOAD_IDENTITY
uint16_t uniffi_fauna_launch_machine_checksum_method_launchpersistence_load_identity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_LOAD_NEST_URL
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_LOAD_NEST_URL
uint16_t uniffi_fauna_launch_machine_checksum_method_launchpersistence_load_nest_url(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_LOAD_PENDING_INVITE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_LOAD_PENDING_INVITE
uint16_t uniffi_fauna_launch_machine_checksum_method_launchpersistence_load_pending_invite(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_LOAD_AWAITING_DNS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_LOAD_AWAITING_DNS
uint16_t uniffi_fauna_launch_machine_checksum_method_launchpersistence_load_awaiting_dns(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_LOAD_PENDING_FACTORY_RESET
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_LOAD_PENDING_FACTORY_RESET
uint16_t uniffi_fauna_launch_machine_checksum_method_launchpersistence_load_pending_factory_reset(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_SAVE_PENDING_FACTORY_RESET
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_SAVE_PENDING_FACTORY_RESET
uint16_t uniffi_fauna_launch_machine_checksum_method_launchpersistence_save_pending_factory_reset(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_DELETE_PENDING_FACTORY_RESET
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_DELETE_PENDING_FACTORY_RESET
uint16_t uniffi_fauna_launch_machine_checksum_method_launchpersistence_delete_pending_factory_reset(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_SAVE_AUTHENTICATED
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_SAVE_AUTHENTICATED
uint16_t uniffi_fauna_launch_machine_checksum_method_launchpersistence_save_authenticated(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_DELETE_PENDING_INVITE
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_DELETE_PENDING_INVITE
uint16_t uniffi_fauna_launch_machine_checksum_method_launchpersistence_delete_pending_invite(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_LOAD_REACH_IPV4
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_LOAD_REACH_IPV4
uint16_t uniffi_fauna_launch_machine_checksum_method_launchpersistence_load_reach_ipv4(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_DELETE_REACH_IPV4
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_LAUNCHPERSISTENCE_DELETE_REACH_IPV4
uint16_t uniffi_fauna_launch_machine_checksum_method_launchpersistence_delete_reach_ipv4(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_PENDINGPROVISIONSTORE_SAVE_AWAITING_DNS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_PENDINGPROVISIONSTORE_SAVE_AWAITING_DNS
uint16_t uniffi_fauna_launch_machine_checksum_method_pendingprovisionstore_save_awaiting_dns(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_PENDINGPROVISIONSTORE_CLEAR_AWAITING_DNS
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_METHOD_PENDINGPROVISIONSTORE_CLEAR_AWAITING_DNS
uint16_t uniffi_fauna_launch_machine_checksum_method_pendingprovisionstore_clear_awaiting_dns(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_CONSTRUCTOR_LAUNCHMACHINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_FAUNA_LAUNCH_MACHINE_CHECKSUM_CONSTRUCTOR_LAUNCHMACHINE_NEW
uint16_t uniffi_fauna_launch_machine_checksum_constructor_launchmachine_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_FAUNA_LAUNCH_MACHINE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_fauna_launch_machine_uniffi_contract_version(void
    
);
#endif

 void fauna_launch_machine_observer_cgo_dispatchCallbackInterfaceLaunchObserverMethod0(uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_observer_cgo_dispatchCallbackInterfaceLaunchObserverFree(uint64_t handle);
uint64_t fauna_launch_machine_observer_cgo_dispatchCallbackInterfaceLaunchObserverClone(uint64_t handle);
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceMethod0(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceMethod1(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceMethod2(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceMethod3(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceMethod4(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceMethod5(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceMethod6(uint64_t uniffi_handle, RustBuffer record, void* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceMethod7(uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceMethod8(uint64_t uniffi_handle, RustBuffer nest_url, RustBuffer user_handle, RustBuffer domain, RustBuffer tier, void* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceMethod9(uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceMethod10(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceMethod11(uint64_t uniffi_handle, void* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceFree(uint64_t handle);
uint64_t fauna_launch_machine_persistence_cgo_dispatchCallbackInterfaceLaunchPersistenceClone(uint64_t handle);
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfacePendingProvisionStoreMethod0(uint64_t uniffi_handle, RustBuffer secret_hex, RustBuffer record, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfacePendingProvisionStoreMethod1(uint64_t uniffi_handle, RustBuffer secret_hex, void* uniffi_out_return, RustCallStatus* callStatus );
 void fauna_launch_machine_persistence_cgo_dispatchCallbackInterfacePendingProvisionStoreFree(uint64_t handle);
uint64_t fauna_launch_machine_persistence_cgo_dispatchCallbackInterfacePendingProvisionStoreClone(uint64_t handle);

void fauna_launch_machine_uniffiFutureContinuationCallback(uint64_t, int8_t);
void fauna_launch_machine_uniffiFreeGorutine(uint64_t);
