// Cross-language Push-frame verifier for the one push kind the Go
// mail-bridge decodes in production: fauna.bridges.push.mailbox_state.
//
// Every other WS-RPC push kind is consumed only by the shared Rust
// PushEvent::from_push decoder (which the WASM + UniFFI receivers share),
// so there is no independent decoder to drift against. This one crosses
// into the Go bridge's own hand-written dag-cbor decoder, so it gets a
// Rust-produced fixture. The existing TestPushHandler_BridgeMailboxState
// (client_test.go) only round-trips Go→Go and cannot catch a Rust-side
// field rename or a MailboxStateEvent tag-style change; these fixtures can.
//
// FIXTURE REGEN: testdata/push-mailbox-state-{append,flags,expunge,move}.cbor
// are regenerated by the Rust example
// libs/fauna-protocol/examples/regen_go_push_fixture.rs. From the
// workspace root:
//
//	cargo run -p fauna-protocol --example regen_go_push_fixture
//
// then commit the updated fixtures. The bytes are byte-identical to what
// nest's WsState::notify_push emits (bins/fauna-nest/src/ws.rs).
package wsrpc

import (
	"bytes"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/faunasocial/fauna/bins/fauna-bridges/internal/dagcbor"
)

// actorID is the recognizable 32-byte pattern the Rust generator stamps
// into every fixture (ACTOR_ID = [0x11; 32]).
var actorID = bytes.Repeat([]byte{0x11}, 32)

func TestPushMailboxStateCrossLanguage(t *testing.T) {
	t.Parallel()
	cases := []struct {
		fixture string
		want    BridgeMailboxStatePush
	}{
		{
			fixture: "push-mailbox-state-append.cbor",
			want: BridgeMailboxStatePush{
				SubscriptionID: 1,
				ActorID:        actorID,
				Mailbox:        "INBOX",
				Event: MailboxStateEvent{
					Kind:   MailboxStateEventAppend,
					Uid:    101,
					Flags:  []string{"\\Seen", "\\Recent"},
					Modseq: 5000,
				},
			},
		},
		{
			fixture: "push-mailbox-state-flags.cbor",
			want: BridgeMailboxStatePush{
				SubscriptionID: 2,
				ActorID:        actorID,
				Mailbox:        "INBOX",
				Event: MailboxStateEvent{
					Kind:   MailboxStateEventFlags,
					Uid:    102,
					Flags:  []string{"\\Flagged"},
					Modseq: 5001,
				},
			},
		},
		{
			fixture: "push-mailbox-state-expunge.cbor",
			want: BridgeMailboxStatePush{
				SubscriptionID: 3,
				ActorID:        actorID,
				Mailbox:        "INBOX",
				Event: MailboxStateEvent{
					Kind:   MailboxStateEventExpunge,
					Uid:    103,
					Modseq: 5002,
				},
			},
		},
		{
			fixture: "push-mailbox-state-move.cbor",
			want: BridgeMailboxStatePush{
				SubscriptionID: 4,
				ActorID:        actorID,
				Mailbox:        "Archive",
				Event: MailboxStateEvent{
					Kind:      MailboxStateEventMove,
					SrcUid:    104,
					DstUid:    204,
					ModseqSrc: 5003,
					ModseqDst: 5004,
					Side:      MoveSideDestination,
				},
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.fixture, func(t *testing.T) {
			t.Parallel()
			b, err := os.ReadFile(filepath.Join("testdata", tc.fixture))
			if err != nil {
				t.Fatalf("read fixture: %v (run `cargo run -p fauna-protocol --example regen_go_push_fixture` to regenerate)", err)
			}

			// Step 1: decode the envelope. It must be a Push frame with the
			// expected kind; this exercises the integer-keyed frame decode.
			frame, err := DecodeFrame(b)
			if err != nil {
				t.Fatalf("DecodeFrame: %v", err)
			}
			push, ok := frame.(*PushFrame)
			if !ok {
				t.Fatalf("DecodeFrame returned %T, want *PushFrame", frame)
			}
			if push.Type != TypePush {
				t.Errorf("Type = %d, want %d", push.Type, TypePush)
			}
			if push.Kind != BridgeMailboxStatePushKind {
				t.Errorf("Kind = %q, want %q", push.Kind, BridgeMailboxStatePushKind)
			}

			// Step 2: decode the typed payload through the exact production
			// path (notification_router.go uses the same call).
			got, err := dagcbor.Unmarshal[BridgeMailboxStatePush](push.Payload)
			if err != nil {
				t.Fatalf("dagcbor.Unmarshal[BridgeMailboxStatePush]: %v", err)
			}
			if !reflect.DeepEqual(got, tc.want) {
				t.Errorf("decoded mismatch:\n got = %+v\nwant = %+v", got, tc.want)
			}
		})
	}
}
