// Phase D.2: SMTP submission AEAD-unwrap-as-auth tests. Mirrors
// `bins/fauna-bridges/internal/mda/imap/auth_test.go` in shape —
// programmable wsrpc fake + canned replies + assertions on the
// "exactly one report_auth_event per attempt" contract — but exercises
// the submission-token path (different RPCs, different blob shape,
// no MLSCapability stash).
//
// Fixtures live in `libs/fauna-protocol/schemas/test_vectors/`
// (regenerated by `cargo run -p fauna-mls --example
// gen_wrapped_blob_vectors`). The submission-token fixture's
// `actor_id` IS the deterministic signing key's verifying-key bytes —
// the codebase invariant from `bins/fauna-nest/src/registration.rs:184`
// that lets the FFI reconstruct the user's signing pubkey from
// `actor_id` without a separate nest fetch.
package mta

import (
	"context"
	"crypto/ed25519"
	"encoding/hex"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sync"
	"testing"
	"time"

	"github.com/emersion/go-sasl"
	"github.com/fxamacker/cbor/v2"

	"github.com/faunasocial/fauna/bins/fauna-bridges/internal/auth"
	"github.com/faunasocial/fauna/bins/fauna-bridges/internal/dagcbor"
	"github.com/faunasocial/fauna/bins/fauna-bridges/internal/wsrpc"
	"github.com/faunasocial/fauna/bins/fauna-bridges/internal/wsrpc/wsrpctest"
)

// ── Fixture parameters ───────────────────────────────────────────
//
// Mirror `libs/fauna-mls/examples/gen_wrapped_blob_vectors.rs`'s
// submission-token block: the deterministic Ed25519 key derived from
// the 32-byte 0xAA seed, the "default" credential_id, the
// "deterministic-pw" (PLAIN) / "oauth-deterministic-token" (HKDF)
// secrets.

func fixtureSigningSeed() []byte {
	out := make([]byte, 32)
	for i := range out {
		out[i] = 0xAA
	}
	return out
}

// fixtureActorID is the deterministic signing key's verifying-key
// bytes — equal to the submission-token fixture's `actor_id` per the
// codebase invariant.
func fixtureActorID() []byte {
	priv := ed25519.NewKeyFromSeed(fixtureSigningSeed())
	return []byte(priv.Public().(ed25519.PublicKey))
}

var (
	fixtureCredentialID  = "default"
	fixturePlainPassword = []byte("deterministic-pw")
	fixtureOAuthToken    = []byte("oauth-deterministic-token")
)

func repoTestVectorsPath(name string) string {
	// auth_test.go sits at .../bins/fauna-bridges/internal/mta/
	// Test vectors are at <repo>/libs/fauna-protocol/schemas/test_vectors/
	// → 4 levels up from this file.
	return filepath.Join("..", "..", "..", "..",
		"libs", "fauna-protocol", "schemas", "test_vectors", name)
}

func mustReadFixture(t *testing.T, name string) []byte {
	t.Helper()
	p := repoTestVectorsPath(name)
	b, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("read fixture %s: %v", p, err)
	}
	return b
}

// ── Programmable caller for submission AUTH tests ─────────────────

type submissionAuthCall struct {
	method string
	body   []byte
}

type submissionAuthCaller struct {
	mu    sync.Mutex
	calls []submissionAuthCall

	validateRecipientReplyHex string
	// validateRecipientByLocal, when non-empty, overrides
	// validateRecipientReplyHex on a per-local-part basis. The string
	// key is the request's local_part; the value is the resolved
	// actor_id bytes (32 bytes for real fixtures). Missing keys fall
	// back to a "reject — unknown recipient" reply, mirroring nest's
	// behaviour for an unprovisioned local-part. Used by D.6 tests
	// that need different actor_ids per recipient address.
	validateRecipientByLocal map[string][]byte
	// validateRecipientErr, when non-nil, is returned by every
	// validate_recipient call (transport-failure path). It also drives
	// resolve_recipient (the submission RCPT path), so the existing RCPT
	// transport-error test exercises the resolver cutover unchanged.
	validateRecipientErr error
	// resolveForwarders drives the resolve_recipient Forward outcome (the
	// submission admin external-forwarder edge — mail-aliases.md § Kind 7),
	// keyed by the RCPT local_part. validateRecipientByLocal still drives the
	// Resolved outcome; an unmapped local_part rejects.
	resolveForwarders map[string]submissionForwarderDecision

	submissionBlob []byte
	fetchBlobErr   error

	// quotaOutcomes drives the per-call response of
	// fauna.bridges.check_submission_quota (D.3). When empty, the fake
	// returns "allowed" indefinitely; otherwise each successive
	// check_submission_quota call consumes one entry. After the slice
	// is drained, further calls fall back to "allowed" so D.2 tests
	// that ignore quota don't have to set it.
	quotaOutcomes []checkSubmissionQuotaOutcome
	// checkQuotaErr, when non-nil, is returned from every
	// check_submission_quota call (transport-failure path).
	checkQuotaErr error

	// enqueueOutboundMailErr, when non-nil, is returned from every
	// fauna.bridges.enqueue_outbound_mail call (transport-failure
	// path for D.5).
	enqueueOutboundMailErr error
	// enqueuedOutbound captures each successful enqueue so tests can
	// assert the wire shape (sender, recipient list, body bytes).
	enqueuedOutbound []enqueueOutboundCall

	// fetchRecipientMLSPubkey returns this byte slice to every
	// fauna.bridges.fetch_recipient_mls_pubkey call. nil → reply
	// `blob: None` (recipient hasn't provisioned an MLS pubkey).
	mlsPubkey []byte
	// mlsPubkeySuccessionPending rides the reply's `succession_pending`
	// field alongside a nil mlsPubkey — true simulates a succession's
	// successor who has not yet re-provisioned a key (smtp-server.md
	// § Error / tempfail strategy). Meaningless when mlsPubkey is non-nil.
	mlsPubkeySuccessionPending bool
	// fetchRecipientIndexKey returns this byte slice to every
	// fauna.bridges.fetch_recipient_index_key call. nil → reply
	// `blob: None` (Phase E carryover — bridge then falls back to
	// the MLS pubkey for index encryption).
	indexPubkey []byte
	// fetchRecipientMLSPubkeyErr returns an error for every
	// fetch_recipient_mls_pubkey call.
	fetchRecipientMLSPubkeyErr error

	// submitInboundCalls captures every observed submit_inbound_mail
	// invocation so tests can assert sender's Sent copy (and any
	// other "own submission" cases).
	submitInboundCalls []inboundMailCall
	// ingestInboundCalls captures every observed ingest_inbound_mail
	// invocation so tests can assert Fauna-recipient delivery.
	ingestInboundCalls []inboundMailCall
	// submitInboundErr, when non-nil, is returned from every
	// submit_inbound_mail call (Sent-copy failure path).
	submitInboundErr error
	// ingestInboundErr, when non-nil, is returned from every
	// ingest_inbound_mail call (Fauna-recipient failure path).
	ingestInboundErr error
	// forwardRequests captures every forward_message call (the submission
	// admin external-forwarder redirect). Reuses the inbound forwardRecord shape.
	forwardRequests []forwardRecord
	// forwardMessageErr, when non-nil, is returned from every forward_message
	// call (after the request is recorded) — nest refused or never received
	// the enqueue.
	forwardMessageErr error
}

// submissionForwarderDecision drives a resolve_recipient Forward outcome for one
// RCPT local-part (the submission admin external-forwarder edge).
type submissionForwarderDecision struct {
	target string
	admin  []byte
}

// inboundMailCall records one observed submit_inbound_mail or
// ingest_inbound_mail invocation. The fields capture the wire shape
// the test wants to assert against (actor target, ciphertext sizes,
// disposition); the encrypted payload bytes themselves are HPKE
// output so tests don't try to decode them.
type inboundMailCall struct {
	ActorID            []byte
	EncryptedBodySize  int
	EncryptedIndexSize int
	SenderDomain       string
	SpamDisposition    string
	Verdicts           map[string]string // kind-summary per axis
}

// enqueueOutboundCall records one observed
// fauna.bridges.enqueue_outbound_mail call.
type enqueueOutboundCall struct {
	OriginalMsgID  string
	OriginalSender string
	Recipients     []string
	RawMessage     []byte
	// StagedBody is non-nil when the body rode the bulk-byte plane under a
	// one-shot AEAD envelope (the staged-envelope rule): RawMessage is then
	// empty and the reference carries the chunk hashes + total + key.
	StagedBody *wsrpc.StagedBodyRef
}

// checkSubmissionQuotaOutcome is a one-off scripted response for the
// fake's check_submission_quota handler. `over` flips the outcome to
// "over_quota" with `remaining` headroom; otherwise "allowed".
type checkSubmissionQuotaOutcome struct {
	over      bool
	remaining uint32
}

func (a *submissionAuthCaller) Call(_ context.Context, method string, body, reply any) error {
	a.mu.Lock()
	defer a.mu.Unlock()
	enc, err := dagcbor.Marshal(body)
	if err != nil {
		return err
	}
	a.calls = append(a.calls, submissionAuthCall{method: method, body: enc})

	switch method {
	case wsrpc.MethodValidateRecipient:
		if a.validateRecipientErr != nil {
			return a.validateRecipientErr
		}
		if len(a.validateRecipientByLocal) > 0 {
			var req struct {
				LocalPart string `cbor:"local_part"`
				Domain    string `cbor:"domain"`
			}
			if err := cbor.Unmarshal(enc, &req); err != nil {
				return fmt.Errorf("decode validate_recipient body: %w", err)
			}
			if actor, ok := a.validateRecipientByLocal[req.LocalPart]; ok {
				return encodeReply(map[string]any{"outcome": "resolved", "actor_id": actor}, reply)
			}
			return encodeReply(map[string]any{"outcome": "reject", "reason": "unknown recipient"}, reply)
		}
		if a.validateRecipientReplyHex == "" {
			return encodeReply(map[string]any{"outcome": "reject", "reason": "unknown recipient"}, reply)
		}
		raw, err := hex.DecodeString(a.validateRecipientReplyHex)
		if err != nil {
			return fmt.Errorf("test fake bad hex: %w", err)
		}
		return encodeReply(map[string]any{"outcome": "resolved", "actor_id": raw}, reply)

	case wsrpc.MethodResolveRecipient:
		// The submission RCPT path resolves through resolve_recipient (the
		// superset of validate_recipient). Reuse the same driving fields so the
		// existing RCPT tests exercise the cutover unchanged, and add the Forward
		// outcome for the admin external-forwarder edge.
		if a.validateRecipientErr != nil {
			return a.validateRecipientErr
		}
		var req struct {
			LocalPart    string `cbor:"local_part"`
			Domain       string `cbor:"domain"`
			SenderDomain string `cbor:"sender_domain"`
		}
		if err := cbor.Unmarshal(enc, &req); err != nil {
			return fmt.Errorf("decode resolve_recipient body: %w", err)
		}
		if fwd, ok := a.resolveForwarders[req.LocalPart]; ok {
			return encodeReply(map[string]any{
				"outcome":            "forward",
				"forward_target":     fwd.target,
				"forwarder_actor_id": fwd.admin,
			}, reply)
		}
		if actor, ok := a.validateRecipientByLocal[req.LocalPart]; ok {
			return encodeReply(map[string]any{"outcome": "resolved", "actor_id": actor}, reply)
		}
		if len(a.validateRecipientByLocal) == 0 && a.validateRecipientReplyHex != "" {
			raw, err := hex.DecodeString(a.validateRecipientReplyHex)
			if err != nil {
				return fmt.Errorf("test fake bad hex: %w", err)
			}
			return encodeReply(map[string]any{"outcome": "resolved", "actor_id": raw}, reply)
		}
		return encodeReply(map[string]any{
			"outcome":   "reject",
			"smtp_code": uint16(550),
			"reason":    "unknown recipient",
		}, reply)

	case wsrpc.MethodFetchWrappedSubmissionToken:
		if a.fetchBlobErr != nil {
			return a.fetchBlobErr
		}
		r := struct {
			Blob *[]byte `cbor:"blob"`
		}{Blob: nil}
		if a.submissionBlob != nil {
			b := a.submissionBlob
			r.Blob = &b
		}
		return encodeReply(r, reply)

	case wsrpc.MethodReportAuthEvent:
		return encodeReply(struct {
			OK bool `cbor:"ok"`
		}{OK: true}, reply)

	case wsrpc.MethodCheckSubmissionQuota:
		if a.checkQuotaErr != nil {
			return a.checkQuotaErr
		}
		var outcome checkSubmissionQuotaOutcome
		if len(a.quotaOutcomes) > 0 {
			outcome = a.quotaOutcomes[0]
			a.quotaOutcomes = a.quotaOutcomes[1:]
		}
		if outcome.over {
			return encodeReply(map[string]any{
				"outcome":   "over_quota",
				"remaining": outcome.remaining,
			}, reply)
		}
		return encodeReply(map[string]any{"outcome": "allowed"}, reply)

	case wsrpc.MethodMintBulkByteToken:
		// The submission staging leg mints a MailBody write token before uploading
		// the ciphertext chunks. A short scripted token is enough for the fake
		// byte plane (which ignores the bearer); nest gates the mint in production.
		return encodeReply(map[string]any{
			"token":      "test-mail-body-token",
			"expires_at": uint64(0),
		}, reply)

	case wsrpc.MethodEnqueueOutboundMail:
		if a.enqueueOutboundMailErr != nil {
			return a.enqueueOutboundMailErr
		}
		var req struct {
			OriginalMsgID  string               `cbor:"original_msgid"`
			OriginalSender string               `cbor:"original_sender"`
			Recipients     []string             `cbor:"recipients"`
			RawMessage     []byte               `cbor:"raw_message"`
			StagedBody     *wsrpc.StagedBodyRef `cbor:"staged_body,omitempty"`
		}
		if err := cbor.Unmarshal(enc, &req); err != nil {
			return fmt.Errorf("decode enqueue_outbound_mail body: %w", err)
		}
		a.enqueuedOutbound = append(a.enqueuedOutbound, enqueueOutboundCall{
			OriginalMsgID:  req.OriginalMsgID,
			OriginalSender: req.OriginalSender,
			Recipients:     append([]string(nil), req.Recipients...),
			RawMessage:     append([]byte(nil), req.RawMessage...),
			StagedBody:     req.StagedBody,
		})
		ids := make([]int64, len(req.Recipients))
		for i := range ids {
			ids[i] = int64(i + 1)
		}
		return encodeReply(map[string]any{"ids": ids}, reply)

	case wsrpc.MethodFetchRecipientMLSPubkey:
		if a.fetchRecipientMLSPubkeyErr != nil {
			return a.fetchRecipientMLSPubkeyErr
		}
		r := struct {
			Key               *map[string][]byte `cbor:"key"`
			SuccessionPending bool               `cbor:"succession_pending"`
		}{}
		if a.mlsPubkey != nil {
			key := wsrpctest.RecipientSealKey(a.mlsPubkey)
			r.Key = &key
		} else {
			r.SuccessionPending = a.mlsPubkeySuccessionPending
		}
		return encodeReply(r, reply)

	case wsrpc.MethodFetchRecipientIndexKey:
		r := struct {
			Pubkey *[]byte `cbor:"pubkey"`
		}{}
		if a.indexPubkey != nil {
			b := a.indexPubkey
			r.Pubkey = &b
		}
		return encodeReply(r, reply)

	case wsrpc.MethodSubmitInboundMail:
		if a.submitInboundErr != nil {
			return a.submitInboundErr
		}
		call, err := decodeInboundMailCall(enc)
		if err != nil {
			return err
		}
		a.submitInboundCalls = append(a.submitInboundCalls, call)
		return encodeReply(map[string]any{"message_id": deterministicMessageID(call.ActorID, "submit")}, reply)

	case wsrpc.MethodIngestInboundMail:
		if a.ingestInboundErr != nil {
			return a.ingestInboundErr
		}
		call, err := decodeInboundMailCall(enc)
		if err != nil {
			return err
		}
		a.ingestInboundCalls = append(a.ingestInboundCalls, call)
		return encodeReply(map[string]any{"message_id": deterministicMessageID(call.ActorID, "ingest")}, reply)

	case wsrpc.MethodForwardMessage:
		var req struct {
			ActorID            []byte `cbor:"actor_id"`
			OriginalMsgID      string `cbor:"original_msgid"`
			OriginalSender     string `cbor:"original_sender"`
			Destination        string `cbor:"destination"`
			RawMessage         []byte `cbor:"raw_message"`
			RuleIDOrForwardAll string `cbor:"rule_id_or_forward_all"`
			CopyMode           string `cbor:"copy_mode"`
		}
		if err := cbor.Unmarshal(enc, &req); err != nil {
			return fmt.Errorf("decode forward_message body: %w", err)
		}
		a.forwardRequests = append(a.forwardRequests, forwardRecord{
			actorID:            append([]byte(nil), req.ActorID...),
			originalMsgID:      req.OriginalMsgID,
			originalSender:     req.OriginalSender,
			destination:        req.Destination,
			rawMessage:         append([]byte(nil), req.RawMessage...),
			ruleIDOrForwardAll: req.RuleIDOrForwardAll,
			copyMode:           req.CopyMode,
		})
		if a.forwardMessageErr != nil {
			return a.forwardMessageErr
		}
		return encodeReply(map[string]any{"id": int64(len(a.forwardRequests))}, reply)
	}

	return fmt.Errorf("submissionAuthCaller: unexpected method %q", method)
}

// decodeInboundMailCall unpacks an ingest/submit_inbound_mail request
// body into the test-side capture shape. Only the fields tests need
// to assert on are pulled out; the rest of the wire payload is
// dropped on the floor (HPKE ciphertext bytes are opaque to tests).
func decodeInboundMailCall(body []byte) (inboundMailCall, error) {
	var req struct {
		ActorID            []byte `cbor:"actor_id"`
		EncryptedBody      []byte `cbor:"encrypted_body"`
		EncryptedIndexHint []byte `cbor:"encrypted_index_hint"`
		PublicMetadata     struct {
			Timestamp      int64  `cbor:"timestamp"`
			CiphertextSize uint32 `cbor:"ciphertext_size"`
			SenderDomain   string `cbor:"sender_domain"`
		} `cbor:"public_metadata"`
		Verdicts struct {
			Dkim  struct{ Kind string } `cbor:"dkim"`
			Spf   struct{ Kind string } `cbor:"spf"`
			Dmarc struct{ Kind string } `cbor:"dmarc"`
			Arc   struct{ Kind string } `cbor:"arc"`
		} `cbor:"verdicts"`
		SpamDisposition string `cbor:"spam_disposition"`
	}
	if err := cbor.Unmarshal(body, &req); err != nil {
		return inboundMailCall{}, fmt.Errorf("decode inbound_mail body: %w", err)
	}
	return inboundMailCall{
		ActorID:            append([]byte(nil), req.ActorID...),
		EncryptedBodySize:  len(req.EncryptedBody),
		EncryptedIndexSize: len(req.EncryptedIndexHint),
		SenderDomain:       req.PublicMetadata.SenderDomain,
		SpamDisposition:    req.SpamDisposition,
		Verdicts: map[string]string{
			"dkim":  req.Verdicts.Dkim.Kind,
			"spf":   req.Verdicts.Spf.Kind,
			"dmarc": req.Verdicts.Dmarc.Kind,
			"arc":   req.Verdicts.Arc.Kind,
		},
	}, nil
}

// deterministicMessageID returns a 32-byte slice keyed on actor_id +
// a "submit"/"ingest" suffix so test assertions can tell the two
// apart without parsing the encrypted body. Production message_ids
// derive from the canonical DAG-CBOR encoding; the test fake only
// needs uniqueness + determinism.
func deterministicMessageID(actorID []byte, kind string) []byte {
	out := make([]byte, 32)
	copy(out, actorID)
	out[31] = byte(kind[0])
	return out
}

func encodeReply(value, reply any) error {
	if reply == nil {
		return nil
	}
	enc, err := dagcbor.Marshal(value)
	if err != nil {
		return fmt.Errorf("encode reply: %w", err)
	}
	return cbor.Unmarshal(enc, reply)
}

func (a *submissionAuthCaller) callsOf(method string) []submissionAuthCall {
	a.mu.Lock()
	defer a.mu.Unlock()
	var out []submissionAuthCall
	for _, c := range a.calls {
		if c.method == method {
			out = append(out, c)
		}
	}
	return out
}

// ── Test session construction ────────────────────────────────────

func newTestSubmissionSession(caller *submissionAuthCaller) *submissionSession {
	now := time.Unix(1_700_000_000, 0)
	backend := &submissionBackend{
		logger: slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelError})),
		client: caller,
		nowFn:  func() time.Time { return now },
		cfg: staticMTAConfig(&mtaLiveConfig{
			localDomains:  []string{"example.com"},
			primaryDomain: "example.com",
		}),
	}
	return &submissionSession{
		backend:  backend,
		sourceIP: "10.0.0.1",
	}
}

// ── Tests ─────────────────────────────────────────────────────────

func TestSubmissionPLAINSuccess(t *testing.T) {
	blob := mustReadFixture(t, "wrapped_submission_token.bin")
	caller := &submissionAuthCaller{
		validateRecipientReplyHex: hex.EncodeToString(fixtureActorID()),
		submissionBlob:            blob,
	}
	sess := newTestSubmissionSession(caller)

	payload := auth.BuildPlainPayload("", "alice@example.com", string(fixturePlainPassword))
	if err := sess.authenticate(sasl.Plain, payload); err != nil {
		t.Fatalf("authenticate: %v", err)
	}

	sess.mu.Lock()
	defer sess.mu.Unlock()
	if !sess.authenticated {
		t.Fatal("authenticated flag must flip on success")
	}
	if !bytesEqual(sess.actorID, fixtureActorID()) {
		t.Errorf("actorID = %x", sess.actorID)
	}
	if sess.credentialID != fixtureCredentialID {
		t.Errorf("credentialID = %q", sess.credentialID)
	}
	if sess.authedLocalPart != "alice" {
		t.Errorf("authedLocalPart = %q", sess.authedLocalPart)
	}
	if sess.submissionToken == nil {
		t.Fatal("submissionToken must be stashed on success")
	}
	if sess.submissionToken.MaxRecipients != 100 {
		t.Errorf("MaxRecipients = %d, want 100", sess.submissionToken.MaxRecipients)
	}
	if got := caller.callsOf(wsrpc.MethodReportAuthEvent); len(got) != 1 {
		t.Fatalf("report_auth_event fired %d times, want 1", len(got))
	}
}

// TestSubmissionBareUsernameResolvesUnderPrimaryDomain pins the uniform
// bare-username fix on the MTA submission surface: a SASL username with no
// `@domain` resolves under the box's PrimaryDomain (auth.SplitEmailDefault),
// matching the CalDAV + IMAP surfaces (priority #1 — no per-surface auth
// divergence; the same fix that unblocks macOS Calendar.app on CalDAV).
func TestSubmissionBareUsernameResolvesUnderPrimaryDomain(t *testing.T) {
	blob := mustReadFixture(t, "wrapped_submission_token.bin")
	caller := &submissionAuthCaller{
		validateRecipientReplyHex: hex.EncodeToString(fixtureActorID()),
		submissionBlob:            blob,
	}
	sess := newTestSubmissionSession(caller) // holder primaryDomain = "example.com"

	payload := auth.BuildPlainPayload("", "alice", string(fixturePlainPassword)) // bare username
	if err := sess.authenticate(sasl.Plain, payload); err != nil {
		t.Fatalf("bare username must authenticate under PrimaryDomain: %v", err)
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	if !sess.authenticated {
		t.Fatal("authenticated flag must flip on a bare-username success")
	}
	if sess.authedLocalPart != "alice" {
		t.Errorf("authedLocalPart = %q, want %q", sess.authedLocalPart, "alice")
	}
	calls := caller.callsOf(wsrpc.MethodValidateRecipient)
	if len(calls) != 1 {
		t.Fatalf("validate_recipient fired %d times, want 1", len(calls))
	}
	var got struct {
		LocalPart string `cbor:"local_part"`
		Domain    string `cbor:"domain"`
	}
	if err := cbor.Unmarshal(calls[0].body, &got); err != nil {
		t.Fatalf("decode validate_recipient body: %v", err)
	}
	if got.LocalPart != "alice" || got.Domain != "example.com" {
		t.Errorf("validate_recipient (local,domain) = (%q,%q), want (alice,example.com)", got.LocalPart, got.Domain)
	}
}

func TestSubmissionPLAINFailsWithWrongPassword(t *testing.T) {
	blob := mustReadFixture(t, "wrapped_submission_token.bin")
	caller := &submissionAuthCaller{
		validateRecipientReplyHex: hex.EncodeToString(fixtureActorID()),
		submissionBlob:            blob,
	}
	sess := newTestSubmissionSession(caller)

	payload := auth.BuildPlainPayload("", "alice@example.com", "WRONG-PASSWORD")
	err := sess.authenticate(sasl.Plain, payload)
	if err == nil {
		t.Fatal("wrong password must produce an AUTH error")
	}
	if err != errSubmissionAuthFailed {
		t.Errorf("wire error = %v, want errSubmissionAuthFailed", err)
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	if sess.authenticated {
		t.Fatal("AUTH-fail must leave session unauthenticated")
	}
	if sess.submissionToken != nil {
		t.Fatal("AUTH-fail must not stash token")
	}
	if got := caller.callsOf(wsrpc.MethodReportAuthEvent); len(got) != 1 {
		t.Fatalf("report_auth_event fired %d times on fail, want 1", len(got))
	}
}

func TestSubmissionOAUTHBEARERSuccess(t *testing.T) {
	blob := mustReadFixture(t, "wrapped_submission_token_oauth.bin")
	caller := &submissionAuthCaller{
		validateRecipientReplyHex: hex.EncodeToString(fixtureActorID()),
		submissionBlob:            blob,
	}
	sess := newTestSubmissionSession(caller)

	payload := auth.BuildOAuthBearerPayload("alice@example.com", string(fixtureOAuthToken))
	if err := sess.authenticate(sasl.OAuthBearer, payload); err != nil {
		t.Fatalf("authenticate OAUTHBEARER: %v", err)
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	if !sess.authenticated {
		t.Fatal("authenticated flag must flip on OAUTHBEARER success")
	}
	if got := caller.callsOf(wsrpc.MethodReportAuthEvent); len(got) != 1 {
		t.Fatalf("report_auth_event fired %d times, want 1", len(got))
	}
}

func TestSubmissionOAUTHBEARERFailsWithWrongToken(t *testing.T) {
	blob := mustReadFixture(t, "wrapped_submission_token_oauth.bin")
	caller := &submissionAuthCaller{
		validateRecipientReplyHex: hex.EncodeToString(fixtureActorID()),
		submissionBlob:            blob,
	}
	sess := newTestSubmissionSession(caller)

	payload := auth.BuildOAuthBearerPayload("alice@example.com", "WRONG-TOKEN")
	if err := sess.authenticate(sasl.OAuthBearer, payload); err == nil {
		t.Fatal("wrong token must produce an AUTH error")
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	if sess.authenticated {
		t.Fatal("AUTH-fail must leave session unauthenticated")
	}
	if got := caller.callsOf(wsrpc.MethodReportAuthEvent); len(got) != 1 {
		t.Fatalf("report_auth_event fired %d times on fail, want 1", len(got))
	}
}

func TestSubmissionAuthFailsWhenNestHasNoBlob(t *testing.T) {
	caller := &submissionAuthCaller{
		validateRecipientReplyHex: hex.EncodeToString(fixtureActorID()),
		submissionBlob:            nil, // nest: no blob on file
	}
	sess := newTestSubmissionSession(caller)

	err := sess.authenticate(sasl.Plain, auth.BuildPlainPayload("", "alice@example.com", "any"))
	if err == nil {
		t.Fatal("missing blob must produce an AUTH error")
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	if sess.authenticated {
		t.Fatal("missing blob must leave session unauthenticated")
	}
	if got := caller.callsOf(wsrpc.MethodReportAuthEvent); len(got) != 1 {
		t.Fatalf("report_auth_event fired %d times on missing-blob, want 1", len(got))
	}
}

func TestSubmissionAuthRejectsUnknownMech(t *testing.T) {
	caller := &submissionAuthCaller{}
	sess := newTestSubmissionSession(caller)
	if err := sess.authenticate("LOGIN", "alice"); err == nil {
		t.Fatal("LOGIN mech must be rejected")
	}
	if err := sess.authenticate("CRAM-MD5", ""); err == nil {
		t.Fatal("CRAM-MD5 mech must be rejected")
	}
	if len(caller.calls) != 0 {
		t.Fatalf("unknown-mech path must not call wsrpc; got %d calls", len(caller.calls))
	}
}

func TestSubmissionAuthMechanismsAdvertised(t *testing.T) {
	sess := newTestSubmissionSession(&submissionAuthCaller{})
	mechs := sess.AuthMechanisms()
	want := map[string]bool{sasl.Plain: true, sasl.OAuthBearer: true}
	for _, m := range mechs {
		if !want[m] {
			t.Errorf("advertised unexpected mech %q", m)
		}
		delete(want, m)
	}
	for m := range want {
		t.Errorf("missing required mech %q", m)
	}
}

func TestSubmissionPLAINFailsOnAuthzIDMismatch(t *testing.T) {
	// RFC 4616: authzid must be empty or equal to authcid.
	// Mismatch returns errSubmissionAuthFailed pre-resolution, so
	// no validate_recipient call should fire.
	caller := &submissionAuthCaller{}
	sess := newTestSubmissionSession(caller)
	payload := auth.BuildPlainPayload("eve@evil", "alice@example.com", "any")
	err := sess.authenticate(sasl.Plain, payload)
	if err == nil {
		t.Fatal("authzid mismatch must produce an AUTH error")
	}
	if len(caller.callsOf(wsrpc.MethodValidateRecipient)) != 0 {
		t.Fatal("authzid mismatch must NOT call validate_recipient")
	}
	if got := caller.callsOf(wsrpc.MethodReportAuthEvent); len(got) != 1 {
		t.Fatalf("report_auth_event fired %d times on authzid-mismatch, want 1", len(got))
	}
}

// ── Phase D.7: per-(credential, IP) lockout integration ─────────

// TestSubmissionAuthLockoutRejectsAfter30Failures pins the wire
// contract: with a 30-failure-per-minute limit, 30 failed AUTH
// attempts from the same (presented_user, credential, source_ip)
// produce one fetch_wrapped_submission_token + AEAD-unwrap each (the
// gate is the normal post-AEAD failure path) and the 31st attempt
// returns SMTP 421 4.7.0 *before* any nest call fires — no
// fetch_wrapped_submission_token on the 31st, no AEAD attempt, and
// no report_auth_event row.
func TestSubmissionAuthLockoutRejectsAfter30Failures(t *testing.T) {
	t.Parallel()
	blob := mustReadFixture(t, "wrapped_submission_token.bin")
	caller := &submissionAuthCaller{
		validateRecipientReplyHex: hex.EncodeToString(fixtureActorID()),
		submissionBlob:            blob,
	}
	sess := newTestSubmissionSession(caller)
	lc := *sess.backend.cfg.current()
	lc.authLockout = NewAuthLockout(30, time.Minute, newFakeLockoutClock())
	sess.backend.cfg = staticMTAConfig(&lc)

	// 30 failed PLAIN AUTH attempts. Each goes through the full
	// path (validate_recipient → fetch_wrapped_submission_token →
	// unseal-fail → report_auth_event{fail}) and records a failure
	// against the lockout bucket.
	for i := 0; i < 30; i++ {
		err := sess.authenticate(sasl.Plain,
			auth.BuildPlainPayload("", "alice@example.com", "WRONG-PASSWORD"))
		if err == nil {
			t.Fatalf("attempt %d: expected wrong-password failure, got nil", i+1)
		}
		if err != errSubmissionAuthFailed {
			t.Fatalf("attempt %d: wire = %v, want errSubmissionAuthFailed", i+1, err)
		}
	}

	priorFetchCount := len(caller.callsOf(wsrpc.MethodFetchWrappedSubmissionToken))
	priorAuthEventCount := len(caller.callsOf(wsrpc.MethodReportAuthEvent))
	if priorFetchCount != 30 {
		t.Fatalf("setup invariant: fetch_wrapped_submission_token fired %d times; want 30", priorFetchCount)
	}
	if priorAuthEventCount != 30 {
		t.Fatalf("setup invariant: report_auth_event fired %d times; want 30", priorAuthEventCount)
	}

	// 31st attempt MUST trip the lockout: 421 4.7.0 on the wire, no
	// new fetch_wrapped_submission_token call, no new
	// report_auth_event audit row.
	err := sess.authenticate(sasl.Plain,
		auth.BuildPlainPayload("", "alice@example.com", "WRONG-PASSWORD"))
	if err != errSubmissionAuthLockedOut {
		t.Fatalf("31st attempt: wire = %v, want errSubmissionAuthLockedOut", err)
	}

	if got := len(caller.callsOf(wsrpc.MethodFetchWrappedSubmissionToken)); got != priorFetchCount {
		t.Errorf("31st attempt fired fetch_wrapped_submission_token (got %d total, want %d)",
			got, priorFetchCount)
	}
	if got := len(caller.callsOf(wsrpc.MethodReportAuthEvent)); got != priorAuthEventCount {
		t.Errorf("31st attempt fired report_auth_event (got %d total, want %d)",
			got, priorAuthEventCount)
	}

	// 32nd attempt with the *correct* password also locks out — the
	// budget is per (user, IP) and a brute-forcer can't slip through
	// on a guess once the gate closes. Reset only fires on a real
	// AUTH success, which can't happen while the gate is locked.
	err = sess.authenticate(sasl.Plain,
		auth.BuildPlainPayload("", "alice@example.com", string(fixturePlainPassword)))
	if err != errSubmissionAuthLockedOut {
		t.Fatalf("32nd attempt (correct password): wire = %v, want errSubmissionAuthLockedOut", err)
	}
	if got := len(caller.callsOf(wsrpc.MethodFetchWrappedSubmissionToken)); got != priorFetchCount {
		t.Errorf("locked-out correct-password attempt still fired fetch_wrapped_submission_token (got %d total, want %d)",
			got, priorFetchCount)
	}
}

// TestSubmissionAuthLockoutResetsOnSuccess — a legitimate AUTH (the
// fixture password) before the 31st attempt resets the bucket, so the
// next 30 fresh failures don't trip the gate. Mirrors the typo-fest
// shape: an honest user fat-fingers a few times, then succeeds, and
// shouldn't be locked out by their prior typos.
func TestSubmissionAuthLockoutResetsOnSuccess(t *testing.T) {
	t.Parallel()
	blob := mustReadFixture(t, "wrapped_submission_token.bin")
	caller := &submissionAuthCaller{
		validateRecipientReplyHex: hex.EncodeToString(fixtureActorID()),
		submissionBlob:            blob,
	}
	sess := newTestSubmissionSession(caller)
	lc := *sess.backend.cfg.current()
	lc.authLockout = NewAuthLockout(3, time.Minute, newFakeLockoutClock())
	sess.backend.cfg = staticMTAConfig(&lc)

	// Two typos.
	for i := 0; i < 2; i++ {
		if err := sess.authenticate(sasl.Plain,
			auth.BuildPlainPayload("", "alice@example.com", "WRONG")); err == nil {
			t.Fatalf("typo %d should fail", i+1)
		}
	}
	// Success — the lockout bucket resets.
	if err := sess.authenticate(sasl.Plain,
		auth.BuildPlainPayload("", "alice@example.com", string(fixturePlainPassword))); err != nil {
		t.Fatalf("correct password must succeed: %v", err)
	}
	// Reset the session so we can probe AUTH again with the lockout
	// bucket cleared. (The successful AUTH stashed state on the
	// session; we want to drive the wire path fresh.)
	sess.mu.Lock()
	sess.authenticated = false
	sess.submissionToken = nil
	sess.actorID = nil
	sess.credentialID = ""
	sess.authedLocalPart = ""
	sess.mu.Unlock()

	// Three fresh failures must NOT lock — the bucket was reset by
	// the successful AUTH above. The 3rd failure brings count back
	// to 3 but doesn't lock the *4th* attempt either, because limit=3
	// means 3 failures still allowed.
	for i := 0; i < 3; i++ {
		if err := sess.authenticate(sasl.Plain,
			auth.BuildPlainPayload("", "alice@example.com", "WRONG")); err != errSubmissionAuthFailed {
			t.Fatalf("fresh failure %d after reset: wire = %v, want errSubmissionAuthFailed", i+1, err)
		}
	}
}

// ── Helpers ───────────────────────────────────────────────────────

func bytesEqual(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// Compile-time assertion: submissionAuthCaller satisfies wsrpc.Caller's
// call shape. Kept local to avoid pulling wsrpc into the test
// imports beyond the package boundary.
type wsrpcCaller interface {
	Call(ctx context.Context, method string, body, reply any) error
}

var _ wsrpcCaller = (*submissionAuthCaller)(nil)
